// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.
// 源:core/api_routes.py 组装出的权威 API 层的 OpenAPI 文档。
// 后端加/删/改端点后重跑该脚本;CI 会比对生成结果是否与后端一致。

// 路径 396 条 · 组件 schema 103 个

/** 权威 API 层的全部路径。写错或调一个不存在的端点 → 编译期报错。 */
export type ApiPath =
  | "/api/config"
  | "/api/config/all"
  | "/api/config/probe"
  | "/api/config/save"
  | "/api/devices/heartbeat"
  | "/api/devices/list"
  | "/api/devices/register"
  | "/api/devices/unregister"
  | "/api/perception/desktop/analyze"
  | "/api/perception/desktop/audio"
  | "/api/perception/desktop/audio/echo_cancellation"
  | "/api/perception/desktop/frame"
  | "/api/perception/desktop/listen"
  | "/api/perception/desktop/privacy"
  | "/api/perception/desktop/privacy/pause"
  | "/api/perception/desktop/privacy/resume"
  | "/api/perception/desktop/status"
  | "/api/perception/desktop/system_audio"
  | "/api/perception/desktop/system_audio/probe"
  | "/api/remote-desktop/disable"
  | "/api/remote-desktop/enable"
  | "/api/remote-desktop/status"
  | "/api/v1/acceptance/cross-repo-chain"
  | "/api/v1/acceptance/dual-repo-completeness-baseline"
  | "/api/v1/agent/autonomous"
  | "/api/v1/agent/create"
  | "/api/v1/agent/deploy"
  | "/api/v1/agent/status"
  | "/api/v1/agent/templates"
  | "/api/v1/agents/debate"
  | "/api/v1/agents/linux/servers"
  | "/api/v1/agents/linux/servers/{server_id}"
  | "/api/v1/agents/linux/servers/{server_id}/execute"
  | "/api/v1/agents/linux/servers/{server_id}/file/read"
  | "/api/v1/agents/linux/servers/{server_id}/file/write"
  | "/api/v1/agents/linux/servers/{server_id}/info"
  | "/api/v1/agents/linux/servers/{server_id}/probe"
  | "/api/v1/agents/sandbox/execute"
  | "/api/v1/agents/sandbox/status"
  | "/api/v1/agents/sandbox/validate"
  | "/api/v1/agents/status"
  | "/api/v1/agents/swarm"
  | "/api/v1/agents/twin"
  | "/api/v1/agents/{agent_id}/children"
  | "/api/v1/agents/{agent_id}/split"
  | "/api/v1/ai/conversation"
  | "/api/v1/ai/conversation/{session_id}"
  | "/api/v1/ai/intent"
  | "/api/v1/ai/recommendations/{session_id}"
  | "/api/v1/approval-grants"
  | "/api/v1/approval-grants/{grant_key}"
  | "/api/v1/approvals"
  | "/api/v1/approvals/{request_id}"
  | "/api/v1/audit/snapshot"
  | "/api/v1/audit/traces"
  | "/api/v1/audit/traces/{trace_id}"
  | "/api/v1/audit/traces/{trace_id}/dag"
  | "/api/v1/audit/traces/{trace_id}/graph"
  | "/api/v1/audit/traces/{trace_id}/timeline"
  | "/api/v1/capabilities/runtime"
  | "/api/v1/capabilities/runtime/{capability_name}"
  | "/api/v1/channels"
  | "/api/v1/channels/auto_load"
  | "/api/v1/channels/health"
  | "/api/v1/channels/load"
  | "/api/v1/channels/{plugin_id}/schema"
  | "/api/v1/channels/{plugin_id}/send"
  | "/api/v1/chat"
  | "/api/v1/chat/stream"
  | "/api/v1/code/execute"
  | "/api/v1/code/stats"
  | "/api/v1/command"
  | "/api/v1/command/unified"
  | "/api/v1/command/unified/{request_id}/status"
  | "/api/v1/command/{request_id}"
  | "/api/v1/command/{request_id}/status"
  | "/api/v1/computer-use/status"
  | "/api/v1/computer-use/task"
  | "/api/v1/concurrency/status"
  | "/api/v1/config"
  | "/api/v1/config/status"
  | "/api/v1/config/versions"
  | "/api/v1/connectors"
  | "/api/v1/connectors/{service}/authorize"
  | "/api/v1/connectors/{service}/callback"
  | "/api/v1/connectors/{service}/credentials"
  | "/api/v1/connectors/{service}/disconnect"
  | "/api/v1/contracts/messages"
  | "/api/v1/contracts/planes"
  | "/api/v1/contracts/reliability"
  | "/api/v1/cost/health"
  | "/api/v1/cost/records"
  | "/api/v1/cost/summary"
  | "/api/v1/devices"
  | "/api/v1/devices/cross-device"
  | "/api/v1/devices/cross-device-ready"
  | "/api/v1/devices/discover"
  | "/api/v1/devices/discover-active"
  | "/api/v1/devices/health"
  | "/api/v1/devices/parallel"
  | "/api/v1/devices/participation"
  | "/api/v1/devices/readiness"
  | "/api/v1/devices/register"
  | "/api/v1/devices/runtime-hosts"
  | "/api/v1/devices/status"
  | "/api/v1/devices/transfer"
  | "/api/v1/devices/{device_id}"
  | "/api/v1/devices/{device_id}/command"
  | "/api/v1/devices/{device_id}/health"
  | "/api/v1/devices/{device_id}/heartbeat"
  | "/api/v1/devices/{device_id}/participation"
  | "/api/v1/devices/{device_id}/readiness"
  | "/api/v1/devices/{device_id}/runtime-contract"
  | "/api/v1/devices/{device_id}/runtime-host"
  | "/api/v1/devices/{device_id}/telemetry"
  | "/api/v1/devices/{device_id}/unquarantine"
  | "/api/v1/diagnostics/startup-timing"
  | "/api/v1/diagnostics/url-sentinel"
  | "/api/v1/discovery/status"
  | "/api/v1/errors/summary"
  | "/api/v1/execution/merge-summary"
  | "/api/v1/existence/surface"
  | "/api/v1/federation/forward"
  | "/api/v1/federation/health"
  | "/api/v1/federation/heartbeat"
  | "/api/v1/federation/info"
  | "/api/v1/federation/peers"
  | "/api/v1/federation/peers/cleanup"
  | "/api/v1/federation/peers/{instance_id}"
  | "/api/v1/federation/peers/{instance_id}/ping"
  | "/api/v1/federation/task"
  | "/api/v1/github/context"
  | "/api/v1/github/ingest"
  | "/api/v1/github/install"
  | "/api/v1/github/list"
  | "/api/v1/github/status"
  | "/api/v1/github/uninstall"
  | "/api/v1/governance/budget/record"
  | "/api/v1/governance/budget/{session_id}"
  | "/api/v1/governance/policy"
  | "/api/v1/governance/queue/stats"
  | "/api/v1/governance/tools/audit"
  | "/api/v1/governance/tools/check"
  | "/api/v1/governance/tools/policy"
  | "/api/v1/guardian/audit"
  | "/api/v1/health/quick"
  | "/api/v1/health/unified"
  | "/api/v1/hybrid/execute"
  | "/api/v1/hybrid/registry"
  | "/api/v1/hybrid/stats"
  | "/api/v1/memory/cold"
  | "/api/v1/memory/drift/check"
  | "/api/v1/memory/drift/config"
  | "/api/v1/memory/query"
  | "/api/v1/memory/stats"
  | "/api/v1/memory/store"
  | "/api/v1/memory/tasks"
  | "/api/v1/memory/unified/status"
  | "/api/v1/mesh/android-lifecycle"
  | "/api/v1/mesh/coordinator-summary"
  | "/api/v1/mesh/memberships"
  | "/api/v1/mesh/participation-summary"
  | "/api/v1/mesh/peer_announce"
  | "/api/v1/mesh/peer_exchange"
  | "/api/v1/mesh/peers"
  | "/api/v1/mesh/probe"
  | "/api/v1/mesh/send"
  | "/api/v1/mesh/session"
  | "/api/v1/mesh/stats"
  | "/api/v1/mesh/topology"
  | "/api/v1/mesh/worker"
  | "/api/v1/mesh/worker/toggle"
  | "/api/v1/modality/devices"
  | "/api/v1/modality/matrix"
  | "/api/v1/modality/plan"
  | "/api/v1/modality/providers"
  | "/api/v1/models/catalog"
  | "/api/v1/models/latency-probe"
  | "/api/v1/models/routing-stats"
  | "/api/v1/models/slot"
  | "/api/v1/models/status"
  | "/api/v1/models/sync"
  | "/api/v1/models/tier"
  | "/api/v1/models/verify-provider"
  | "/api/v1/monitoring/alerts"
  | "/api/v1/monitoring/dashboard"
  | "/api/v1/monitoring/health"
  | "/api/v1/monitoring/metrics"
  | "/api/v1/monitoring/performance"
  | "/api/v1/nodes"
  | "/api/v1/nodes/call"
  | "/api/v1/nodes/legacy/filesystem"
  | "/api/v1/nodes/roster"
  | "/api/v1/nodes/status"
  | "/api/v1/nodes/{node_name}"
  | "/api/v1/nodes/{node}/start"
  | "/api/v1/nodes/{node}/stop"
  | "/api/v1/observability/bus-events"
  | "/api/v1/observability/context-layer"
  | "/api/v1/observability/execution-legibility"
  | "/api/v1/observability/execution/evidence-state"
  | "/api/v1/observability/execution/evidence-state/{task_id}"
  | "/api/v1/observability/execution/recent-events"
  | "/api/v1/observability/execution/schema"
  | "/api/v1/observability/execution/trace/{trace_id}"
  | "/api/v1/observability/gateway"
  | "/api/v1/observability/model-route"
  | "/api/v1/observability/nats"
  | "/api/v1/observability/orchestration-review"
  | "/api/v1/observability/recent-calls"
  | "/api/v1/observability/stats"
  | "/api/v1/observability/trace/{trace_id}"
  | "/api/v1/opencode/configure"
  | "/api/v1/opencode/generate"
  | "/api/v1/opencode/status"
  | "/api/v1/operator/action"
  | "/api/v1/operator/actions/android-directed"
  | "/api/v1/operator/actions/android-directed/{dispatch_id}/ack"
  | "/api/v1/operator/actions/audit"
  | "/api/v1/operator/actions/availability"
  | "/api/v1/operator/board/operable-truth"
  | "/api/v1/operator/devices/dispatch-readiness"
  | "/api/v1/operator/devices/ecosystem"
  | "/api/v1/operator/devices/ecosystem/{device_id}"
  | "/api/v1/operator/devices/execution-events"
  | "/api/v1/operator/devices/{device_id}/dispatch-readiness"
  | "/api/v1/operator/dispatch"
  | "/api/v1/operator/flows"
  | "/api/v1/operator/flows/{flow_id}"
  | "/api/v1/operator/flows/{flow_id}/cancel"
  | "/api/v1/operator/heartbeat"
  | "/api/v1/operator/inspect/audit-evidence/{task_id}"
  | "/api/v1/operator/inspect/executor/{node_id}"
  | "/api/v1/operator/inspect/failure/{task_id}"
  | "/api/v1/operator/inspect/flow/{flow_id}"
  | "/api/v1/operator/inspect/lineage/{task_id}"
  | "/api/v1/operator/inspect/partial-result/{task_id}"
  | "/api/v1/operator/inspect/recovery/{task_id}"
  | "/api/v1/operator/inspect/route/{task_id}"
  | "/api/v1/operator/inspect/task/{task_id}"
  | "/api/v1/operator/llm"
  | "/api/v1/operator/nats"
  | "/api/v1/operator/pr4/snapshot"
  | "/api/v1/operator/presence/ambient"
  | "/api/v1/operator/presence/ambient/halt"
  | "/api/v1/operator/review/{task_id}"
  | "/api/v1/operator/snapshot"
  | "/api/v1/pair/card"
  | "/api/v1/pair/check"
  | "/api/v1/pair/claim"
  | "/api/v1/pair/paths"
  | "/api/v1/pair/peers"
  | "/api/v1/pair/peers/{device_id}"
  | "/api/v1/pair/trust"
  | "/api/v1/panel/feed"
  | "/api/v1/panel/unified"
  | "/api/v1/ports"
  | "/api/v1/projection/agent-dispatch"
  | "/api/v1/projection/canonical-routing"
  | "/api/v1/projection/clone-to-use-acceptance"
  | "/api/v1/projection/cross_device_routing"
  | "/api/v1/projection/desktop-status-board"
  | "/api/v1/projection/device-formation"
  | "/api/v1/projection/dual-repo-integrated-system-contract"
  | "/api/v1/projection/execution_policy"
  | "/api/v1/projection/governance"
  | "/api/v1/projection/operability-contract"
  | "/api/v1/projection/operational-readiness"
  | "/api/v1/projection/policy-alignment"
  | "/api/v1/projection/return"
  | "/api/v1/projection/routing-explanation"
  | "/api/v1/projection/runtime"
  | "/api/v1/projection/runtime-governance"
  | "/api/v1/projection/runtime-truth"
  | "/api/v1/projection/runtime/multi-device"
  | "/api/v1/projection/runtime/recovery"
  | "/api/v1/projection/runtime/session-snapshot"
  | "/api/v1/projection/server-canonicalization-status"
  | "/api/v1/projection/task_semantics"
  | "/api/v1/protocols/load-status"
  | "/api/v1/protocols/mcp"
  | "/api/v1/protocols/mcp/load"
  | "/api/v1/protocols/mcp/{name}"
  | "/api/v1/protocols/mcp/{name}/call"
  | "/api/v1/protocols/mcp/{name}/reload"
  | "/api/v1/protocols/mcp/{name}/tools"
  | "/api/v1/protocols/reload-all"
  | "/api/v1/protocols/skills"
  | "/api/v1/protocols/skills/load"
  | "/api/v1/protocols/skills/{name}"
  | "/api/v1/protocols/skills/{name}/execute"
  | "/api/v1/protocols/skills/{name}/reload"
  | "/api/v1/protocols/status"
  | "/api/v1/rag/patterns"
  | "/api/v1/rag/query"
  | "/api/v1/rag/stats"
  | "/api/v1/readiness"
  | "/api/v1/relay/broadcast"
  | "/api/v1/relay/history"
  | "/api/v1/relay/send"
  | "/api/v1/relay/stats"
  | "/api/v1/resilience/circuit-breakers"
  | "/api/v1/resilience/circuit-breakers/{target}/reset"
  | "/api/v1/resilience/metrics"
  | "/api/v1/resilience/metrics/prom"
  | "/api/v1/runtime/domain"
  | "/api/v1/runtime/result-merge-summary"
  | "/api/v1/runtime/scope-authority"
  | "/api/v1/runtime/source-dispatch-summary"
  | "/api/v1/runtime/takeover"
  | "/api/v1/security/audit"
  | "/api/v1/security/connection-provenance"
  | "/api/v1/security/context-provenance"
  | "/api/v1/security/egress"
  | "/api/v1/security/execution-isolation"
  | "/api/v1/security/policy"
  | "/api/v1/security/policy/evaluate"
  | "/api/v1/security/stats"
  | "/api/v1/security/weights-admission"
  | "/api/v1/sessions"
  | "/api/v1/sessions/ingest_turns"
  | "/api/v1/sessions/migrate"
  | "/api/v1/sessions/reconcile"
  | "/api/v1/sessions/{session_id}"
  | "/api/v1/sessions/{session_id}/history"
  | "/api/v1/sessions/{session_id}/join"
  | "/api/v1/sessions/{session_id}/sync"
  | "/api/v1/slo/metrics"
  | "/api/v1/slo/operational"
  | "/api/v1/strategy/mappings"
  | "/api/v1/stream"
  | "/api/v1/system/completion-status"
  | "/api/v1/system/config"
  | "/api/v1/system/dual-repo-progress"
  | "/api/v1/system/health"
  | "/api/v1/system/mcp"
  | "/api/v1/system/mode-status"
  | "/api/v1/system/skills"
  | "/api/v1/system/status"
  | "/api/v1/system/subsystems"
  | "/api/v1/tasks"
  | "/api/v1/tasks/groups/{group_id}/cancel"
  | "/api/v1/tasks/{task_id}"
  | "/api/v1/tasks/{task_id}/cancel"
  | "/api/v1/tasks/{task_id}/result"
  | "/api/v1/twin/create"
  | "/api/v1/twin/scenario"
  | "/api/v1/twin/status"
  | "/api/v1/twin/{twin_id}"
  | "/api/v1/twin/{twin_id}/couple"
  | "/api/v1/twin/{twin_id}/decouple"
  | "/api/v1/twin/{twin_id}/drift"
  | "/api/v1/twin/{twin_id}/predict"
  | "/api/v1/twin/{twin_id}/simulate"
  | "/api/v1/twin/{twin_id}/switch-mode"
  | "/api/v1/ui/act"
  | "/api/v1/ui/perception"
  | "/api/v1/vault/audit"
  | "/api/v1/vault/cleanup"
  | "/api/v1/vault/credentials"
  | "/api/v1/vault/credentials/{key_name}"
  | "/api/v1/vault/fetch"
  | "/api/v1/vault/health"
  | "/api/v1/vault/tokens"
  | "/api/v1/vault/tokens/validate"
  | "/api/v1/vault/tokens/{token}/info"
  | "/api/v1/vision/observe"
  | "/api/v1/vision/ocr"
  | "/api/v1/vision/understand"
  | "/api/v1/webrtc/endpoint"
  | "/api/v5/autonomous_programming"
  | "/api/v5/debug_code"
  | "/api/v5/generate_code"
  | "/api/v5/health"
  | "/api/v5/learn_from_experience"
  | "/api/v5/optimize_code"
  | "/api/v5/reason"
  | "/api/v5/stats"
  | "/auth/oauth/callback"
  | "/auth/oauth/device/poll"
  | "/auth/oauth/device/start"
  | "/auth/oauth/github"
  | "/auth/oauth/google"
  | "/auth/oauth/health"
  | "/auth/oauth/logout"
  | "/auth/oauth/me"
  | "/auth/oauth/providers"
  | "/auth/oauth/refresh"
  | "/auth/oauth/{provider}/authorize"
  | "/health/metrics"
  | "/health/nats"
  | "/metrics"
  | "/sync/status"
  | "/v1/audio/capabilities"
  | "/v1/audio/speech"
  | "/v1/audio/transcriptions"
;

/** 每条路径允许的 HTTP 方法。用错方法 → 编译期报错。 */
export const API_METHODS = {
  "/api/config": ["get", "post"],
  "/api/config/all": ["get"],
  "/api/config/probe": ["post"],
  "/api/config/save": ["post"],
  "/api/devices/heartbeat": ["post"],
  "/api/devices/list": ["get"],
  "/api/devices/register": ["post"],
  "/api/devices/unregister": ["post"],
  "/api/perception/desktop/analyze": ["post"],
  "/api/perception/desktop/audio": ["post"],
  "/api/perception/desktop/audio/echo_cancellation": ["get"],
  "/api/perception/desktop/frame": ["post"],
  "/api/perception/desktop/listen": ["post"],
  "/api/perception/desktop/privacy": ["get"],
  "/api/perception/desktop/privacy/pause": ["post"],
  "/api/perception/desktop/privacy/resume": ["post"],
  "/api/perception/desktop/status": ["get"],
  "/api/perception/desktop/system_audio": ["post"],
  "/api/perception/desktop/system_audio/probe": ["get"],
  "/api/remote-desktop/disable": ["post"],
  "/api/remote-desktop/enable": ["post"],
  "/api/remote-desktop/status": ["get"],
  "/api/v1/acceptance/cross-repo-chain": ["get"],
  "/api/v1/acceptance/dual-repo-completeness-baseline": ["get"],
  "/api/v1/agent/autonomous": ["post"],
  "/api/v1/agent/create": ["post"],
  "/api/v1/agent/deploy": ["post"],
  "/api/v1/agent/status": ["get"],
  "/api/v1/agent/templates": ["get"],
  "/api/v1/agents/debate": ["post"],
  "/api/v1/agents/linux/servers": ["get", "post"],
  "/api/v1/agents/linux/servers/{server_id}": ["delete", "get"],
  "/api/v1/agents/linux/servers/{server_id}/execute": ["post"],
  "/api/v1/agents/linux/servers/{server_id}/file/read": ["post"],
  "/api/v1/agents/linux/servers/{server_id}/file/write": ["post"],
  "/api/v1/agents/linux/servers/{server_id}/info": ["get"],
  "/api/v1/agents/linux/servers/{server_id}/probe": ["post"],
  "/api/v1/agents/sandbox/execute": ["post"],
  "/api/v1/agents/sandbox/status": ["get"],
  "/api/v1/agents/sandbox/validate": ["post"],
  "/api/v1/agents/status": ["get"],
  "/api/v1/agents/swarm": ["post"],
  "/api/v1/agents/twin": ["post"],
  "/api/v1/agents/{agent_id}/children": ["get"],
  "/api/v1/agents/{agent_id}/split": ["post"],
  "/api/v1/ai/conversation": ["post"],
  "/api/v1/ai/conversation/{session_id}": ["delete", "get"],
  "/api/v1/ai/intent": ["post"],
  "/api/v1/ai/recommendations/{session_id}": ["get"],
  "/api/v1/approval-grants": ["get"],
  "/api/v1/approval-grants/{grant_key}": ["delete"],
  "/api/v1/approvals": ["get"],
  "/api/v1/approvals/{request_id}": ["get", "post"],
  "/api/v1/audit/snapshot": ["get"],
  "/api/v1/audit/traces": ["get"],
  "/api/v1/audit/traces/{trace_id}": ["get"],
  "/api/v1/audit/traces/{trace_id}/dag": ["get"],
  "/api/v1/audit/traces/{trace_id}/graph": ["get"],
  "/api/v1/audit/traces/{trace_id}/timeline": ["get"],
  "/api/v1/capabilities/runtime": ["get"],
  "/api/v1/capabilities/runtime/{capability_name}": ["get"],
  "/api/v1/channels": ["get"],
  "/api/v1/channels/auto_load": ["post"],
  "/api/v1/channels/health": ["get"],
  "/api/v1/channels/load": ["post"],
  "/api/v1/channels/{plugin_id}/schema": ["get"],
  "/api/v1/channels/{plugin_id}/send": ["post"],
  "/api/v1/chat": ["post"],
  "/api/v1/chat/stream": ["post"],
  "/api/v1/code/execute": ["post"],
  "/api/v1/code/stats": ["get"],
  "/api/v1/command": ["get", "post"],
  "/api/v1/command/unified": ["post"],
  "/api/v1/command/unified/{request_id}/status": ["get"],
  "/api/v1/command/{request_id}": ["delete", "get"],
  "/api/v1/command/{request_id}/status": ["get"],
  "/api/v1/computer-use/status": ["get"],
  "/api/v1/computer-use/task": ["post"],
  "/api/v1/concurrency/status": ["get"],
  "/api/v1/config": ["get"],
  "/api/v1/config/status": ["get"],
  "/api/v1/config/versions": ["get"],
  "/api/v1/connectors": ["get"],
  "/api/v1/connectors/{service}/authorize": ["get"],
  "/api/v1/connectors/{service}/callback": ["get"],
  "/api/v1/connectors/{service}/credentials": ["post"],
  "/api/v1/connectors/{service}/disconnect": ["post"],
  "/api/v1/contracts/messages": ["get"],
  "/api/v1/contracts/planes": ["get"],
  "/api/v1/contracts/reliability": ["get"],
  "/api/v1/cost/health": ["get"],
  "/api/v1/cost/records": ["get"],
  "/api/v1/cost/summary": ["get"],
  "/api/v1/devices": ["get"],
  "/api/v1/devices/cross-device": ["post"],
  "/api/v1/devices/cross-device-ready": ["get"],
  "/api/v1/devices/discover": ["get"],
  "/api/v1/devices/discover-active": ["post"],
  "/api/v1/devices/health": ["get"],
  "/api/v1/devices/parallel": ["post"],
  "/api/v1/devices/participation": ["get"],
  "/api/v1/devices/readiness": ["get"],
  "/api/v1/devices/register": ["post"],
  "/api/v1/devices/runtime-hosts": ["get"],
  "/api/v1/devices/status": ["post"],
  "/api/v1/devices/transfer": ["post"],
  "/api/v1/devices/{device_id}": ["delete", "get"],
  "/api/v1/devices/{device_id}/command": ["post"],
  "/api/v1/devices/{device_id}/health": ["get"],
  "/api/v1/devices/{device_id}/heartbeat": ["post"],
  "/api/v1/devices/{device_id}/participation": ["get"],
  "/api/v1/devices/{device_id}/readiness": ["get"],
  "/api/v1/devices/{device_id}/runtime-contract": ["get"],
  "/api/v1/devices/{device_id}/runtime-host": ["get"],
  "/api/v1/devices/{device_id}/telemetry": ["get"],
  "/api/v1/devices/{device_id}/unquarantine": ["post"],
  "/api/v1/diagnostics/startup-timing": ["get"],
  "/api/v1/diagnostics/url-sentinel": ["get"],
  "/api/v1/discovery/status": ["get"],
  "/api/v1/errors/summary": ["get"],
  "/api/v1/execution/merge-summary": ["get"],
  "/api/v1/existence/surface": ["get"],
  "/api/v1/federation/forward": ["post"],
  "/api/v1/federation/health": ["get"],
  "/api/v1/federation/heartbeat": ["post"],
  "/api/v1/federation/info": ["get"],
  "/api/v1/federation/peers": ["get", "post"],
  "/api/v1/federation/peers/cleanup": ["get"],
  "/api/v1/federation/peers/{instance_id}": ["delete"],
  "/api/v1/federation/peers/{instance_id}/ping": ["get"],
  "/api/v1/federation/task": ["post"],
  "/api/v1/github/context": ["post"],
  "/api/v1/github/ingest": ["post"],
  "/api/v1/github/install": ["post"],
  "/api/v1/github/list": ["get"],
  "/api/v1/github/status": ["get"],
  "/api/v1/github/uninstall": ["post"],
  "/api/v1/governance/budget/record": ["post"],
  "/api/v1/governance/budget/{session_id}": ["get"],
  "/api/v1/governance/policy": ["get"],
  "/api/v1/governance/queue/stats": ["get"],
  "/api/v1/governance/tools/audit": ["get"],
  "/api/v1/governance/tools/check": ["post"],
  "/api/v1/governance/tools/policy": ["get"],
  "/api/v1/guardian/audit": ["get"],
  "/api/v1/health/quick": ["get"],
  "/api/v1/health/unified": ["get"],
  "/api/v1/hybrid/execute": ["post"],
  "/api/v1/hybrid/registry": ["get"],
  "/api/v1/hybrid/stats": ["get"],
  "/api/v1/memory/cold": ["get"],
  "/api/v1/memory/drift/check": ["post"],
  "/api/v1/memory/drift/config": ["get", "put"],
  "/api/v1/memory/query": ["get"],
  "/api/v1/memory/stats": ["get"],
  "/api/v1/memory/store": ["post"],
  "/api/v1/memory/tasks": ["get"],
  "/api/v1/memory/unified/status": ["get"],
  "/api/v1/mesh/android-lifecycle": ["get"],
  "/api/v1/mesh/coordinator-summary": ["get"],
  "/api/v1/mesh/memberships": ["get"],
  "/api/v1/mesh/participation-summary": ["get"],
  "/api/v1/mesh/peer_announce": ["post"],
  "/api/v1/mesh/peer_exchange": ["post"],
  "/api/v1/mesh/peers": ["get"],
  "/api/v1/mesh/probe": ["post"],
  "/api/v1/mesh/send": ["post"],
  "/api/v1/mesh/session": ["get"],
  "/api/v1/mesh/stats": ["get"],
  "/api/v1/mesh/topology": ["get"],
  "/api/v1/mesh/worker": ["get"],
  "/api/v1/mesh/worker/toggle": ["post"],
  "/api/v1/modality/devices": ["get"],
  "/api/v1/modality/matrix": ["get"],
  "/api/v1/modality/plan": ["get"],
  "/api/v1/modality/providers": ["get"],
  "/api/v1/models/catalog": ["get"],
  "/api/v1/models/latency-probe": ["post"],
  "/api/v1/models/routing-stats": ["get"],
  "/api/v1/models/slot": ["post"],
  "/api/v1/models/status": ["get"],
  "/api/v1/models/sync": ["post"],
  "/api/v1/models/tier": ["post"],
  "/api/v1/models/verify-provider": ["post"],
  "/api/v1/monitoring/alerts": ["get"],
  "/api/v1/monitoring/dashboard": ["get"],
  "/api/v1/monitoring/health": ["get"],
  "/api/v1/monitoring/metrics": ["get"],
  "/api/v1/monitoring/performance": ["get"],
  "/api/v1/nodes": ["get"],
  "/api/v1/nodes/call": ["post"],
  "/api/v1/nodes/legacy/filesystem": ["get"],
  "/api/v1/nodes/roster": ["get"],
  "/api/v1/nodes/status": ["get"],
  "/api/v1/nodes/{node_name}": ["get"],
  "/api/v1/nodes/{node}/start": ["post"],
  "/api/v1/nodes/{node}/stop": ["post"],
  "/api/v1/observability/bus-events": ["get"],
  "/api/v1/observability/context-layer": ["get"],
  "/api/v1/observability/execution-legibility": ["get"],
  "/api/v1/observability/execution/evidence-state": ["get"],
  "/api/v1/observability/execution/evidence-state/{task_id}": ["get"],
  "/api/v1/observability/execution/recent-events": ["get"],
  "/api/v1/observability/execution/schema": ["get"],
  "/api/v1/observability/execution/trace/{trace_id}": ["get"],
  "/api/v1/observability/gateway": ["get"],
  "/api/v1/observability/model-route": ["get"],
  "/api/v1/observability/nats": ["get"],
  "/api/v1/observability/orchestration-review": ["get"],
  "/api/v1/observability/recent-calls": ["get"],
  "/api/v1/observability/stats": ["get"],
  "/api/v1/observability/trace/{trace_id}": ["get"],
  "/api/v1/opencode/configure": ["post"],
  "/api/v1/opencode/generate": ["post"],
  "/api/v1/opencode/status": ["get"],
  "/api/v1/operator/action": ["post"],
  "/api/v1/operator/actions/android-directed": ["post"],
  "/api/v1/operator/actions/android-directed/{dispatch_id}/ack": ["post"],
  "/api/v1/operator/actions/audit": ["get"],
  "/api/v1/operator/actions/availability": ["get"],
  "/api/v1/operator/board/operable-truth": ["get"],
  "/api/v1/operator/devices/dispatch-readiness": ["get"],
  "/api/v1/operator/devices/ecosystem": ["get"],
  "/api/v1/operator/devices/ecosystem/{device_id}": ["get"],
  "/api/v1/operator/devices/execution-events": ["get"],
  "/api/v1/operator/devices/{device_id}/dispatch-readiness": ["get"],
  "/api/v1/operator/dispatch": ["post"],
  "/api/v1/operator/flows": ["get"],
  "/api/v1/operator/flows/{flow_id}": ["get"],
  "/api/v1/operator/flows/{flow_id}/cancel": ["post"],
  "/api/v1/operator/heartbeat": ["get"],
  "/api/v1/operator/inspect/audit-evidence/{task_id}": ["get"],
  "/api/v1/operator/inspect/executor/{node_id}": ["get"],
  "/api/v1/operator/inspect/failure/{task_id}": ["get"],
  "/api/v1/operator/inspect/flow/{flow_id}": ["get"],
  "/api/v1/operator/inspect/lineage/{task_id}": ["get"],
  "/api/v1/operator/inspect/partial-result/{task_id}": ["get"],
  "/api/v1/operator/inspect/recovery/{task_id}": ["get"],
  "/api/v1/operator/inspect/route/{task_id}": ["get"],
  "/api/v1/operator/inspect/task/{task_id}": ["get"],
  "/api/v1/operator/llm": ["get"],
  "/api/v1/operator/nats": ["get"],
  "/api/v1/operator/pr4/snapshot": ["get"],
  "/api/v1/operator/presence/ambient": ["get"],
  "/api/v1/operator/presence/ambient/halt": ["post"],
  "/api/v1/operator/review/{task_id}": ["get"],
  "/api/v1/operator/snapshot": ["get"],
  "/api/v1/pair/card": ["get"],
  "/api/v1/pair/check": ["post"],
  "/api/v1/pair/claim": ["post"],
  "/api/v1/pair/paths": ["get"],
  "/api/v1/pair/peers": ["get"],
  "/api/v1/pair/peers/{device_id}": ["delete", "get"],
  "/api/v1/pair/trust": ["post"],
  "/api/v1/panel/feed": ["get"],
  "/api/v1/panel/unified": ["get"],
  "/api/v1/ports": ["get"],
  "/api/v1/projection/agent-dispatch": ["get"],
  "/api/v1/projection/canonical-routing": ["get"],
  "/api/v1/projection/clone-to-use-acceptance": ["get"],
  "/api/v1/projection/cross_device_routing": ["get"],
  "/api/v1/projection/desktop-status-board": ["get"],
  "/api/v1/projection/device-formation": ["get"],
  "/api/v1/projection/dual-repo-integrated-system-contract": ["get"],
  "/api/v1/projection/execution_policy": ["get"],
  "/api/v1/projection/governance": ["get"],
  "/api/v1/projection/operability-contract": ["get"],
  "/api/v1/projection/operational-readiness": ["get"],
  "/api/v1/projection/policy-alignment": ["get"],
  "/api/v1/projection/return": ["get"],
  "/api/v1/projection/routing-explanation": ["get"],
  "/api/v1/projection/runtime": ["get"],
  "/api/v1/projection/runtime-governance": ["get"],
  "/api/v1/projection/runtime-truth": ["get"],
  "/api/v1/projection/runtime/multi-device": ["get"],
  "/api/v1/projection/runtime/recovery": ["get"],
  "/api/v1/projection/runtime/session-snapshot": ["get"],
  "/api/v1/projection/server-canonicalization-status": ["get"],
  "/api/v1/projection/task_semantics": ["get"],
  "/api/v1/protocols/load-status": ["get"],
  "/api/v1/protocols/mcp": ["get"],
  "/api/v1/protocols/mcp/load": ["post"],
  "/api/v1/protocols/mcp/{name}": ["delete"],
  "/api/v1/protocols/mcp/{name}/call": ["post"],
  "/api/v1/protocols/mcp/{name}/reload": ["post"],
  "/api/v1/protocols/mcp/{name}/tools": ["get"],
  "/api/v1/protocols/reload-all": ["post"],
  "/api/v1/protocols/skills": ["get"],
  "/api/v1/protocols/skills/load": ["post"],
  "/api/v1/protocols/skills/{name}": ["delete"],
  "/api/v1/protocols/skills/{name}/execute": ["post"],
  "/api/v1/protocols/skills/{name}/reload": ["post"],
  "/api/v1/protocols/status": ["get"],
  "/api/v1/rag/patterns": ["get"],
  "/api/v1/rag/query": ["post"],
  "/api/v1/rag/stats": ["get"],
  "/api/v1/readiness": ["get"],
  "/api/v1/relay/broadcast": ["post"],
  "/api/v1/relay/history": ["get"],
  "/api/v1/relay/send": ["post"],
  "/api/v1/relay/stats": ["get"],
  "/api/v1/resilience/circuit-breakers": ["get"],
  "/api/v1/resilience/circuit-breakers/{target}/reset": ["post"],
  "/api/v1/resilience/metrics": ["get"],
  "/api/v1/resilience/metrics/prom": ["get"],
  "/api/v1/runtime/domain": ["get"],
  "/api/v1/runtime/result-merge-summary": ["get"],
  "/api/v1/runtime/scope-authority": ["get"],
  "/api/v1/runtime/source-dispatch-summary": ["get"],
  "/api/v1/runtime/takeover": ["post"],
  "/api/v1/security/audit": ["get"],
  "/api/v1/security/connection-provenance": ["get"],
  "/api/v1/security/context-provenance": ["get"],
  "/api/v1/security/egress": ["get"],
  "/api/v1/security/execution-isolation": ["get"],
  "/api/v1/security/policy": ["get", "put"],
  "/api/v1/security/policy/evaluate": ["post"],
  "/api/v1/security/stats": ["get"],
  "/api/v1/security/weights-admission": ["get"],
  "/api/v1/sessions": ["get", "post"],
  "/api/v1/sessions/ingest_turns": ["post"],
  "/api/v1/sessions/migrate": ["post"],
  "/api/v1/sessions/reconcile": ["post"],
  "/api/v1/sessions/{session_id}": ["get"],
  "/api/v1/sessions/{session_id}/history": ["get"],
  "/api/v1/sessions/{session_id}/join": ["post"],
  "/api/v1/sessions/{session_id}/sync": ["post"],
  "/api/v1/slo/metrics": ["get"],
  "/api/v1/slo/operational": ["get"],
  "/api/v1/strategy/mappings": ["get"],
  "/api/v1/stream": ["get"],
  "/api/v1/system/completion-status": ["get"],
  "/api/v1/system/config": ["get"],
  "/api/v1/system/dual-repo-progress": ["get"],
  "/api/v1/system/health": ["get"],
  "/api/v1/system/mcp": ["get"],
  "/api/v1/system/mode-status": ["get"],
  "/api/v1/system/skills": ["get"],
  "/api/v1/system/status": ["get"],
  "/api/v1/system/subsystems": ["get"],
  "/api/v1/tasks": ["get", "post"],
  "/api/v1/tasks/groups/{group_id}/cancel": ["delete", "post"],
  "/api/v1/tasks/{task_id}": ["get"],
  "/api/v1/tasks/{task_id}/cancel": ["delete", "post"],
  "/api/v1/tasks/{task_id}/result": ["post"],
  "/api/v1/twin/create": ["post"],
  "/api/v1/twin/scenario": ["post"],
  "/api/v1/twin/status": ["get"],
  "/api/v1/twin/{twin_id}": ["delete", "get"],
  "/api/v1/twin/{twin_id}/couple": ["post"],
  "/api/v1/twin/{twin_id}/decouple": ["post"],
  "/api/v1/twin/{twin_id}/drift": ["get"],
  "/api/v1/twin/{twin_id}/predict": ["get"],
  "/api/v1/twin/{twin_id}/simulate": ["post"],
  "/api/v1/twin/{twin_id}/switch-mode": ["post"],
  "/api/v1/ui/act": ["post"],
  "/api/v1/ui/perception": ["get"],
  "/api/v1/vault/audit": ["get"],
  "/api/v1/vault/cleanup": ["post"],
  "/api/v1/vault/credentials": ["get", "post"],
  "/api/v1/vault/credentials/{key_name}": ["delete"],
  "/api/v1/vault/fetch": ["post"],
  "/api/v1/vault/health": ["get"],
  "/api/v1/vault/tokens": ["post"],
  "/api/v1/vault/tokens/validate": ["post"],
  "/api/v1/vault/tokens/{token}/info": ["get"],
  "/api/v1/vision/observe": ["post"],
  "/api/v1/vision/ocr": ["post"],
  "/api/v1/vision/understand": ["post"],
  "/api/v1/webrtc/endpoint": ["get"],
  "/api/v5/autonomous_programming": ["post"],
  "/api/v5/debug_code": ["post"],
  "/api/v5/generate_code": ["post"],
  "/api/v5/health": ["get"],
  "/api/v5/learn_from_experience": ["post"],
  "/api/v5/optimize_code": ["post"],
  "/api/v5/reason": ["post"],
  "/api/v5/stats": ["get"],
  "/auth/oauth/callback": ["get"],
  "/auth/oauth/device/poll": ["post"],
  "/auth/oauth/device/start": ["post"],
  "/auth/oauth/github": ["post"],
  "/auth/oauth/google": ["post"],
  "/auth/oauth/health": ["get"],
  "/auth/oauth/logout": ["post"],
  "/auth/oauth/me": ["get"],
  "/auth/oauth/providers": ["get"],
  "/auth/oauth/refresh": ["post"],
  "/auth/oauth/{provider}/authorize": ["get"],
  "/health/metrics": ["get"],
  "/health/nats": ["get"],
  "/metrics": ["get"],
  "/sync/status": ["get"],
  "/v1/audio/capabilities": ["get"],
  "/v1/audio/speech": ["post"],
  "/v1/audio/transcriptions": ["post"],
} as const satisfies Record<ApiPath, readonly string[]>;

export type ApiMethod<P extends ApiPath> = (typeof API_METHODS)[P][number];

// ── 组件 schema ──

export interface AIIntentRequest {
  "context"?: Record<string, unknown>;
  "session_id"?: string;
  "text": string;
}

export interface AgentCreateRequest {
  "agent_type"?: string;
  "context"?: Record<string, unknown>;
  "device_id"?: string;
  "device_type"?: string;
  "task_description"?: string;
  "template_name"?: string;
}

export interface AgentDeployRequest {
  "execution_mode"?: string;
  "instruction": string;
  "priority"?: string;
  "target_device": string;
  "timeout_seconds"?: number;
  "tools"?: Array<Record<string, unknown>>;
}

export interface AgentSplitRequest {
  "subtasks": Array<string>;
}

export interface ApprovalActionRequest {
  "action"?: string;
  "grant"?: string;
  "operator"?: string;
  "reason"?: string;
  "token"?: string | null;
}

export interface AutonomousProgrammingRequest {
  "auto_debug"?: boolean;
  "auto_optimize"?: boolean;
  "language"?: string;
  "task": string;
}

export interface AutonomousRequest {
  "context"?: Record<string, unknown>;
  "instruction": string;
  "model_alias"?: string | null;
}

export interface Body_create_transcription_v1_audio_transcriptions_post {
  "file": string;
  "language"?: string;
  "model"?: string;
  "response_format"?: string;
}

export interface BudgetRecordRequest {
  "cost_usd": number;
  "model": string;
  "session_id": string;
  "tenant_id"?: string;
  "tokens_used": number;
}

export interface ChatRequest {
  "context"?: Array<Record<string, string>>;
  "device_id"?: string;
  "entry_mode"?: string | null;
  "message": string;
  "multimodal_context"?: MultiModalContext | null;
  "required_capabilities"?: Array<string> | null;
  "session_id"?: string;
  "source_runtime_posture"?: string | null;
  "target_device"?: string | null;
  "user_id"?: string;
}

export interface CheckRequest {
  "device_id": string;
  "intent"?: string;
}

export interface ClaimRequest {
  "auto_accept"?: Array<string> | null;
  "capabilities"?: Array<string> | null;
  "code"?: string | null;
  "device_id": string;
  "device_type"?: string;
  "link"?: string | null;
  "name"?: string;
  "note"?: string;
  "token_ttl_s"?: number;
  "trust"?: string;
}

export interface CodeExecuteRequest {
  "code": string;
  "language"?: string;
  "stdin"?: string;
  "timeout"?: number;
}

export interface ComputerUseTaskRequest {
  "dry_run"?: boolean;
  "instruction": string;
  "max_steps"?: number | null;
  "node_id"?: string;
}

export interface ConfigUpdateRequest {
  "config": Record<string, string>;
}

export interface ConfigureRequest {
  "model": string;
  "provider": string;
  "temperature"?: number;
}

export interface ConversationRequest {
  "content": string;
  "metadata"?: Record<string, unknown>;
  "role"?: string;
  "session_id": string;
}

export interface CreateSessionRequest {
  "device_id"?: string;
  "user_id": string;
}

export interface CrossDeviceRequest {
  "command": string;
  "context"?: Record<string, unknown>;
}

export interface DebateRequest {
  "question": string;
  "rounds"?: number;
  "strategies"?: Array<string>;
}

export interface DebugCodeRequest {
  "code": string;
  "error"?: string | null;
  "language"?: string;
}

export interface DesktopAnalyze {
  "image_base64"?: string;
  "mime"?: string;
  "prompt"?: string;
  "session_id"?: string;
  "source"?: string;
}

export interface DesktopAudio {
  "audio_base64": string;
  "mime"?: string;
}

export interface DesktopFrame {
  "image_base64": string;
  "mime"?: string;
  "screen"?: Record<string, unknown> | null;
  "source"?: string;
}

export interface DesktopListen {
  "audio_base64"?: string;
  "mime"?: string;
  "prompt"?: string;
}

export interface DeviceCommandRequest {
  "command": string;
  "params"?: Record<string, unknown>;
  "timeout"?: number;
}

export interface DeviceHealthResponse {
  "circuit_state": string;
  "consecutive_failures": number;
  "device_id": string;
  "health_score": number;
  "heartbeat_latency_ms": number;
  "last_failure_time"?: number | null;
  "last_success_time"?: number | null;
  "quarantine_reason": string;
  "quarantined": boolean;
  "recent_error_rate": number;
}

export interface DevicePollRequest {
  "device_code": string;
  "provider": string;
}

export interface DeviceRegisterRequest {
  "app_version"?: string;
  "capabilities"?: Array<string>;
  "device_id": string;
  "device_name"?: string;
  "device_type"?: string;
  "os_version"?: string;
}

export interface DeviceRelayRequest {
  "chain"?: Array<string>;
  "expect_reply"?: boolean;
  "payload"?: Record<string, unknown>;
  "payload_type"?: string;
  "source_device": string;
  "target_device": string;
  "timeout_seconds"?: number;
}

export interface DeviceStartRequest {
  "provider"?: string;
}

export interface DeviceStatusUpdate {
  "device_id": string;
  "status"?: Record<string, unknown>;
}

export interface ExecuteCommandRequest {
  "command": string;
  "env"?: Record<string, string> | null;
  "timeout"?: number;
  "working_dir"?: string | null;
}

export interface ExecuteResponse {
  "command": string;
  "execution_time_ms": number;
  "exit_code": number;
  "fallback"?: boolean;
  "server_id": string;
  "stderr": string;
  "stdout": string;
  "success": boolean;
  "timestamp": string;
}

export interface FileTransferRequest {
  "file_path": string;
  "source_device": string;
  "target_device": string;
  "target_path"?: string;
}

export interface GitHubCodeRequest {
  "code": string;
  "redirect_uri"?: string | null;
}

export interface GitHubContextRequest {
  "ref"?: string | null;
  "url": string;
}

export interface GitHubIngestRequest {
  "include_code"?: boolean;
  "ref"?: string | null;
  "url": string;
}

export interface GitHubInstallRequest {
  "dry_run"?: boolean;
  "ref"?: string | null;
  "type"?: string | null;
  "url": string;
}

export interface GitHubUninstallRequest {
  "name": string;
}

export interface GoogleIdTokenRequest {
  "id_token": string;
}

export interface HTTPValidationError {
  "detail"?: Array<ValidationError>;
}

export interface HybridExecuteRequest {
  "action"?: string;
  "app_id"?: string;
  "device_id": string;
  "force_level"?: string | null;
  "instruction"?: string;
  "params"?: Record<string, unknown>;
}

export interface IngestTurnModel {
  "content": string;
  "metadata"?: Record<string, unknown> | null;
  "role": string;
  "ts"?: number;
}

export interface IngestTurnsRequest {
  "device_id"?: string;
  "session_id": string;
  "turns"?: Array<IngestTurnModel>;
  "user_id"?: string;
}

export interface JoinSessionRequest {
  "device_id": string;
}

export interface LearnFromExperienceRequest {
  "actions": Array<Record<string, unknown>>;
  "command": string;
  "context": Record<string, unknown>;
  "result": Record<string, unknown>;
  "success": boolean;
}

export interface MCPLoadRequest {
  "args"?: Array<string>;
  "auto_start"?: boolean;
  "command": string;
  "cwd"?: string;
  "env"?: Record<string, string>;
  "name": string;
}

export interface MCPToolCallRequest {
  "arguments"?: Record<string, unknown>;
  "tool_name": string;
}

export interface MeshSendRequest {
  "payload"?: Record<string, unknown>;
  "payload_type"?: string;
  "source_device"?: string;
  "target_device": string;
}

export interface MeshWorkerToggleRequest {
  "enable": boolean;
}

export interface ModelSyncRequest {
  "apply"?: boolean;
  "max_add"?: number;
  "only"?: Array<string> | null;
}

export interface MultiModalAudio {
  "data": string;
  "mime": string;
  "source"?: string | null;
  "timestamp"?: string | null;
}

export interface MultiModalContext {
  "audio"?: Array<MultiModalAudio>;
  "images"?: Array<MultiModalImage>;
  "metadata"?: Record<string, unknown>;
  "screen"?: Record<string, unknown> | null;
  "sensor"?: Record<string, unknown> | null;
}

export interface MultiModalImage {
  "data": string;
  "mime": string;
  "source"?: string | null;
  "timestamp"?: string | null;
}

export interface NodeCallRequest {
  "action": string;
  "node_id": string;
  "params"?: Record<string, unknown>;
}

export interface OAuthLogoutRequest {
  "refresh_token": string;
}

export interface OAuthRefreshRequest {
  "refresh_token": string;
}

export interface OCRRequest {
  "image_base64": string;
  "language"?: string;
  "mode"?: string;
}

export interface ObserveRequest {
  "device_id": string;
  "duration"?: number;
  "fps"?: number;
  "mode"?: string | null;
  "prompt"?: string | null;
}

export interface OptimizeCodeRequest {
  "code": string;
  "language"?: string;
  "target"?: string;
}

export interface ParallelCommandItem {
  "command": string;
  "device_id": string;
  "params"?: Record<string, unknown>;
}

export interface ParallelCommandRequest {
  "commands": Array<ParallelCommandItem>;
  "context"?: Record<string, unknown>;
  "timeout"?: number;
}

export interface PeerAnnounceRequest {
  "device_id": string;
  "local_ip"?: string;
  "local_port"?: number;
  "metadata"?: Record<string, unknown>;
  "public_ip"?: string;
  "public_port"?: number;
}

export interface ProbeRequest {
  "keys": Array<string>;
}

export interface ProviderVerifyRequest {
  "env_key"?: string | null;
  "provider"?: string | null;
}

export interface RAGQueryRequest {
  "device_id"?: string;
  "include_experience"?: boolean;
  "include_knowledge"?: boolean;
  "query": string;
  "top_k"?: number;
}

export interface ReadFileRequest {
  "max_size"?: number;
  "path": string;
}

export interface ReasonRequest {
  "facts": Array<string>;
  "question": string;
}

export interface ReconcileSessionRequest {
  "canonical_session_id"?: string;
  "device_id"?: string;
  "local_session_id": string;
  "merge_history"?: boolean;
  "user_id"?: string;
}

export interface RegisterServerRequest {
  "description"?: string | null;
  "host": string;
  "key_path"?: string | null;
  "name": string;
  "password"?: string | null;
  "port"?: number;
  "tags"?: Array<string>;
  "user": string;
}

export interface SandboxExecuteRequest {
  "code": string;
  "cpu_limit_seconds"?: number | null;
  "language"?: string;
  "memory_limit_mb"?: number;
  "stdin"?: string | null;
  "timeout"?: number;
}

export interface SandboxExecuteResponse {
  "blocked_reason": string | null;
  "execution_time_ms": number;
  "exit_code": number;
  "language": string;
  "safe": boolean;
  "stderr": string;
  "stdout": string;
  "success": boolean;
  "timestamp": string;
}

export interface SandboxValidateRequest {
  "command": string;
  "context"?: string | null;
}

export interface SandboxValidateResponse {
  "blocked": boolean;
  "blocked_reason": string | null;
  "recommended_action": string;
  "risk_level": string;
  "safe": boolean;
  "warnings": Array<string>;
}

export interface ServerInfo {
  "auth_type": string;
  "description": string | null;
  "host": string;
  "last_used": string | null;
  "name": string;
  "port": number;
  "registered_at": string;
  "server_id": string;
  "status": string;
  "system_info"?: Record<string, unknown> | null;
  "tags": Array<string>;
  "user": string;
}

export interface SkillExecuteRequest {
  "context"?: Record<string, unknown>;
  "input"?: Record<string, unknown>;
}

export interface SkillLoadRequest {
  "config"?: Record<string, unknown>;
  "name"?: string;
  "path"?: string;
}

export interface SlotSelectRequest {
  "model": string;
  "role": string;
}

export interface SpeechRequest {
  "input": string;
  "model"?: string;
  "response_format"?: string;
  "speed"?: number;
  "voice"?: string;
}

export interface SwarmCreateRequest {
  "agent_count"?: number;
  "task": string;
  "template"?: string;
}

export interface SyncSessionRequest {
  "device_id": string;
  "max_turns"?: number;
}

export interface TaskRequest {
  "control_session_id"?: string;
  "conversation_session_id"?: string;
  "device_id"?: string;
  "payload"?: Record<string, unknown>;
  "priority"?: number;
  "runtime_attachment_session_id"?: string;
  "session_id"?: string;
  "task_type": string;
}

export interface TaskResultPayload {
  "details"?: string | null;
  "result"?: unknown | null;
  "status"?: string | null;
  "trace_id"?: string | null;
}

export interface TierSelectRequest {
  "main_brain"?: string | null;
  "tier": string;
}

export interface ToolCheckRequest {
  "risk_tier"?: string;
  "tool_name": string;
}

export interface TrustRequest {
  "auto_accept"?: Array<string> | null;
  "device_id": string;
  "note"?: string | null;
  "trust"?: string | null;
}

export interface TwinScenarioRequest {
  "actions": Array<unknown>;
}

export interface TwinSimulateRequest {
  "action": string;
  "params"?: Record<string, unknown>;
}

export interface TwinSwitchModeRequest {
  "mode": string;
}

export interface UIActRequest {
  "device_id"?: string;
  "execute"?: boolean;
  "instruction"?: string;
  "model_reply"?: string | null;
  "node_id"?: string;
  "platform"?: string;
  "screenshot_b64"?: string | null;
  "ui_graph"?: Record<string, unknown> | null;
}

export interface UnifiedCommandRequest {
  "command": string;
  "mode"?: string;
  "params"?: Record<string, unknown>;
  "request_id"?: string | null;
  "targets": Array<string>;
  "timeout"?: number;
}

export interface UnquarantineResponse {
  "device_id": string;
  "message": string;
  "was_quarantined": boolean;
}

export interface ValidationError {
  "ctx"?: Record<string, unknown>;
  "input"?: unknown;
  "loc": Array<string | number>;
  "msg": string;
  "type": string;
}

export interface VisionRequest {
  "image_base64"?: string | null;
  "instruction"?: string;
  "is_last_chunk"?: boolean;
  "mode"?: string;
  "session_id"?: string | null;
  "video_chunk"?: string | null;
}

export interface WriteFileRequest {
  "content": string;
  "mode"?: string;
  "path": string;
  "user"?: string | null;
}

export interface _LegacyHeartbeatRequest {
  "device_id": string;
  "status"?: Record<string, unknown>;
}

export interface _LegacyRegisterRequest {
  "app_version"?: string;
  "capabilities"?: Array<unknown>;
  "device_id": string;
  "device_name"?: string;
  "device_type"?: string;
  "os_version"?: string;
}

export interface _LegacyUnregisterRequest {
  "device_id": string;
}

export interface core__routes__ai__create_router___locals___TwinCreateRequest {
  "member_count"?: number;
  "providers"?: Array<string>;
  "strategy"?: string;
  "task": string;
}

export interface core__routes__opencode__GenerateCodeRequest {
  "context"?: Record<string, unknown> | null;
  "language"?: string | null;
  "model"?: string | null;
  "prompt": string;
  "provider"?: string | null;
}

export interface core__routes__twin__TwinCreateRequest {
  "device_id": string;
  "device_type"?: string;
  "drift_threshold"?: number;
  "initial_state"?: Record<string, unknown> | null;
}

export interface galaxy_gateway__gateway_service__GenerateCodeRequest {
  "context"?: string | null;
  "language"?: string;
  "requirement": string;
}

