// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.
// 源:core/phase_contract.py(面板侧相位契约 SSOT)。改后端字段后重跑该脚本。

/**
 * 后端【线上】传输的三态 token。
 *
 * 刻意不叫 `Phase`：面板自己的 `types/phase.ts` 里已有一个 `Phase`,
 * 取值是 'silent' | 'liminal' | 'manifest'（展示词汇），而后端发的是
 * 'static'（见 core/desktop_presence_system.py 的 STATIC）。两者同名不同义，
 * 一起 import 会撞。转换由 usePhase.ts 的 _mapPhaseToken 负责。
 *
 * 连续量只描述它在这一档里的位置，不改变是哪一档。
 */
export type WirePhase = "static" | "liminal" | "manifest";

/** depth 是实算的还是锚点兜底。前端可据此区分精确态/估计态。 */
export type PhasePostureSource = "continuum" | "anchor_only";

/** 三态在渲染深度轴上的锚点。前端过渡编排按这几个数调。 */
export const PHASE_ANCHORS: Record<WirePhase, number> = {
  "static": 0.05,
  "liminal": 0.62,
  "manifest": 0.92,
};

/** 边缘混合上限:倾向为 1 时深度最多向邻档漂移两档间距的这个比例。 */
export const PHASE_EDGE_BLEND = 0.45;

export interface PhasePosture {
  /** 后端线上传输的三态 token（static/liminal/manifest），仍然是权威 */
  phase: WirePhase;
  /** 渲染深度 [0,1]，在相位带内漂移 */
  depth: number;
  /** EMA 平滑的在场强度 [0,1] */
  presence_intensity: number;
  /** 信号成意图的程度 [0,1] */
  coherence: number;
  /** 推向下一档的概率质量 [0,1] */
  collapse_tendency: number;
  /** 推向上一档回撤的概率质量 [0,1] */
  retreat_tendency: number;
  /** 时间稳定度 [0,1]，低值表示刚发生过振荡 */
  stability: number;
  /** 深度来自实算还是锚点兜底 */
  source: PhasePostureSource;
}
