// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.
// 源:core/phase_contract.py(面板侧相位契约 SSOT)。改后端字段后重跑该脚本。

/**
 * 后端【线上】传输的三态 token。
 *
 * 刻意不叫 `Phase`：面板自己的 `types/phase.ts` 里已有一个 `Phase`,
 * 取值是 'silent' | 'liminal' | 'manifest'（展示词汇），而后端发的是
 * 'static'（见 core/desktop_presence_system.py 的 STATIC）。两者同名不同义，
 * 一起 import 会撞。转换由 usePhase.ts 的 _mapPhaseToken 负责。
 *
 * 连续量只描述它在这一档里的位置，不改变是哪一档。
 */
export type WirePhase = "static" | "liminal" | "manifest";

/** depth 是实算的还是锚点兜底。前端可据此区分精确态/估计态。 */
export type PhasePostureSource = "continuum" | "anchor_only";

/** 三态在渲染深度轴上的锚点。前端过渡编排按这几个数调。 */
export const PHASE_ANCHORS: Record<WirePhase, number> = {
  "static": 0.05,
  "liminal": 0.62,
  "manifest": 0.92,
};

/** 边缘混合上限:倾向为 1 时深度最多向邻档漂移两档间距的这个比例。 */
export const PHASE_EDGE_BLEND = 0.45;

export interface PhasePosture {
  /** 后端线上传输的三态 token（static/liminal/manifest），仍然是权威 */
  phase: WirePhase;
  /** 渲染深度 [0,1]，在相位带内漂移 */
  depth: number;
  /** EMA 平滑的在场强度 [0,1] */
  presence_intensity: number;
  /** 信号成意图的程度 [0,1] */
  coherence: number;
  /** 推向下一档的概率质量 [0,1] */
  collapse_tendency: number;
  /** 推向 receding 的概率质量 [0,1]。注意：在本【遗留】投影里它被当作「向上一档锚点漂移」，那是语义误读，见 RenderPosture 的同名字段 */
  retreat_tendency: number;
  /** 时间稳定度 [0,1]，低值表示刚发生过振荡 */
  stability: number;
  /** 深度来自实算还是锚点兜底 */
  source: PhasePostureSource;
}


// ═══════════════════════════════════════════════════════════════════
// 忠实契约：按 core/continuum 的实际形状生成
//
// 上面的 PhasePosture 是一维遗留投影（三锚点串在一条 depth 轴上），保留
// 只为兼容既有覆盖层 presence_motion.js。**新代码应当消费 RenderPosture。**
//
// 差别是结构性的，不是字段多少：
//   · 四相 vs 三态 —— receding（返回弧）在遗留投影里被折叠成 silent，
//     于是「刚做完正在退场」与「静息」在渲染端不可分辨；
//   · 二维 vs 一维 —— runtime_domain（在哪儿跑）遗留投影里完全没有；
//   · retreat_tendency 的语义 —— 后端原文是「推向 receding」，遗留投影
//     把它当成「退回上一档」，那会表达出转移表明令禁止的 manifest→liminal。
// ═══════════════════════════════════════════════════════════════════

/**
 * 【主轴】主体生命周期（后端 TriState）——渲染端的整体编排跟这一根走。
 *
 * 它就是用户能直接感知的节奏：休息 / 过渡 / 对外表达。在场桥广播的
 * `payload.phase` 一直是这一根。
 */
export type Lifecycle = "silent" | "liminal" | "manifest";

/**
 * 【副轴】内部连续体四相 —— 提供主轴给不出的纹理，不决定整体编排。
 *
 * 比主轴多一相 `receding`（返回弧）。主轴回到 `silent` 时，靠副轴才能
 * 区分「刚做完正在消散」(receding) 与「静息」(formless)。
 */
export type RenderPhase = "formless" | "liminal" | "manifest" | "receding";

/** 阈限态里正在发生什么。主轴说「在过渡」，这一项说「过渡里在干嘛」。 */
export type LiminalActivity = "none" | "understanding" | "thinking" | "rehearsing";

/** 沙盘推演的种类。 */
export type SimulationKind = "none" | "speculative" | "sandbox";

/**
 * 阈限态沙盘推演摘要 —— **阈限态的可视内容**。
 *
 * 阈限态在面板上一直「什么都没有」，根因不是动画简陋，是这一层从没送出来过：
 * 智能体在真正落手之前会先在影子沙盘里推演若干条候选路径（见后端
 * core/liminal_rehearsal.py），`candidate_paths` 就是它正在权衡的那几条，
 * `committed_path` 是最终提交的那条。
 */
export interface SimulationSummary {
  /** 当前是否有推演在跑 */
  is_active: boolean;
  /** none / speculative / sandbox */
  simulation_kind: SimulationKind;
  /** 正在评估的候选执行路径 —— 阈限态在权衡什么 */
  candidate_paths: string[];
  /** 已提交的那条；仍在推演/全失败时 null */
  committed_path: string | null;
  /** committed_path !== null */
  is_committed: boolean;
  /** 已完成的推演步数 */
  step_count: number;
  /** 场景的人类可读标签 */
  scenario_label: string | null;
}

/** 三态公共投影。仅供必须使用公共词汇的消费者；用它画图会丢掉返回弧。 */
export type WirePhaseTri = "liminal" | "manifest" | "silent";

/** 第二维：执行发生在哪儿。 */
export type RuntimeDomain = "local" | "cross_device" | "transition";

/** 形态提示（后端 ExpressionEngine 算出，非前端推导）。 */
export type FormSignature = "none" | "diffuse_cluster" | "focused_point" | "expanding_ring" | "collapsing_field";

/** 抽象空间权重／贴近度。 */
export type SpatialPresence = "absent" | "peripheral" | "ambient" | "foreground";

/** 执行链的种类。决定 ExecutionChainView.last_target 指的是任务还是设备。 */
export type ChainKind = "local" | "cross_device";

/** 表达期用什么手法动手。none = 尚未决策。 */
export type HybridExecutionMode = "none" | "sequential_degrade" | "parallel_race" | "staged_hybrid" | "local_preferred" | "remote_preferred";

/** 「这一维接没接上」。unwired = 这条链路还没建，不是「零个」。 */
export type ViewSource = "unwired" | "live";

/** 世界模型视图的来源。与 ViewSource 同一份取值域（后端是别名，不是副本）。 */
export type WorldModelSource = ViewSource;

/** 感知模态。四条恒定存在，缺席的那条以 unavailable 出现而不是从数组里消失。 */
export type PerceptionModality = "screen" | "camera" | "microphone" | "system_audio";

/**
 * 单个模态的状态。**刻意不是布尔** —— 布尔会把三件不同的事压成一件，
 * 而那正是深度轴犯过的错（20 个字段压成一个标量，退场只能把进场倒放）。
 *
 *   unavailable  这条通路从没来过东西（没硬件／没授权／前端没在推）→ 这一侧不亮
 *   paused       用户按了隐私暂停 → 明确地「闭着」，不是「没有」
 *   suppressed   在，但这一拍被刻意屏蔽 → 短暂闭合，不是熄灭
 *   idle         通路通、有过信号，但这一拍静了 → 柔和呼吸
 *   live         这一拍有新鲜信号 → 有反应
 *
 * `suppressed` 是反自激励：AI 朗读时麦克风采到的是它自己的声音，自发注意力
 * 循环刻意忽略那段音频。这一档把「说话时不能显示在听」从**渲染端要记的规矩**
 * 变成**后端给的状态** —— 规矩会被忘记，状态不会。
 */
export type ModalityState = "unavailable" | "paused" | "suppressed" | "idle" | "live";

/** 自发注意力上一拍的决策。none = 还没决策过。 */
export type AmbientAction = "none" | "speak" | "silent" | "delegate";

/** 一个感知模态的当前状态。第一态「哪侧亮、亮多少、是闭着还是没有」全靠这一层。 */
export interface ModalityView {
  /** screen / camera / microphone / system_audio */
  modality: PerceptionModality;
  /** 五档之一 —— 刻意不是布尔，理由见该类型的注释 */
  state: ModalityState;
  /** 距上次有信号多久（秒）；null=从没有过信号（与 0 是两件事） */
  signal_age_s: number | null;
}

/**
 * **第一态的主体** —— 原生多模态摄入此刻的样子。
 *
 * 第一态的定义本身就是感知：后端 TriStatePhase.SILENT 的原文是「the system is
 * always alive in silent; it is receiving inputs (audio, visual, touch, text) from
 * its native modalities」。而在这一层之前，RenderPosture 里**一个感知字段都没有** ——
 * 感知状态走的是另一条平行的、无类型的分支 `payload.ambient`：面板手写类型读了它，
 * 覆盖层一次都没读过。也就是说第一态的视觉主体在渲染端没有数据来源。
 *
 * 它**不随相位裁剪**，而且恰恰是主轴 silent 时最要紧 —— 第一态是「在场但不表达」，
 * 没有这一层它就退化成「睡着」。
 */
export interface PerceptionView {
  /** unwired=进程里没有感知库，live=有 */
  source: ViewSource;
  /** 任一模态 live。便利位，由 modalities 推出 */
  is_sensing: boolean;
  /** 隐私急停是否生效 —— 整体姿态，不是四条恰好都闭着 */
  privacy_paused: boolean;
  /** 恒定四条，缺席的以 unavailable 出现 */
  modalities: ModalityView[];
  /** 自发注意力上一拍的决策；none=还没决策过 */
  ambient_action: AmbientAction;
  /** 那一拍为什么这么决定（后端原文，已截断） */
  ambient_rationale: string;
}

/**
 * 主轴上最近一次转移的**性质** —— 退场编排该看这一位。
 *
 * 覆盖层此前唯一的依据是一个标量深度，深度从 manifest 走回 silent 时，画面上
 * 放的就是进场动画倒着播。这个类型把「刚才发生的是哪一种转移」变成显式事实。
 *
 * `handoff` 与 `dissolving` **都是合法出口**：前者是「这一轮结果已提交、还有
 * 后续」（在场层 core/desktop_presence_system.py 的 MANIFEST→LIMINAL 策略），
 * 后者是「做完就散」。它们在不同的轴上，不是同一件事的两种说法 —— 所以渲染端
 * 按实际收到的这一位编排，不必也不该预先选定一条退场路线。
 */
export type TransitionKind = "none" | "emerging" | "committing" | "handoff" | "dissolving";

/**
 * 阈限空间三类内容里的**执行链**那两类。
 *
 * core/liminal_space_mapping.py 把阈限空间定义为「运行时的空间执行场」，装三类
 * 内容：本机执行链、跨设备执行链、沙盘推演。`is_active === false` 表示**这条链
 * 还没跑过**，不是「没有这条链」—— 零态本身是有意义的信号。
 */
export interface ExecutionChainView {
  /** local / cross_device —— 决定 last_target 的含义 */
  kind: ChainKind;
  /** 这条链是否跑过；false=还没跑过，不是「没有这条链」 */
  is_active: boolean;
  /** 本会话内这条链上的总执行次数 */
  total_executions: number;
  /** 其中走完整规范链的次数 */
  canonical_executions: number;
  /** 其中走遗留／非规范路径的次数 */
  legacy_executions: number;
  /** 规范链的步骤名（有序）—— 空间里该画几段 */
  chain_order: string[];
  /** 最近一次到达的步骤名 */
  last_step: string | null;
  /** local→task_id，cross_device→device_id */
  last_target: string | null;
}

/**
 * 表达期用什么手法在动手（直接调 API / 操作界面 / 看截图推理 / 混合）。
 *
 * 后端 core/hybrid_execution_policy.py 早就把它显式化了，但那个决策此前在
 * core/ 之外零消费方 —— 系统知道自己正在并行赛跑还是分阶段混合，却从没对外
 * 说过一个字。`is_decided === false` 与「决定了但没给理由」可区分。
 */
export interface HybridExecutionView {
  /** 本轮是否真的做过模式选择 */
  is_decided: boolean;
  /** 用什么手法动手；none=尚未决策 */
  mode: HybridExecutionMode;
  /** 选它的理由（后端策略引擎原文） */
  reason: string;
  /** [0,1]：1=精确命中规则，0.5=启发式，0=兜底 */
  confidence: number;
}

/**
 * 世界模型在阈限空间里的位置 —— **目前是留出的位置，`is_wired` 恒为 false**。
 *
 * enhancements/reasoning/world_model.py 是存在的，但没有通向渲染层的投影通路。
 * 这里显式区分 `unwired`（链路还没建）与 `live`（建好了，数就是这个），于是前端
 * 一次写对：链路接上时只有后端的构造函数需要改，前端判断不用动。
 */
export interface WorldModelView {
  /** 世界模型是否已接到渲染链路；当前恒 false */
  is_wired: boolean;
  /** unwired=链路还没建，live=数就是这个 */
  source: WorldModelSource;
  /** 已知实体数；unwired 时的 0 是「不知道」 */
  entity_count: number;
  /** 出现过的实体种类 */
  entity_kinds: string[];
}

/** 一条模态通路的名字。与后端协商层的四个模态一一对应。 */
export type PathwayModality = "vision_in" | "audio_in" | "audio_out" | "video_in";

/**
 * 这条通路是怎么走的。
 *
 *   native       模型自己吃这个模态 → 一条通路直达
 *   bridge       中间还有一段转换（听→ASR 转写、说→TTS 合成、视频→抽静帧）
 *   unavailable  不通，且没有桥可替
 *
 * `native` 与 `bridge` 都是「能用」，但**不是同一件事**：桥意味着多一段延迟、
 * 多一次信息损失（转写丢掉语气、抽帧丢掉连续性）。渲染上它们本就不该长一个样。
 */
export type PathwayMode = "native" | "bridge" | "unavailable";

/**
 * 谁把这条通路限制住的 —— 空串表示没被限制。
 *
 * 分成四类是因为**对用户是四件不同的事**：`serving` 开个环境变量就行，`model`
 * 要换本地模型，`provider` 要换一家云端，`device` 得换台机器。合成一个「不可用」
 * 的话，面板只能提示「不支持」，而用户无从知道该动哪里。
 */
export type PathwayLimit = "" | "model" | "serving" | "device" | "provider";

/** 本地档位形态：单模型 / 双位分工。unknown = 取不到档位表（不猜）。 */
export type TierKind = "unknown" | "single" | "composite";

/** 一条模态通路此刻的走法。 */
export interface PathwayLane {
  /** vision_in / audio_in / audio_out / video_in */
  modality: PathwayModality;
  /** native=一条通路直达；bridge=中间还有一段转换；unavailable=不通 */
  mode: PathwayMode;
  /** 谁把它限制住的：model=换模型 / serving=开环境变量 / device=换设备 / provider=换一家；空串=没被限制 */
  limited_by: PathwayLimit;
}

/**
 * 四条模态通路此刻走原生还是走桥。
 *
 * 与 `PerceptionView` 是两件事，缺一不可：那一位说「这一侧有没有信号」，这一位
 * 说「这条信号是**怎么**进去的」。第一态两侧的氛围光画的是后者。
 *
 * `lanes` **恒定四条**，不通的以 `unavailable` 出现 —— 渲染端要能把「这一侧不亮」
 * 画出来，而不是遍历一个长度会变的数组。
 *
 * `locus` 是这份结论照着谁算的。它不是装饰：本地档位没有视觉模型、而这一轮交给
 * 一家能看的云端时，视觉是**可用**的 —— 通路取决于这一轮由谁来想。
 */
export interface ModalityPathwayView {
  /** 这份结论照着谁算的：local 或某家 provider 名；空串=没协商过 */
  locus: string;
  /** 本地档位形态；unknown=取不到档位表（不猜） */
  tier_kind: TierKind;
  /** false=这个进程里没有协商层，四条全是占位空态 */
  is_wired: boolean;
  /** 恒定四条，不通的以 unavailable 出现 */
  lanes: PathwayLane[];
  /** 走原生的条数（由 lanes 推出的便利位） */
  native_count: number;
  /** 接了桥的条数（同上） */
  bridged_count: number;
}

/** 想这件事发生在哪一侧。`unknown` = 本进程还没路由过任何角色。 */
export type ThinkingLocus = "unknown" | "local" | "cloud";

/** 这次路由属于哪一类角色意图（派活 / 产出 / 把关）。 */
export type RouteType = "unknown" | "dispatch" | "produce" | "gatekeep";

/**
 * 这一轮的推理落在本地还是云端。
 *
 * manifest 那一段，本地推理与云端推理是完全不同的两件事：一个在这台机器上耗电、
 * 延迟由显存决定，一个在网络另一头、延迟由链路决定。此前契约里没有任何一位能把
 * 它们分开。
 *
 * `locus` 默认 `unknown` 而**不是** `local`：把没发生过的事画成「本地在想」，
 * 是三态里最不该乱画的那一段。`is_decided === false` 时下面几位都是空的。
 */
export interface ThinkingLocusView {
  /** 本进程是否路由过角色；false 时下面几位都是空的 */
  is_decided: boolean;
  /** local / cloud；unknown=还没想过，**不是**本地 */
  locus: ThinkingLocus;
  /** 选中的提供商名；未决策时空串 */
  provider: string;
  /** 选中的型号 */
  model: string;
  /** 这次路由是为哪个协作角色做的 */
  role: string;
  /** dispatch=派活 / produce=产出 / gatekeep=把关 */
  route_type: RouteType;
  /** 路由理由（后端原文，已截断） */
  reason: string;
  /** 角色意图没被满足：派活落到云端，或把关回落本地 —— 该画得不一样 */
  is_fallback: boolean;
  /** 本地这一轮开没开投机解码的草稿位；只在 locus=local 时有意义 */
  draft_active: boolean;
  /** 这台机器实测的倍数；0=没测过，<1=测过且更慢（那时 draft_active 为 false） */
  draft_speedup: number;
}

/** (上一档, 当前档) → 转移性质。缺失的组合按 `none` 处理。 */
export const TRANSITION_KIND_OF: ReadonlyArray<{from: Lifecycle; to: Lifecycle; kind: TransitionKind}> = [
  { from: "silent", to: "liminal", kind: "emerging" },
  { from: "silent", to: "manifest", kind: "committing" },
  { from: "liminal", to: "manifest", kind: "committing" },
  { from: "manifest", to: "liminal", kind: "handoff" },
  { from: "manifest", to: "silent", kind: "dissolving" },
  { from: "liminal", to: "silent", kind: "dissolving" },
];

/**
 * 相位之间【允许】的转移，源自 docs/PHASE_TRANSITION_TABLE.md。
 *
 * 渲染端据此可提前编排：处在 manifest 时唯一出口是 receding，所以退场动作
 * 该按「消散」准备，绝不是「退回 liminal」。
 */
export const PHASE_TRANSITIONS: Record<RenderPhase, RenderPhase[]> = {
  "formless": ["liminal"],
  "liminal": ["manifest", "formless"],
  "manifest": ["receding"],
  "receding": ["formless"],
};

/** 明令禁止的转移 + 理由。渲染端不该为它们编排动作。 */
export const FORBIDDEN_TRANSITIONS: ReadonlyArray<{from: RenderPhase; to: RenderPhase; why: string}> = [
  { from: "formless", to: "manifest", why: "跳过了 liminal 闸门，没有结构成型过（allow_emergency_jump 时例外）" },
  { from: "formless", to: "receding", why: "receding 要求先有过在场" },
  { from: "manifest", to: "liminal", why: "结构不能不经 receding 就解体" },
  { from: "receding", to: "manifest", why: "必须先回到 formless 才能重新进入 manifest" },
  { from: "receding", to: "liminal", why: "必须先回到 formless 才能重新进入 liminal" },
];

/** 四相 → 三态的公共投影表。 */
export const TRI_STATE_OF: Record<RenderPhase, WirePhaseTri> = {
  "formless": "silent",
  "liminal": "liminal",
  "manifest": "manifest",
  "receding": "silent",
};

export interface RenderPosture {
  /** 【主轴】主体生命周期 —— 渲染端的整体编排跟它走 */
  lifecycle: Lifecycle;
  /** 主轴的上一档（相位事件自带 from_phase）；null=还没发生过转移 */
  previous_lifecycle: Lifecycle | null;
  /** 刚才那次转移的性质 —— 退场编排看这一位，别从深度差里猜 */
  transition_kind: TransitionKind;
  /** 【副轴】内部连续体四相，提供主轴给不出的纹理 */
  continuum_phase: RenderPhase;
  /** 副轴是否在返回弧上（receding）——把「刚做完」与「静息」分开的那一位 */
  is_returning: boolean;
  /** 副轴从当前相位合法能去的下一相 */
  next_phases: RenderPhase[];
  /** 阈限态里正在干嘛（有序递进）：none → understanding → thinking → rehearsing */
  liminal_activity: LiminalActivity;
  /** 沙盘推演摘要 —— 阈限态的可视内容之三 */
  simulation: SimulationSummary;
  /** 本机执行链 —— 阈限态的可视内容之一 */
  local_chain: ExecutionChainView;
  /** 跨设备执行链 —— 阈限态的可视内容之二 */
  cross_device_chain: ExecutionChainView;
  /** 世界模型 —— 留出的位置，当前恒 unwired */
  world_model: WorldModelView;
  /** **第一态的主体** —— 原生多模态摄入此刻的样子；不随相位裁剪 */
  perception: PerceptionView;
  /** 表达期用什么手法动手（GUI／API／混合） */
  hybrid_execution: HybridExecutionView;
  /** 四条模态通路走原生还是走桥 —— perception 说有没有信号，这一位说它怎么进去的 */
  pathway: ModalityPathwayView;
  /** 这一轮在哪儿想（本地／云端）；unknown=还没想过，不是本地 */
  thinking_locus: ThinkingLocusView;
  /** 第二维：在哪儿跑；null=尚未判定 */
  runtime_domain: RuntimeDomain | null;
  /** 抽象运动能量 [0,1] */
  motion: number;
  /** 整体在场强度 [0,1] */
  intensity: number;
  /** 形态提示；receding 对应 collapsing_field */
  form_signature: FormSignature;
  /** 空间权重／贴近度 */
  spatial_presence: SpatialPresence;
  /** 质感描述（soft_dissolve 等）；空串=无提示 */
  texture_hint: string;
  /** EMA 平滑的在场强度 [0,1] */
  presence_intensity: number;
  /** 信号成意图的程度 [0,1] */
  coherence: number;
  /** coherence 的反面 [0,1] */
  ambiguity: number;
  /** 推向塌缩（liminal→manifest）的概率质量 [0,1] */
  collapse_tendency: number;
  /** 推向 receding 的概率质量 [0,1]（不是退回上一档） */
  retreat_tendency: number;
  /** 时间稳定度 [0,1]，低值表示刚振荡过 */
  stability: number;
  /** 实算还是兜底 */
  source: PhasePostureSource;
  /** continuum 本拍是否降级 */
  degraded: boolean;
  /** 仅 degraded=true 时有值 */
  degrade_reason: string | null;
}
