// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.
// 源:core/phase_contract.py(面板侧相位契约 SSOT)。改后端字段后重跑该脚本。

/**
 * 后端【线上】传输的三态 token。
 *
 * 刻意不叫 `Phase`：面板自己的 `types/phase.ts` 里已有一个 `Phase`,
 * 取值是 'silent' | 'liminal' | 'manifest'（展示词汇），而后端发的是
 * 'static'（见 core/desktop_presence_system.py 的 STATIC）。两者同名不同义，
 * 一起 import 会撞。转换由 usePhase.ts 的 _mapPhaseToken 负责。
 *
 * 连续量只描述它在这一档里的位置，不改变是哪一档。
 */
export type WirePhase = "static" | "liminal" | "manifest";

/** depth 是实算的还是锚点兜底。前端可据此区分精确态/估计态。 */
export type PhasePostureSource = "continuum" | "anchor_only";

/** 三态在渲染深度轴上的锚点。前端过渡编排按这几个数调。 */
export const PHASE_ANCHORS: Record<WirePhase, number> = {
  "static": 0.05,
  "liminal": 0.62,
  "manifest": 0.92,
};

/** 边缘混合上限:倾向为 1 时深度最多向邻档漂移两档间距的这个比例。 */
export const PHASE_EDGE_BLEND = 0.45;

export interface PhasePosture {
  /** 后端线上传输的三态 token（static/liminal/manifest），仍然是权威 */
  phase: WirePhase;
  /** 渲染深度 [0,1]，在相位带内漂移 */
  depth: number;
  /** EMA 平滑的在场强度 [0,1] */
  presence_intensity: number;
  /** 信号成意图的程度 [0,1] */
  coherence: number;
  /** 推向下一档的概率质量 [0,1] */
  collapse_tendency: number;
  /** 推向 receding 的概率质量 [0,1]。注意：在本【遗留】投影里它被当作「向上一档锚点漂移」，那是语义误读，见 RenderPosture 的同名字段 */
  retreat_tendency: number;
  /** 时间稳定度 [0,1]，低值表示刚发生过振荡 */
  stability: number;
  /** 深度来自实算还是锚点兜底 */
  source: PhasePostureSource;
}


// ═══════════════════════════════════════════════════════════════════
// 忠实契约：按 core/continuum 的实际形状生成
//
// 上面的 PhasePosture 是一维遗留投影（三锚点串在一条 depth 轴上），保留
// 只为兼容既有覆盖层 presence_motion.js。**新代码应当消费 RenderPosture。**
//
// 差别是结构性的，不是字段多少：
//   · 四相 vs 三态 —— receding（返回弧）在遗留投影里被折叠成 silent，
//     于是「刚做完正在退场」与「静息」在渲染端不可分辨；
//   · 二维 vs 一维 —— runtime_domain（在哪儿跑）遗留投影里完全没有；
//   · retreat_tendency 的语义 —— 后端原文是「推向 receding」，遗留投影
//     把它当成「退回上一档」，那会表达出转移表明令禁止的 manifest→liminal。
// ═══════════════════════════════════════════════════════════════════

/**
 * 【主轴】主体生命周期（后端 TriState）——渲染端的整体编排跟这一根走。
 *
 * 它就是用户能直接感知的节奏：休息 / 过渡 / 对外表达。在场桥广播的
 * `payload.phase` 一直是这一根。
 */
export type Lifecycle = "silent" | "liminal" | "manifest";

/**
 * 【副轴】内部连续体四相 —— 提供主轴给不出的纹理，不决定整体编排。
 *
 * 比主轴多一相 `receding`（返回弧）。主轴回到 `silent` 时，靠副轴才能
 * 区分「刚做完正在消散」(receding) 与「静息」(formless)。
 */
export type RenderPhase = "formless" | "liminal" | "manifest" | "receding";

/** 阈限态里正在发生什么。主轴说「在过渡」，这一项说「过渡里在干嘛」。 */
export type LiminalActivity = "none" | "understanding" | "thinking" | "rehearsing";

/** 沙盘推演的种类。 */
export type SimulationKind = "none" | "speculative" | "sandbox";

/**
 * 阈限态沙盘推演摘要 —— **阈限态的可视内容**。
 *
 * 阈限态在面板上一直「什么都没有」，根因不是动画简陋，是这一层从没送出来过：
 * 智能体在真正落手之前会先在影子沙盘里推演若干条候选路径（见后端
 * core/liminal_rehearsal.py），`candidate_paths` 就是它正在权衡的那几条，
 * `committed_path` 是最终提交的那条。
 */
export interface SimulationSummary {
  /** 当前是否有推演在跑 */
  is_active: boolean;
  /** none / speculative / sandbox */
  simulation_kind: SimulationKind;
  /** 正在评估的候选执行路径 —— 阈限态在权衡什么 */
  candidate_paths: string[];
  /** 已提交的那条；仍在推演/全失败时 null */
  committed_path: string | null;
  /** committed_path !== null */
  is_committed: boolean;
  /** 已完成的推演步数 */
  step_count: number;
  /** 场景的人类可读标签 */
  scenario_label: string | null;
}

/** 三态公共投影。仅供必须使用公共词汇的消费者；用它画图会丢掉返回弧。 */
export type WirePhaseTri = "liminal" | "manifest" | "silent";

/** 第二维：执行发生在哪儿。 */
export type RuntimeDomain = "local" | "cross_device" | "transition";

/** 形态提示（后端 ExpressionEngine 算出，非前端推导）。 */
export type FormSignature = "none" | "diffuse_cluster" | "focused_point" | "expanding_ring" | "collapsing_field";

/** 抽象空间权重／贴近度。 */
export type SpatialPresence = "absent" | "peripheral" | "ambient" | "foreground";

/** 执行链的种类。决定 ExecutionChainView.last_target 指的是任务还是设备。 */
export type ChainKind = "local" | "cross_device";

/** 表达期用什么手法动手。none = 尚未决策。 */
export type HybridExecutionMode = "none" | "sequential_degrade" | "parallel_race" | "staged_hybrid" | "local_preferred" | "remote_preferred";

/** 世界模型视图的来源。unwired = 这条链路还没建，不是「零个实体」。 */
export type WorldModelSource = "unwired" | "live";

/**
 * 主轴上最近一次转移的**性质** —— 退场编排该看这一位。
 *
 * 覆盖层此前唯一的依据是一个标量深度，深度从 manifest 走回 silent 时，画面上
 * 放的就是进场动画倒着播。这个类型把「刚才发生的是哪一种转移」变成显式事实。
 *
 * `handoff` 与 `dissolving` **都是合法出口**：前者是「这一轮结果已提交、还有
 * 后续」（在场层 core/desktop_presence_system.py 的 MANIFEST→LIMINAL 策略），
 * 后者是「做完就散」。它们在不同的轴上，不是同一件事的两种说法 —— 所以渲染端
 * 按实际收到的这一位编排，不必也不该预先选定一条退场路线。
 */
export type TransitionKind = "none" | "emerging" | "committing" | "handoff" | "dissolving";

/**
 * 阈限空间三类内容里的**执行链**那两类。
 *
 * core/liminal_space_mapping.py 把阈限空间定义为「运行时的空间执行场」，装三类
 * 内容：本机执行链、跨设备执行链、沙盘推演。`is_active === false` 表示**这条链
 * 还没跑过**，不是「没有这条链」—— 零态本身是有意义的信号。
 */
export interface ExecutionChainView {
  /** local / cross_device —— 决定 last_target 的含义 */
  kind: ChainKind;
  /** 这条链是否跑过；false=还没跑过，不是「没有这条链」 */
  is_active: boolean;
  /** 本会话内这条链上的总执行次数 */
  total_executions: number;
  /** 其中走完整规范链的次数 */
  canonical_executions: number;
  /** 其中走遗留／非规范路径的次数 */
  legacy_executions: number;
  /** 规范链的步骤名（有序）—— 空间里该画几段 */
  chain_order: string[];
  /** 最近一次到达的步骤名 */
  last_step: string | null;
  /** local→task_id，cross_device→device_id */
  last_target: string | null;
}

/**
 * 表达期用什么手法在动手（直接调 API / 操作界面 / 看截图推理 / 混合）。
 *
 * 后端 core/hybrid_execution_policy.py 早就把它显式化了，但那个决策此前在
 * core/ 之外零消费方 —— 系统知道自己正在并行赛跑还是分阶段混合，却从没对外
 * 说过一个字。`is_decided === false` 与「决定了但没给理由」可区分。
 */
export interface HybridExecutionView {
  /** 本轮是否真的做过模式选择 */
  is_decided: boolean;
  /** 用什么手法动手；none=尚未决策 */
  mode: HybridExecutionMode;
  /** 选它的理由（后端策略引擎原文） */
  reason: string;
  /** [0,1]：1=精确命中规则，0.5=启发式，0=兜底 */
  confidence: number;
}

/**
 * 世界模型在阈限空间里的位置 —— **目前是留出的位置，`is_wired` 恒为 false**。
 *
 * enhancements/reasoning/world_model.py 是存在的，但没有通向渲染层的投影通路。
 * 这里显式区分 `unwired`（链路还没建）与 `live`（建好了，数就是这个），于是前端
 * 一次写对：链路接上时只有后端的构造函数需要改，前端判断不用动。
 */
export interface WorldModelView {
  /** 世界模型是否已接到渲染链路；当前恒 false */
  is_wired: boolean;
  /** unwired=链路还没建，live=数就是这个 */
  source: WorldModelSource;
  /** 已知实体数；unwired 时的 0 是「不知道」 */
  entity_count: number;
  /** 出现过的实体种类 */
  entity_kinds: string[];
}

/** (上一档, 当前档) → 转移性质。缺失的组合按 `none` 处理。 */
export const TRANSITION_KIND_OF: ReadonlyArray<{from: Lifecycle; to: Lifecycle; kind: TransitionKind}> = [
  { from: "silent", to: "liminal", kind: "emerging" },
  { from: "silent", to: "manifest", kind: "committing" },
  { from: "liminal", to: "manifest", kind: "committing" },
  { from: "manifest", to: "liminal", kind: "handoff" },
  { from: "manifest", to: "silent", kind: "dissolving" },
  { from: "liminal", to: "silent", kind: "dissolving" },
];

/**
 * 相位之间【允许】的转移，源自 docs/PHASE_TRANSITION_TABLE.md。
 *
 * 渲染端据此可提前编排：处在 manifest 时唯一出口是 receding，所以退场动作
 * 该按「消散」准备，绝不是「退回 liminal」。
 */
export const PHASE_TRANSITIONS: Record<RenderPhase, RenderPhase[]> = {
  "formless": ["liminal"],
  "liminal": ["manifest", "formless"],
  "manifest": ["receding"],
  "receding": ["formless"],
};

/** 明令禁止的转移 + 理由。渲染端不该为它们编排动作。 */
export const FORBIDDEN_TRANSITIONS: ReadonlyArray<{from: RenderPhase; to: RenderPhase; why: string}> = [
  { from: "formless", to: "manifest", why: "跳过了 liminal 闸门，没有结构成型过（allow_emergency_jump 时例外）" },
  { from: "formless", to: "receding", why: "receding 要求先有过在场" },
  { from: "manifest", to: "liminal", why: "结构不能不经 receding 就解体" },
  { from: "receding", to: "manifest", why: "必须先回到 formless 才能重新进入 manifest" },
  { from: "receding", to: "liminal", why: "必须先回到 formless 才能重新进入 liminal" },
];

/** 四相 → 三态的公共投影表。 */
export const TRI_STATE_OF: Record<RenderPhase, WirePhaseTri> = {
  "formless": "silent",
  "liminal": "liminal",
  "manifest": "manifest",
  "receding": "silent",
};

export interface RenderPosture {
  /** 【主轴】主体生命周期 —— 渲染端的整体编排跟它走 */
  lifecycle: Lifecycle;
  /** 主轴的上一档（相位事件自带 from_phase）；null=还没发生过转移 */
  previous_lifecycle: Lifecycle | null;
  /** 刚才那次转移的性质 —— 退场编排看这一位，别从深度差里猜 */
  transition_kind: TransitionKind;
  /** 【副轴】内部连续体四相，提供主轴给不出的纹理 */
  continuum_phase: RenderPhase;
  /** 副轴是否在返回弧上（receding）——把「刚做完」与「静息」分开的那一位 */
  is_returning: boolean;
  /** 副轴从当前相位合法能去的下一相 */
  next_phases: RenderPhase[];
  /** 阈限态里正在干嘛（有序递进）：none → understanding → thinking → rehearsing */
  liminal_activity: LiminalActivity;
  /** 沙盘推演摘要 —— 阈限态的可视内容之三 */
  simulation: SimulationSummary;
  /** 本机执行链 —— 阈限态的可视内容之一 */
  local_chain: ExecutionChainView;
  /** 跨设备执行链 —— 阈限态的可视内容之二 */
  cross_device_chain: ExecutionChainView;
  /** 世界模型 —— 留出的位置，当前恒 unwired */
  world_model: WorldModelView;
  /** 表达期用什么手法动手（GUI／API／混合） */
  hybrid_execution: HybridExecutionView;
  /** 第二维：在哪儿跑；null=尚未判定 */
  runtime_domain: RuntimeDomain | null;
  /** 抽象运动能量 [0,1] */
  motion: number;
  /** 整体在场强度 [0,1] */
  intensity: number;
  /** 形态提示；receding 对应 collapsing_field */
  form_signature: FormSignature;
  /** 空间权重／贴近度 */
  spatial_presence: SpatialPresence;
  /** 质感描述（soft_dissolve 等）；空串=无提示 */
  texture_hint: string;
  /** EMA 平滑的在场强度 [0,1] */
  presence_intensity: number;
  /** 信号成意图的程度 [0,1] */
  coherence: number;
  /** coherence 的反面 [0,1] */
  ambiguity: number;
  /** 推向塌缩（liminal→manifest）的概率质量 [0,1] */
  collapse_tendency: number;
  /** 推向 receding 的概率质量 [0,1]（不是退回上一档） */
  retreat_tendency: number;
  /** 时间稳定度 [0,1]，低值表示刚振荡过 */
  stability: number;
  /** 实算还是兜底 */
  source: PhasePostureSource;
  /** continuum 本拍是否降级 */
  degraded: boolean;
  /** 仅 degraded=true 时有值 */
  degrade_reason: string | null;
}
