// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.
// 源:core/schemas/ui_element.py(结构化 UI 契约 SSOT)。改后端字段后重跑该脚本。

export type UISource = "uia" | "atspi" | "ax" | "android_a11y" | "vision" | "ocr" | "hybrid";
export type UIActionKind = "tap" | "double_tap" | "long_press" | "right_click" | "set_text" | "clear" | "scroll" | "swipe" | "focus" | "open_app" | "back" | "home" | "key";

export interface UIBounds {
  x?: number;
  y?: number;
  width?: number;
  height?: number;
}
export interface UIElementNode {
  node_id?: string;
  role?: string;
  label?: string;
  value?: string;
  bounds?: UIBounds | null;
  clickable?: boolean;
  editable?: boolean;
  focused?: boolean;
  enabled?: boolean;
  visible?: boolean;
  selected?: boolean;
  scrollable?: boolean;
  checked?: boolean | null;
  actions?: UIActionKind[];
  source?: UISource;
  confidence?: number;
  automation_id?: string;
  class_name?: string;
  package?: string;
  children?: UIElementNode[];
}
export interface UIGraph {
  root?: UIElementNode | null;
  source?: UISource;
  device_id?: string;
  app?: string;
  screen_width?: number;
  screen_height?: number;
  captured_at_ms?: number;
  merged_from?: UISource[];
  vision_added?: number;
}
