"""core/runtime/__init__.py
============================
Galaxy runtime sub-package.

Exports the target-side local takeover path introduced in PR-34, the
source-side dispatch orchestrator introduced in PR-35, the cross-runtime
result merge helpers introduced in PR-36, and the mesh session coordinator
helpers introduced in PR-37.

PR-2 (post-533 dual-repo runtime host unification): exports posture-aware
source execution eligibility helpers from
``core.source_execution_eligibility``.

PR package 1 (post-533 dual-repo runtime unification master plan, MAIN repo
side): exports posture contract canonicalization enforcement helpers from
``core.posture_contract_canonicalization``.

PR-5 (post-533 dual-repo runtime unification, MAIN repo side): exports
Android first-class runtime host classification and identity helpers from
``core.android_runtime_host``.

PR package 6 (post-533 dual-repo runtime unification master plan, MAIN repo
side): exports canonical device/host capability representation and
scheduling-basis normalization helpers from
``core.canonical_capability_scheduling_basis``.

PR package 7 (post-533 dual-repo runtime unification master plan, MAIN repo
side): exports canonical persistent attached-runtime session semantics from
``core.attached_runtime_session``.

PR package 9 (post-533 dual-repo runtime unification master plan, MAIN repo
side): exports canonical delegated-runtime handoff contract foundations from
``core.delegated_runtime_handoff_contract``.

PR-4V2 (Android runtime truth reconciliation into V2 canonical orchestration):
exports Android participant/session/runtime truth ingress and canonical
reconciliation helpers from ``core.android_participant_truth_ingress``.
Closes TRUTH-005.
"""

from core.runtime.target_takeover import (
    TargetTakeoverHandler,
    adopt_handoff_session,
    build_local_takeover_context,
    resolve_or_create_runtime_session,
    normalize_handoff_envelope,
    execute_local_takeover,
)

# PR-35: Source Runtime Dispatch Orchestrator
from core.runtime.source_dispatch_orchestrator import (
    SourceDispatchOrchestrator,
    select_dispatch_mode,
    select_dispatch_target,
    build_source_dispatch_plan,
    orchestrate_source_runtime_dispatch,
    # PR-24: dispatch selection truth consolidation
    DISPATCH_SELECTION_TRUTH_CONSOLIDATED_PR24_SENTINEL,
    SELECTION_READINESS_IS_REQUIRED_TRUTH_PR24_POLICY,
    SELECTION_PARTICIPATION_IS_REQUIRED_TRUTH_PR24_POLICY,
    SELECTION_REGISTRY_IS_CANONICAL_GATE_PR24_POLICY,
    SELECTION_REUSE_CONTRIBUTES_PREFERENCE_PR24_POLICY,
    SELECTION_FALLBACK_IS_STABLE_AND_EXPLAINABLE_PR24_POLICY,
    # PR-25: mainline abnormal-path matrix + Phase A acceptance
    MAINLINE_ABNORMAL_PATH_MATRIX_CLOSED_PR25_SENTINEL,
    REMOTE_TASK_BLOCKS_LOCAL_LOOP_ABNORMAL_PATH_PR25_POLICY,
    LOCAL_FALLBACK_AFTER_REMOTE_FAILURE_ABNORMAL_PATH_PR25_POLICY,
    DELEGATED_EXECUTION_FAILURE_SESSION_TRUTH_IS_PRESERVED_PR25_POLICY,
    SELECTION_FALLBACK_UNDER_DEGRADED_CONDITIONS_IS_STABLE_PR25_POLICY,
    PHASE_A_ACCEPTANCE_ABNORMAL_PATH_PR25_POLICY,
    # PR-26: client-facing result surfacing normalization
    CLIENT_FACING_RESULT_SURFACING_NORMALIZED_PR26_SENTINEL,
    RESULT_CONTRACT_IS_INVARIANT_ACROSS_DISPATCH_PATHS_PR26_POLICY,
    RESULT_SEMANTICS_ARE_COHERENT_REGARDLESS_OF_PATH_PR26_POLICY,
    RESULT_IDENTITY_IS_STABLE_ACROSS_EXECUTION_PATHS_PR26_POLICY,
    NO_PATH_SPECIFIC_RESULT_CONTRACT_DRIFT_PR26_POLICY,
    # PR-27: gateway-facing registration and capability error semantics hardening
    GATEWAY_FACING_REGISTRATION_CAPABILITY_ERROR_SEMANTICS_HARDENED_PR27_SENTINEL,
    REGISTRATION_FAILURE_IS_DISTINGUISHABLE_FROM_CAPABILITY_FAILURE_PR27_POLICY,
    READINESS_DEGRADED_BEHAVIOR_IS_REPORTED_THROUGH_STABLE_SIGNALS_PR27_POLICY,
    CAPABILITY_NOT_SATISFIED_FAILURE_IS_ACTIONABLE_PR27_POLICY,
    GATEWAY_SETUP_CONNECTION_SIGNALS_ARE_DETERMINISTIC_PR27_POLICY,
    # PR-28: integrated regression closure and release-readiness tightening
    INTEGRATED_REGRESSION_CLOSURE_RELEASE_READINESS_PR28_SENTINEL,
    END_TO_END_DISPATCH_EXECUTION_RESULT_COHERENCE_PR28_POLICY,
    INTEGRATED_SELECTION_REGISTRY_REUSE_FALLBACK_BEHAVIOR_PR28_POLICY,
    REGISTRATION_CAPABILITY_READINESS_UNDER_INTEGRATED_SCENARIOS_PR28_POLICY,
    REGRESSION_STABILIZATION_RELEASE_READINESS_TIGHTENING_PR28_POLICY,
    # PR-29: post-release follow-up tightening across dispatch and client semantics
    POST_RELEASE_DISPATCH_CLIENT_SEMANTICS_TIGHTENING_PR29_SENTINEL,
    DISPATCH_SELECTION_COHESION_POST_RELEASE_PR29_POLICY,
    REGISTRATION_READINESS_CAPABILITY_STABILITY_POST_RELEASE_PR29_POLICY,
    DELEGATED_EXECUTION_FALLBACK_SEMANTIC_CONSISTENCY_PR29_POLICY,
    CLIENT_GATEWAY_RESULT_CONTRACT_ALIGNMENT_POST_RELEASE_PR29_POLICY,
    # PR-30: observability and diagnostics hardening for rollout safety
    OBSERVABILITY_DIAGNOSTICS_ROLLOUT_SAFETY_HARDENING_PR30_SENTINEL,
    DISPATCH_PATH_DECISION_OBSERVABILITY_PR30_POLICY,
    REGISTRATION_READINESS_CAPABILITY_FALLBACK_DIAGNOSTICS_PR30_POLICY,
    DELEGATED_EXECUTION_OBSERVABILITY_PR30_POLICY,
    ROLLOUT_SAFETY_SIGNALS_CLIENT_RESULT_OBSERVABILITY_PR30_POLICY,
    # PR-31: rollout controls, default behaviors, and safe-operating release toggles
    ROLLOUT_CONTROLS_DEFAULT_BEHAVIORS_SAFE_RELEASE_PR31_SENTINEL,
    FEATURE_TOGGLE_DEFAULT_BEHAVIOR_ROLLOUT_CONTROL_PR31_POLICY,
    KILL_SWITCH_SAFE_DISABLE_ROLLBACK_BEHAVIOR_PR31_POLICY,
    SELECTION_REGISTRATION_READINESS_CAPABILITY_SAFE_DEFAULTS_PR31_POLICY,
    DELEGATED_FALLBACK_RELEASE_OPERATION_CONSISTENCY_PR31_POLICY,
    # PR-32: staged mesh minimal executable closure
    STAGED_MESH_MINIMAL_EXECUTABLE_CLOSURE_PR32_SENTINEL,
    STAGED_MESH_PLAN_TO_EXECUTION_TRANSITION_PR32_POLICY,
    STAGED_MESH_SESSION_COORDINATOR_INTEGRATION_PR32_POLICY,
    STAGED_MESH_RESULT_INTEGRATION_CONTRACT_PR32_POLICY,
    STAGED_MESH_GRACEFUL_DEGRADATION_FALLBACK_PR32_POLICY,
    # PR-J: live mesh runtime engine
    LIVE_MESH_RUNTIME_ENGINE_ORCHESTRATOR_PR_J_SENTINEL,
    LIVE_MESH_STAGED_TO_ACTIVE_DISPATCH_PR_J_POLICY,
    LIVE_MESH_RESULT_CONVERGENCE_PR_J_POLICY,
    # PR-33: reconnect and recovery consistency hardening
    RECONNECT_RECOVERY_CONSISTENCY_PR33_SENTINEL,
    RECONNECT_MUST_NOT_BREAK_HOST_SIDE_TRUTH_PR33_POLICY,
    REGISTRY_RECONNECT_EVENT_IS_OBSERVABLE_PR33_POLICY,
    EXECUTION_TRACKER_SURVIVES_RECONNECT_PR33_POLICY,
    RESULT_MERGE_CONSISTENT_THROUGH_RECOVERY_PR33_POLICY,
    # PR-34: final product-grade cross-device and runtime acceptance pack
    CROSS_DEVICE_RUNTIME_ACCEPTANCE_PR34_SENTINEL,
    DISPATCH_FALLBACK_RESULT_MERGE_STABILITY_PR34_POLICY,
    ANDROID_ATTACHED_RUNTIME_ORCHESTRATION_STABILITY_PR34_POLICY,
    MULTI_TARGET_RANKING_MATURITY_PR34_POLICY,
    STAGED_MESH_CLOSURE_RUNNABLE_PR34_POLICY,
    DIAGNOSTICS_READINESS_PARTICIPATION_FORMATION_USABILITY_PR34_POLICY,
    # PR-closure: Android terminal signal → canonical ReplayFoundation truth
    ANDROID_TERMINAL_SIGNAL_RECORDED_TO_CANONICAL_TRUTH_SENTINEL,
    ANDROID_TERMINAL_SIGNAL_RECORDS_TO_REPLAY_FOUNDATION_POLICY,
)

# PR-36: Cross-Runtime Result Merge Contract helpers
from contracts.cross_runtime_result_merge import (
    RuntimeResultRole,
    RuntimeResultStatus,
    ResultMergePolicy,
    RuntimeResultUnit,
    MergedRuntimeResult,
    ResultMergeSummary,
    from_local_takeover_result as merge_unit_from_takeover_result,
    from_source_dispatch_result as merge_unit_from_dispatch_result,
    from_execution_output as merge_unit_from_execution_output,
    build_merged_runtime_result,
    merge_runtime_results,
    build_result_merge_summary,
)

# PR-37: Mesh Session Coordinator (mesh package)
# Imported here for convenience so consumers can reach the coordinator
# from either core.runtime or core.mesh.
from core.mesh.mesh_session_coordinator import (  # noqa: E402
    MeshSessionCoordinator,
    coordinate_mesh_session,
    get_coordinator_summary,
    # PR-J: live mesh runtime execution helpers
    run_live_mesh_session,
    register_participant,
    update_participant_status,
    drop_participant,
    MESH_SESSION_COORDINATOR_LIVE_RUNTIME_ENGINE_PR_J_SENTINEL,
)

# PR-J: Live MeshSession Coordinator — incremental event-driven runtime driver.
# Re-exported here so callers can reach the live coordinator from core.runtime.
from core.mesh.live_mesh_session_coordinator import (  # noqa: E402
    LiveMeshSessionCoordinator,
    create_live_mesh_session_coordinator,
    LIVE_MESH_SESSION_COORDINATOR_PR_J_SENTINEL,
    INCREMENTAL_PARTICIPANT_EVENTS_PR_J_POLICY,
    BARRIER_TRACKS_ACROSS_EVENTS_PR_J_POLICY,
    COORDINATOR_FINALIZE_PRODUCES_STABLE_RESULT_PR_J_POLICY,
    PARTICIPANT_DROPOUT_AFFECTS_OUTCOME_PR_J_POLICY,
)

# PR-2 (post-533 dual-repo runtime host unification): posture-aware source
# execution eligibility.  Re-exported here so callers can reach the
# eligibility API from core.runtime without importing the module directly.
from core.source_execution_eligibility import (  # noqa: E402
    SOURCE_DISPATCH_POSTURE_AWARE_AUTHORITY,
    CONTROL_ONLY_SOURCE_INELIGIBLE_FOR_LOCAL_EXECUTION_POLICY,
    JOIN_RUNTIME_SOURCE_ELIGIBLE_FOR_LOCAL_EXECUTION_POLICY,
    POSTURE_GATED_LOCAL_EXECUTION_POLICY,
    POSTURE_AWARE_DISPATCH_INTEGRATED_SENTINEL,
    # PR-2 coordination-role alignment
    OBSERVER_ONLY_ROLE_BLOCKS_EXECUTION_POLICY,
    COORDINATION_ROLE_ALIGNED_DISPATCH_SENTINEL,
    SourceExecutionEligibility,
    check_source_execution_eligibility,
    is_source_eligible_for_local_execution,
    resolve_posture_for_eligibility,
    check_source_eligibility_with_coordination_role,
)

# PR-4 (post-533 dual-repo runtime host unification): canonical session truth
# and posture-aware result merge.  Re-exported here so callers can reach the
# session truth API from core.runtime without importing the module directly.
from core.canonical_session_truth import (  # noqa: E402
    CANONICAL_SESSION_TRUTH_AUTHORITY,
    CONTROL_ONLY_EXCLUDED_FROM_MERGE_POLICY,
    POSTURE_AWARE_RESULT_FILTER_POLICY,
    JOIN_RUNTIME_INCLUDED_IN_MERGE_POLICY,
    OBSERVER_ONLY_ROLE_EXCLUDED_FROM_MERGE_POLICY,
    CANONICAL_SESSION_TRUTH_PR4_SENTINEL,
    SessionTruthSource,
    CanonicalSessionTruthRecord,
    CanonicalSessionTruthRuntime,
    CanonicalSessionTruthSnapshot,
    filter_result_units_by_posture,
    merge_session_truth,
    record_session_truth,
    build_canonical_session_truth_snapshot,
    get_canonical_session_truth_runtime,
    reset_canonical_session_truth_runtime,
)

# PR package 1 (post-533 dual-repo runtime unification, MAIN repo side):
# posture contract canonicalization enforcement layer.
from core.posture_contract_canonicalization import (  # noqa: E402
    canonicalize_posture_in_payload,
    validate_posture_field_consistency,
    assert_posture_boundary_compliance,
    get_posture_from_payload,
    PostureBoundaryViolation,
    POSTURE_CONTRACT_CANONICALIZATION_AUTHORITY,
    POSTURE_BOUNDARY_NO_ENTRY_MODE_CONFLATION_POLICY,
    POSTURE_BOUNDARY_NO_CROSS_DEVICE_FLAG_CONFLATION_POLICY,
    POSTURE_BOUNDARY_NO_FORMATION_ROLE_CONFLATION_POLICY,
    POSTURE_CONTRACT_PR_PACKAGE_1_SENTINEL,
)

# PR-6 (post-533 dual-repo runtime host unification): multi-device coordination
# authority and canonical role modelling.  Re-exported here so callers can
# reach the coordination role API from core.runtime without importing the
# module directly.
from core.multi_device_coordination_authority import (  # noqa: E402
    MULTI_DEVICE_COORDINATION_AUTHORITY,
    MULTI_DEVICE_COORDINATION_AUTHORITY_PR6_SENTINEL,
    SOURCE_CONTROLLER_OWNS_RUNTIME_AUTHORITY_POLICY,
    TARGET_ONLY_EXECUTOR_HAS_NO_CONTROL_AUTHORITY_POLICY,
    OBSERVER_ONLY_HAS_NO_EXECUTION_AUTHORITY_POLICY,
    COORDINATION_ROLE_DERIVATION_IS_POSTURE_DRIVEN_POLICY,
    CoordinationRole,
    CoordinationRoleRecord,
    CoordinationRoleSnapshot,
    CoordinationRoleRuntime,
    derive_coordination_role,
    build_coordination_role_record,
    build_coordination_role_snapshot,
    record_coordination_role,
    get_coordination_role_runtime,
    reset_coordination_role_runtime,
    get_source_controller_device_id,
)

# PR-5 (post-533 dual-repo runtime unification, MAIN repo side): Android
# first-class runtime host classification and identity.  Re-exported here
# so callers can reach Android host typing from core.runtime without
# importing the module directly.
from core.android_runtime_host import (  # noqa: E402
    ANDROID_FIRST_CLASS_RUNTIME_HOST_PR5_SENTINEL,
    ANDROID_RUNTIME_HOST_DISTINCT_FROM_CONNECTED_DEVICE_PR5,
    ANDROID_RUNTIME_HOST_POSTURE_PRESERVED_PR5,
    AndroidRuntimeHostRole,
    AndroidRuntimeHostIdentity,
    classify_android_runtime_host,
    build_android_runtime_host_identity,
)

# PR package 6 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): canonical device/host capability representation and scheduling-basis
# normalization.  Re-exported here so callers can reach the capability/
# scheduling API from core.runtime without importing the module directly.
from core.canonical_capability_scheduling_basis import (  # noqa: E402
    CANONICAL_CAPABILITY_SCHEDULING_BASIS_AUTHORITY,
    FULL_RUNTIME_TIER_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY,
    COMMAND_ONLY_TIER_BLOCKS_EXECUTION_PLACEMENT_POLICY,
    CAPABILITY_TIER_DRIVES_SURFACE_ELIGIBILITY_POLICY,
    OBSERVER_ONLY_ROLE_EXCLUDED_FROM_SCHEDULING_POLICY,
    ANDROID_HOST_CAPABILITY_LIFTED_FROM_PR5_POLICY,
    SCHEDULING_BASIS_NORMALISATION_IS_ADDITIVE_POLICY,
    CANONICAL_CAPABILITY_SCHEDULING_BASIS_PR6_SENTINEL,
    CapabilityTier,
    ExecutionSurface,
    RuntimeCapabilityProfile,
    SchedulingBasisInputs,
    ExecutionSurfaceEligibility,
    build_runtime_capability_profile,
    build_scheduling_basis_inputs,
    evaluate_execution_surface_eligibility,
    normalize_scheduling_inputs,
)

# PR package 7 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): canonical persistent attached-runtime session semantics.  Re-exported
# here so callers can reach the attached-runtime session API from core.runtime
# without importing the module directly.
from core.attached_runtime_session import (  # noqa: E402
    ATTACHED_RUNTIME_SESSION_AUTHORITY,
    ATTACHED_SESSION_PERSISTS_ACROSS_REQUESTS_POLICY,
    TRANSIENT_PRESENCE_DISTINCT_FROM_ATTACHED_SESSION_POLICY,
    DETACH_SIGNAL_REQUIRED_FOR_SESSION_TERMINATION_POLICY,
    ATTACH_IS_IDEMPOTENT_POLICY,
    DISCONNECTED_DOES_NOT_INVALIDATE_SESSION_POLICY,
    INVALIDATED_SESSION_IS_TERMINAL_POLICY,
    DISABLED_SESSION_NOT_ELIGIBLE_FOR_EXECUTION_POLICY,
    ATTACHED_SESSION_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY,
    ATTACHMENT_LIFECYCLE_IS_POSTURE_AWARE_POLICY,
    ATTACHMENT_LIFECYCLE_ACTION_GOVERNANCE_POLICY,
    ATTACHED_RUNTIME_SESSION_PR7_SENTINEL,
    AttachmentState,
    AttachmentLifecycleSignal,
    AttachmentLifecycleAction,
    AttachedRuntimeSessionRecord,
    AttachedRuntimeSessionSnapshot,
    AttachedRuntimeSessionRuntime,
    attach_runtime_session,
    apply_lifecycle_signal,
    classify_attach_lifecycle_action,
    classify_signal_lifecycle_action,
    get_attached_runtime_session,
    list_active_attached_sessions,
    build_attached_runtime_session_snapshot,
    get_attached_runtime_session_runtime,
    reset_attached_runtime_session_runtime,
)

# PR package 8 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): canonical delegated-runtime dispatch intent and handoff-preparation
# foundations.
from core.delegated_runtime_dispatch_intent import (  # noqa: E402
    DELEGATED_RUNTIME_DISPATCH_INTENT_AUTHORITY,
    DELEGATION_REQUIRES_ATTACHED_SESSION_POLICY,
    DELEGATION_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY,
    OBSERVER_ONLY_ROLE_BLOCKS_DELEGATION_POLICY,
    TARGET_ONLY_EXECUTOR_CANNOT_DELEGATE_POLICY,
    COMMAND_ONLY_TIER_BLOCKS_FULL_DELEGATION_POLICY,
    HANDOFF_INPUTS_MUST_BE_SESSION_ANCHORED_POLICY,
    DELEGATION_INTENT_IS_ADDITIVE_TO_SESSION_POLICY,
    DISPATCH_RECORD_IS_IMMUTABLE_POLICY,
    PREPARATION_STATE_IS_MONOTONICALLY_ADVANCING_POLICY,
    DELEGATED_RUNTIME_DISPATCH_INTENT_PR8_SENTINEL,
    DelegationIntent,
    HandoffPreparationState,
    DelegatedRuntimeDispatchRecord,
    HandoffInputBundle,
    DispatchEligibilityOutcome,
    DelegatedRuntimeDispatchSnapshot,
    DelegatedRuntimeDispatchRuntime,
    build_delegated_dispatch_record,
    evaluate_dispatch_eligibility,
    prepare_handoff_inputs,
    record_delegated_dispatch_intent,
    get_delegated_dispatch_record,
    list_pending_delegated_dispatch_records,
    build_delegated_dispatch_snapshot,
    get_delegated_runtime_dispatch_runtime,
    reset_delegated_runtime_dispatch_runtime,
)

# PR package 9 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): canonical delegated-runtime handoff contract foundations.  Re-exported
# here so callers can reach the handoff-contract API from core.runtime without
# importing the module directly.
from core.delegated_runtime_handoff_contract import (  # noqa: E402
    DELEGATED_RUNTIME_HANDOFF_CONTRACT_AUTHORITY,
    HANDOFF_CONTRACT_REQUIRES_DISPATCH_RECORD_POLICY,
    HANDOFF_CONTRACT_REQUIRES_ATTACHED_SESSION_POLICY,
    HANDOFF_CONTRACT_VERSION_MUST_BE_EXPLICIT_POLICY,
    HANDOFF_CONTRACT_IDENTITY_IS_IMMUTABLE_POLICY,
    HANDOFF_CONTRACT_STATUS_IS_MONOTONIC_POLICY,
    HANDOFF_CONTRACT_POSTURE_IS_PRESERVED_POLICY,
    SEALED_CONTRACT_IS_DISPATCH_READY_POLICY,
    HANDOFF_CONTRACT_PAYLOAD_MUST_BE_NON_EMPTY_POLICY,
    HANDOFF_CONTRACT_TRACE_ID_IS_PROPAGATED_POLICY,
    DELEGATED_RUNTIME_HANDOFF_CONTRACT_PR9_SENTINEL,
    HandoffContractVersion,
    HandoffContractStatus,
    DelegatedHandoffContractIdentity,
    DelegatedHandoffContractMeta,
    DelegatedHandoffContractPayload,
    DelegatedHandoffContractRecord,
    DelegatedHandoffContractSnapshot,
    DelegatedHandoffContractRuntime,
    build_delegated_handoff_contract,
    seal_handoff_contract,
    record_handoff_contract,
    get_handoff_contract,
    list_pending_handoff_contracts,
    build_handoff_contract_snapshot,
    get_handoff_contract_runtime,
    reset_handoff_contract_runtime,
)

# PR package 10 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): canonical delegated-runtime execution-tracking and acknowledgment
# basis.  Re-exported here so callers can reach the execution-tracking API
# from core.runtime without importing the module directly.
from core.delegated_runtime_execution_tracker import (  # noqa: E402
    DELEGATED_RUNTIME_EXECUTION_TRACKER_AUTHORITY,
    EXECUTION_TRACKING_REQUIRES_CONTRACT_ID_POLICY,
    EXECUTION_TRACKING_REQUIRES_SESSION_ID_POLICY,
    EXECUTION_PHASE_IS_MONOTONIC_POLICY,
    ACK_SEQUENCE_IS_MONOTONICALLY_INCREASING_POLICY,
    RESULT_IS_IMMUTABLE_ONCE_RECORDED_POLICY,
    EXECUTION_TRACKING_POSTURE_IS_PROPAGATED_POLICY,
    TERMINAL_PHASE_BLOCKS_FURTHER_SIGNALS_POLICY,
    TRACKING_RECORD_IS_CONTRACT_ANCHORED_POLICY,
    PARTIAL_RESULT_DOES_NOT_CLOSE_TRACKING_POLICY,
    DELEGATED_RUNTIME_EXECUTION_TRACKER_PR10_SENTINEL,
    DelegatedExecutionPhase,
    AcknowledgmentSignal,
    DelegatedExecutionIdentity,
    DelegatedExecutionAcknowledgment,
    DelegatedExecutionResult,
    DelegatedExecutionTrackingRecord,
    DelegatedExecutionTrackingSnapshot,
    DelegatedExecutionTrackingRuntime,
    create_execution_tracking_record,
    apply_acknowledgment_signal,
    apply_result,
    record_execution_tracking,
    get_execution_tracking_record,
    list_active_execution_tracking_records,
    build_execution_tracking_snapshot,
    get_execution_tracking_runtime,
    reset_execution_tracking_runtime,
)

# PR package 11 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): canonical MAIN-side attached-Android-runtime dispatch binding basis.
# Re-exported here so callers can reach the dispatch-binding API from
# core.runtime without importing the module directly.
from core.android_runtime_dispatch_binding import (  # noqa: E402
    ANDROID_RUNTIME_DISPATCH_BINDING_AUTHORITY,
    BINDING_REQUIRES_ATTACHED_SESSION_POLICY,
    BINDING_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY,
    BINDING_REQUIRES_TARGET_DEVICE_ID_POLICY,
    BINDING_SESSION_ID_MUST_MATCH_CONTRACT_POLICY,
    BINDING_STATE_IS_MONOTONIC_POLICY,
    RELEASED_BINDING_IS_TERMINAL_POLICY,
    BINDING_CONTRACT_ID_IS_IMMUTABLE_POLICY,
    DISPATCH_BINDING_REQUIRES_CONTRACT_ID_POLICY,
    BINDING_TRACKER_ID_IS_PROPAGATED_POLICY,
    ANDROID_RUNTIME_DISPATCH_BINDING_PR11_SENTINEL,
    AndroidRuntimeBindingState,
    AndroidRuntimeBindingSignal,
    AndroidRuntimeDispatchBindingIdentity,
    AndroidRuntimeDispatchBindingRecord,
    AndroidRuntimeDispatchBindingSnapshot,
    AndroidRuntimeDispatchBindingRuntime,
    create_android_dispatch_binding,
    advance_binding_state,
    resolve_dispatch_binding,
    record_dispatch_binding,
    get_dispatch_binding,
    get_dispatch_binding_by_contract,
    list_bound_dispatch_bindings,
    build_dispatch_binding_snapshot,
    get_dispatch_binding_runtime,
    reset_dispatch_binding_runtime,
)

# PR package 13 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): canonical host-side Android execution signal reconciliation binding.
# Re-exported here so callers can reach the reconciler API from core.runtime
# without importing the module directly.
from core.android_execution_signal_reconciler import (  # noqa: E402
    ANDROID_EXECUTION_SIGNAL_RECONCILER_AUTHORITY,
    RECONCILER_REQUIRES_CONTRACT_ID_OR_SESSION_ID_POLICY,
    RECONCILER_SIGNAL_MAPPING_IS_CANONICAL_POLICY,
    RECONCILER_TERMINAL_RECORD_BLOCKS_FURTHER_SIGNALS_POLICY,
    RECONCILER_IDENTITY_IS_PRESERVED_ACROSS_RECONCILE_POLICY,
    RECONCILER_UNKNOWN_SIGNAL_DEFAULTS_TO_PROGRESS_POLICY,
    RECONCILER_TASK_STATUS_MAPS_TO_ACK_SIGNAL_CANONICALLY_POLICY,
    RECONCILER_ERROR_SIGNAL_CLOSES_TRACKING_RECORD_POLICY,
    RECONCILER_TIMEOUT_SIGNAL_CLOSES_TRACKING_RECORD_POLICY,
    RECONCILER_CANCELLED_SIGNAL_CLOSES_TRACKING_RECORD_POLICY,
    RECONCILER_RESULT_PAYLOAD_IS_FORWARDED_TO_TRACKER_POLICY,
    ANDROID_EXECUTION_SIGNAL_RECONCILER_PR13_SENTINEL,
    RECONCILER_PR22_SENTINEL,
    RECONCILER_REGISTRY_GATE_IS_AUTHORITATIVE_PR22_POLICY,
    RECONCILER_REGISTRY_BLOCKS_NON_ACTIVE_SESSION_PR22_POLICY,
    AndroidSignalKind,
    AndroidExecutionSignalEnvelope,
    AndroidSignalReconcileOutcome,
    normalize_android_message_to_signal_kind,
    extract_signal_envelope,
    reconcile_android_execution_signal,
    reconcile_inbound_message,
)

# PR package 14 (post-533 dual-repo runtime unification master plan, MAIN
# side): canonical persistent attached-runtime reuse binding.
# Re-exported here so callers can reach the reuse binding API from core.runtime
# without importing the module directly.
from core.attached_runtime_reuse_binding import (  # noqa: E402
    ATTACHED_RUNTIME_REUSE_BINDING_AUTHORITY,
    REUSE_BINDING_REQUIRES_ATTACHED_SESSION_POLICY,
    REUSE_BINDING_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY,
    REUSE_BINDING_REQUIRES_TARGET_DEVICE_ID_POLICY,
    REUSE_ELIGIBILITY_REQUIRES_ACTIVE_SESSION_POLICY,
    REUSE_BINDING_INVALIDATED_ON_DETACH_POLICY,
    REUSE_BINDING_INVALIDATED_ON_DISCONNECT_POLICY,
    REUSE_BINDING_INVALIDATED_ON_DISABLE_POLICY,
    REUSE_BINDING_DISPATCH_BINDING_ID_IS_LATEST_POLICY,
    REUSE_BINDING_IS_STABLE_TARGETING_SURFACE_POLICY,
    ATTACHED_RUNTIME_REUSE_BINDING_PR14_SENTINEL,
    ReuseEligibilityStatus,
    ReuseInvalidationReason,
    AttachedRuntimeReuseBindingIdentity,
    AttachedRuntimeReuseBindingRecord,
    AttachedRuntimeReuseBindingSnapshot,
    AttachedRuntimeReuseBindingRuntime,
    establish_reuse_binding,
    evaluate_reuse_eligibility,
    invalidate_reuse_binding,
    register_dispatch_binding_id,
    record_reuse_binding,
    get_reuse_binding,
    get_reuse_binding_by_device,
    list_eligible_reuse_bindings,
    build_reuse_binding_snapshot,
    get_reuse_binding_runtime,
    reset_reuse_binding_runtime,
)

# PR package 16 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): canonical ingress path for Android delegated execution signals.
# Re-exported here so callers can reach the ingress API from core.runtime
# without importing the module directly.
from core.android_delegated_signal_ingress import (  # noqa: E402
    ANDROID_DELEGATED_SIGNAL_INGRESS_AUTHORITY,
    INGRESS_DELEGATED_SIGNAL_TYPE_IS_CANONICAL_POLICY,
    INGRESS_SIGNAL_KIND_IS_EXPLICIT_FIELD_POLICY,
    INGRESS_RESULT_KIND_DISAMBIGUATES_RESULT_SIGNALS_POLICY,
    INGRESS_SIGNAL_ID_IS_PRESERVED_POLICY,
    INGRESS_EMISSION_SEQ_IS_PRESERVED_POLICY,
    INGRESS_IDENTITY_FIELDS_ARE_VERBATIM_POLICY,
    INGRESS_REQUIRES_LOOKUP_KEY_POLICY,
    INGRESS_DELEGATES_TO_RECONCILER_POLICY,
    INGRESS_TRACKER_PHASE_CONSISTENT_WITH_SIGNAL_KIND_POLICY,
    INGRESS_NON_DESTRUCTIVE_ON_MISS_POLICY,
    INGRESS_RECOVERY_GUARD_IS_MANDATORY_POLICY,
    INGRESS_GUARD_REJECTED_SIGNAL_IS_DROPPED_POLICY,
    ANDROID_DELEGATED_SIGNAL_INGRESS_PR16_SENTINEL,
    # PR-21: canonical path closure sentinels
    CANONICAL_PATH_IS_INGRESS_GUARD_RECONCILE_TRACKER_POLICY,
    IDENTITY_CONTINUITY_ACROSS_CANONICAL_PATH_POLICY,
    TERMINAL_STATE_IS_PROTECTED_AGAINST_REPLAY_POLICY,
    CANONICAL_DELEGATED_EXECUTION_PATH_CLOSED_PR21_SENTINEL,
    # PR-22: ingress registry consolidation sentinels
    INGRESS_REGISTRY_CONSOLIDATION_PR22_SENTINEL,
    INGRESS_REGISTRY_GATE_IS_AUTHORITATIVE_PR22_POLICY,
    INGRESS_REGISTRY_BLOCKS_NON_ACTIVE_SESSION_PR22_POLICY,
    DelegatedSignalKind,
    ResultKind,
    DelegatedExecutionSignalEnvelope,
    extract_delegated_signal_envelope,
    ingest_delegated_execution_signal,
)

# PR package 15 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): attached-runtime recovery readiness and inbound signal guard.
# Re-exported here so callers can reach the guard API from core.runtime
# without importing the module directly.
from core.attached_runtime_recovery_readiness import (  # noqa: E402
    ATTACHED_RUNTIME_RECOVERY_READINESS_AUTHORITY,
    GUARD_MUST_PRECEDE_RECONCILE_POLICY,
    DUPLICATE_SIGNAL_ID_IS_REJECTED_POLICY,
    REPLAY_AT_SAME_SEQ_IS_REJECTED_POLICY,
    STALE_EMISSION_SEQ_IS_REJECTED_POLICY,
    OUT_OF_ORDER_EMISSION_SEQ_IS_REJECTED_POLICY,
    ACCEPTED_SIGNAL_IS_RECORDED_POLICY,
    GUARD_DECISION_IS_OBSERVABLE_POLICY,
    RING_BUFFER_IS_BOUNDED_POLICY,
    IDEMPOTENCY_KEY_USES_SIGNAL_ID_AND_CONTEXT_POLICY,
    SEQ_INDEX_TRACKS_MAX_PER_CONTEXT_POLICY,
    REJECTED_SIGNAL_MUST_NOT_REACH_TRACKER_POLICY,
    ATTACHED_RUNTIME_RECOVERY_READINESS_PR15_SENTINEL,
    RECOVERY_READINESS_RING_BUFFER_SIZE,
    STALE_EMISSION_SEQ_THRESHOLD,
    SignalGuardDecision,
    RecoveryReadinessStatus,
    IdempotencyKey,
    SeenSignalRecord,
    SignalGuardOutcome,
    RecoveryReadinessSnapshot,
    RecoveryReadinessRuntime,
    build_idempotency_key,
    check_signal_guard,
    record_seen_signal,
    guard_inbound_signal,
    build_recovery_readiness_snapshot,
    get_recovery_readiness_runtime,
    reset_recovery_readiness_runtime,
)

# PR package 17 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): canonical dispatch consumption of attached-runtime reuse bindings.
# Re-exported here to provide a stable public API surface for reuse dispatch
# functionality so callers can import from core.runtime without depending on
# the module path directly.
from core.attached_runtime_reuse_dispatch import (  # noqa: E402
    ATTACHED_RUNTIME_REUSE_DISPATCH_AUTHORITY,
    REUSE_DISPATCH_LOOKUP_PRECEDES_DISPATCH_POLICY,
    REUSE_DISPATCH_ELIGIBILITY_GATE_IS_MANDATORY_POLICY,
    REUSE_DISPATCH_ELIGIBLE_SURFACE_IS_REUSED_POLICY,
    REUSE_DISPATCH_INELIGIBLE_BINDING_IS_REJECTED_POLICY,
    REUSE_DISPATCH_NO_BINDING_ALLOWS_NEW_DISPATCH_POLICY,
    REUSE_DISPATCH_WRITE_BACK_IS_MANDATORY_POLICY,
    REUSE_DISPATCH_INVALIDATION_HARD_STOP_POLICY,
    REUSE_DISPATCH_SESSION_LOOKUP_PRECEDES_DEVICE_LOOKUP_POLICY,
    REUSE_DISPATCH_LIVE_SESSION_CROSS_CHECK_IS_OPTIONAL_POLICY,
    REUSE_DISPATCH_RESOLUTION_IS_IMMUTABLE_POLICY,
    REUSE_DISPATCH_DETACH_TRIGGERS_INELIGIBLE_RESOLUTION_POLICY,
    ATTACHED_RUNTIME_REUSE_DISPATCH_PR17_SENTINEL,
    ReuseDispatchResolutionKind,
    ReuseDispatchResolution,
    resolve_reuse_dispatch_surface,
    write_back_dispatch_binding_id,
    dispatch_with_reuse_binding,
    REUSE_DISPATCH_PR22_SENTINEL,
    REUSE_DISPATCH_REGISTRY_GATE_IS_AUTHORITATIVE_PR22_POLICY,
    REUSE_DISPATCH_REGISTRY_BLOCKS_NON_ACTIVE_SESSION_PR22_POLICY,
    # PR-23: canonical takeover dispatch / delegated fallback
    REUSE_DISPATCH_PR23_SENTINEL,
    TAKEOVER_DISPATCH_CONSULTS_REGISTRY_FIRST_PR23_POLICY,
    DELEGATED_FALLBACK_REQUIRES_INELIGIBLE_CANONICAL_PATH_PR23_POLICY,
    TAKEOVER_DISPATCH_DECISION_IS_DETERMINISTIC_PR23_POLICY,
    REPLACED_SESSION_CANNOT_WIN_TAKEOVER_DISPATCH_PR23_POLICY,
    STALE_EXECUTION_CONTEXT_CANNOT_ALTER_TAKEOVER_DECISION_PR23_POLICY,
    TakeoverRouteOutcome,
    TakeoverDispatchDecision,
    resolve_takeover_or_fallback_route,
)
from core.attached_runtime_session_registry import (  # noqa: E402
    ATTACHED_RUNTIME_SESSION_REGISTRY_AUTHORITY,
    REGISTRY_IS_SINGLE_TRUTH_SOURCE_POLICY,
    REGISTRY_DEVICE_HAS_AT_MOST_ONE_ACTIVE_SESSION_POLICY,
    REGISTRY_REGISTER_REPLACES_OLD_SESSION_POLICY,
    REGISTRY_RECONNECT_PRESERVES_RUNTIME_SESSION_ID_POLICY,
    REGISTRY_DETACH_REQUIRES_EXPLICIT_SIGNAL_POLICY,
    REGISTRY_INVALIDATED_ENTRY_IS_TERMINAL_POLICY,
    REGISTRY_DISPATCH_MUST_CONSULT_REGISTRY_POLICY,
    REGISTRY_REUSE_MUST_CONSULT_REGISTRY_POLICY,
    REGISTRY_RECONCILIATION_MUST_CONSULT_REGISTRY_POLICY,
    REGISTRY_LOOKUP_RETURNS_ACTIVE_ONLY_BY_DEFAULT_POLICY,
    ATTACHED_RUNTIME_SESSION_REGISTRY_PR19_SENTINEL,
    RegistryEntryState,
    RegistryTransition,
    InvalidationReason,
    AttachedSessionRegistryEntry,
    AttachedSessionRegistrySnapshot,
    AttachedSessionRegistry,
    register_session,
    reconnect_session,
    reattach_session,
    detach_session,
    invalidate_session,
    lookup_active_session,
    lookup_session_by_device,
    list_active_sessions,
    build_registry_snapshot,
    get_session_registry,
    reset_session_registry,
    ATTACHED_RUNTIME_REGISTRY_CONSOLIDATION_PR22_SENTINEL,
    REGISTRY_IS_AUTHORITATIVE_DISPATCH_GATE_PR22_POLICY,
    REGISTRY_IS_AUTHORITATIVE_REUSE_GATE_PR22_POLICY,
    REGISTRY_IS_AUTHORITATIVE_RECONCILIATION_GATE_PR22_POLICY,
    REGISTRY_KNOWN_NON_ACTIVE_BLOCKS_EXECUTION_PR22_POLICY,
    REGISTRY_ABSENT_ENTRY_PASSES_THROUGH_PR22_POLICY,
    # PR-23: canonical takeover dispatch authority sentinels
    ATTACHED_RUNTIME_REGISTRY_TAKEOVER_DISPATCH_PR23_SENTINEL,
    REGISTRY_IS_CANONICAL_TAKEOVER_DISPATCH_AUTHORITY_PR23_POLICY,
    REGISTRY_TAKEOVER_ELIGIBILITY_REQUIRES_ACTIVE_STATE_PR23_POLICY,
    REGISTRY_REPLACED_SESSION_IS_INELIGIBLE_FOR_TAKEOVER_PR23_POLICY,
)

# PR package 20 (post-533 dual-repo runtime unification master plan, MAIN repo
# side): canonical delegated target selection policy layer.
from core.delegated_target_selection_policy import (  # noqa: E402
    DELEGATED_TARGET_SELECTION_POLICY_AUTHORITY,
    SELECTION_MUST_CONSULT_REGISTRY_POLICY,
    SELECTION_REQUIRES_ACTIVE_ATTACHMENT_STATE_POLICY,
    SELECTION_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY,
    SELECTION_REQUIRES_NO_INVALIDATION_REASON_POLICY,
    SELECTION_REUSE_VALID_IS_PREFERRED_POLICY,
    SELECTION_HIGH_FAILURE_COUNT_DEMOTES_CANDIDATE_POLICY,
    SELECTION_HIGH_DETACH_COUNT_DEMOTES_CANDIDATE_POLICY,
    SELECTION_NO_VALID_CANDIDATE_TRIGGERS_LOCAL_FALLBACK_POLICY,
    SELECTION_HIGH_RISK_CANDIDATE_MAY_DEGRADE_POLICY,
    SELECTION_DECISION_IS_EXPLAINABLE_POLICY,
    SELECTION_RANKING_IS_DETERMINISTIC_POLICY,
    DELEGATED_TARGET_SELECTION_POLICY_PR20_SENTINEL,
    DEGRADATION_SCORE_THRESHOLD,
    BASE_CANDIDATE_SCORE,
    REUSE_VALID_BONUS,
    FAILURE_COUNT_PENALTY_PER_UNIT,
    FAILURE_COUNT_MAX_PENALTY,
    DETACH_COUNT_PENALTY_PER_UNIT,
    DETACH_COUNT_MAX_PENALTY,
    LOAD_PENALTY_PER_10_EXECUTIONS,
    LOAD_MAX_PENALTY,
    SelectionOutcome,
    CandidateRejectionReason,
    SelectionCandidateContext,
    CandidateEvaluation,
    SelectionDecision,
    evaluate_candidate,
    rank_candidates,
    select_delegated_target,
    build_selection_explanation,
)

# PR-6 (center-side): WebRTC Task-Lifecycle Integration.
# Re-exported here so callers can reach the WebRTC task-lifecycle API from
# core.runtime without importing the module directly.
from core.webrtc_task_lifecycle import (  # noqa: E402
    WEBRTC_TASK_LIFECYCLE_AUTHORITY,
    WEBRTC_SESSION_MUST_BE_TASK_SCOPED_POLICY,
    TRANSPORT_STATE_DRIVES_LIFECYCLE_ACTION_POLICY,
    TERMINAL_TASK_TRIGGERS_SESSION_TEARDOWN_POLICY,
    DEGRADED_TRANSPORT_YIELDS_DEGRADED_TASK_POLICY,
    FAILED_TRANSPORT_YIELDS_FAILED_TASK_POLICY,
    RECONNECTED_TRANSPORT_RESUMES_RUNNING_TASK_POLICY,
    BINDING_IS_TASK_SCOPED_SINGLE_SESSION_POLICY,
    TEARDOWN_IS_IDEMPOTENT_POLICY,
    SESSION_BINDING_RECORD_IS_IMMUTABLE_POLICY,
    WEBRTC_TASK_LIFECYCLE_PR6_SENTINEL,
    WebRTCTransportState,
    WebRTCTaskLifecycleAction,
    WebRTCTaskBinding,
    WebRTCTaskBindingSnapshot,
    WebRTCTaskSessionRegistry,
    bind_webrtc_session_to_task,
    classify_transport_lifecycle_action,
    apply_transport_state_to_task_lifecycle,
    teardown_binding_on_task_terminal,
    get_webrtc_task_binding,
    list_active_webrtc_task_bindings,
    build_webrtc_task_binding_snapshot,
    get_webrtc_task_session_registry,
    reset_webrtc_task_session_registry,
)

# PR-4V2: Android Participant/Session/Runtime Truth Ingress and Canonical
# Reconciliation into V2 Orchestration State.
# Re-exported here so callers can reach the Android participant truth ingress
# API from core.runtime without importing the module directly.
from core.android_participant_truth_ingress import (  # noqa: E402
    ANDROID_PARTICIPANT_TRUTH_INGRESS_AUTHORITY,
    V2_IS_CANONICAL_ORCHESTRATION_AUTHORITY_SENTINEL,
    ANDROID_PARTICIPANT_TRUTH_INGRESS_PR4V2_SENTINEL,
    V2_IS_CANONICAL_ORCHESTRATION_AUTHORITY_POLICY,
    ANDROID_TRUTH_IS_ADVISORY_FOR_DEVICE_SCOPE_POLICY,
    CANCEL_FAILURE_RESULT_AFFECT_CANONICAL_STATE_POLICY,
    STATUS_SIGNAL_EMITS_PROGRESS_EVENT_POLICY,
    TASK_PHASE_RECONCILED_WITH_TRACKING_RECORD_POLICY,
    SESSION_SNAPSHOT_VALIDATES_REGISTRY_CONTINUITY_POLICY,
    READINESS_ASSESSMENT_IS_ADVISORY_POLICY,
    RUNTIME_STATE_IS_AUDIT_ONLY_POLICY,
    TERMINAL_V2_STATE_WINS_CONFLICT_POLICY,
    RECONCILE_IS_NON_DESTRUCTIVE_ON_MISS_POLICY,
    RECONCILE_EMITS_AUDIT_EVENT_ALWAYS_POLICY,
    IDENTITY_FIELDS_ARE_VERBATIM_POLICY,
    AndroidParticipantTruthKind,
    AndroidParticipantTruthEnvelope,
    AndroidParticipantReconcileOutcome,
    extract_participant_truth_envelope,
    reconcile_android_participant_truth,
    ingest_android_participant_truth_message,
)

__all__ = [
    # PR-34: Target Runtime Local Takeover Path
    "TargetTakeoverHandler",
    "adopt_handoff_session",
    "build_local_takeover_context",
    "resolve_or_create_runtime_session",
    "normalize_handoff_envelope",
    "execute_local_takeover",
    # PR-35: Source Runtime Dispatch Orchestrator
    "SourceDispatchOrchestrator",
    "select_dispatch_mode",
    "select_dispatch_target",
    "build_source_dispatch_plan",
    "orchestrate_source_runtime_dispatch",
    # PR-24: Dispatch Selection Truth Consolidation
    "DISPATCH_SELECTION_TRUTH_CONSOLIDATED_PR24_SENTINEL",
    "SELECTION_READINESS_IS_REQUIRED_TRUTH_PR24_POLICY",
    "SELECTION_PARTICIPATION_IS_REQUIRED_TRUTH_PR24_POLICY",
    "SELECTION_REGISTRY_IS_CANONICAL_GATE_PR24_POLICY",
    "SELECTION_REUSE_CONTRIBUTES_PREFERENCE_PR24_POLICY",
    "SELECTION_FALLBACK_IS_STABLE_AND_EXPLAINABLE_PR24_POLICY",
    # PR-25: Mainline Abnormal-Path Matrix + Phase A Acceptance
    "MAINLINE_ABNORMAL_PATH_MATRIX_CLOSED_PR25_SENTINEL",
    "REMOTE_TASK_BLOCKS_LOCAL_LOOP_ABNORMAL_PATH_PR25_POLICY",
    "LOCAL_FALLBACK_AFTER_REMOTE_FAILURE_ABNORMAL_PATH_PR25_POLICY",
    "DELEGATED_EXECUTION_FAILURE_SESSION_TRUTH_IS_PRESERVED_PR25_POLICY",
    "SELECTION_FALLBACK_UNDER_DEGRADED_CONDITIONS_IS_STABLE_PR25_POLICY",
    "PHASE_A_ACCEPTANCE_ABNORMAL_PATH_PR25_POLICY",
    # PR-26: Client-Facing Result Surfacing Normalization
    "CLIENT_FACING_RESULT_SURFACING_NORMALIZED_PR26_SENTINEL",
    "RESULT_CONTRACT_IS_INVARIANT_ACROSS_DISPATCH_PATHS_PR26_POLICY",
    "RESULT_SEMANTICS_ARE_COHERENT_REGARDLESS_OF_PATH_PR26_POLICY",
    "RESULT_IDENTITY_IS_STABLE_ACROSS_EXECUTION_PATHS_PR26_POLICY",
    "NO_PATH_SPECIFIC_RESULT_CONTRACT_DRIFT_PR26_POLICY",
    # PR-27: Gateway-Facing Registration and Capability Error Semantics Hardening
    "GATEWAY_FACING_REGISTRATION_CAPABILITY_ERROR_SEMANTICS_HARDENED_PR27_SENTINEL",
    "REGISTRATION_FAILURE_IS_DISTINGUISHABLE_FROM_CAPABILITY_FAILURE_PR27_POLICY",
    "READINESS_DEGRADED_BEHAVIOR_IS_REPORTED_THROUGH_STABLE_SIGNALS_PR27_POLICY",
    "CAPABILITY_NOT_SATISFIED_FAILURE_IS_ACTIONABLE_PR27_POLICY",
    "GATEWAY_SETUP_CONNECTION_SIGNALS_ARE_DETERMINISTIC_PR27_POLICY",
    # PR-28: Integrated Regression Closure and Release-Readiness Tightening
    "INTEGRATED_REGRESSION_CLOSURE_RELEASE_READINESS_PR28_SENTINEL",
    "END_TO_END_DISPATCH_EXECUTION_RESULT_COHERENCE_PR28_POLICY",
    "INTEGRATED_SELECTION_REGISTRY_REUSE_FALLBACK_BEHAVIOR_PR28_POLICY",
    "REGISTRATION_CAPABILITY_READINESS_UNDER_INTEGRATED_SCENARIOS_PR28_POLICY",
    "REGRESSION_STABILIZATION_RELEASE_READINESS_TIGHTENING_PR28_POLICY",
    # PR-29: Post-Release Follow-Up Tightening Across Dispatch and Client Semantics
    "POST_RELEASE_DISPATCH_CLIENT_SEMANTICS_TIGHTENING_PR29_SENTINEL",
    "DISPATCH_SELECTION_COHESION_POST_RELEASE_PR29_POLICY",
    "REGISTRATION_READINESS_CAPABILITY_STABILITY_POST_RELEASE_PR29_POLICY",
    "DELEGATED_EXECUTION_FALLBACK_SEMANTIC_CONSISTENCY_PR29_POLICY",
    "CLIENT_GATEWAY_RESULT_CONTRACT_ALIGNMENT_POST_RELEASE_PR29_POLICY",
    # PR-30: Observability and Diagnostics Hardening for Rollout Safety
    "OBSERVABILITY_DIAGNOSTICS_ROLLOUT_SAFETY_HARDENING_PR30_SENTINEL",
    "DISPATCH_PATH_DECISION_OBSERVABILITY_PR30_POLICY",
    "REGISTRATION_READINESS_CAPABILITY_FALLBACK_DIAGNOSTICS_PR30_POLICY",
    "DELEGATED_EXECUTION_OBSERVABILITY_PR30_POLICY",
    "ROLLOUT_SAFETY_SIGNALS_CLIENT_RESULT_OBSERVABILITY_PR30_POLICY",
    # PR-31: rollout controls, default behaviors, and safe-operating release toggles
    "ROLLOUT_CONTROLS_DEFAULT_BEHAVIORS_SAFE_RELEASE_PR31_SENTINEL",
    "FEATURE_TOGGLE_DEFAULT_BEHAVIOR_ROLLOUT_CONTROL_PR31_POLICY",
    "KILL_SWITCH_SAFE_DISABLE_ROLLBACK_BEHAVIOR_PR31_POLICY",
    "SELECTION_REGISTRATION_READINESS_CAPABILITY_SAFE_DEFAULTS_PR31_POLICY",
    "DELEGATED_FALLBACK_RELEASE_OPERATION_CONSISTENCY_PR31_POLICY",
    # PR-32: staged mesh minimal executable closure
    "STAGED_MESH_MINIMAL_EXECUTABLE_CLOSURE_PR32_SENTINEL",
    "STAGED_MESH_PLAN_TO_EXECUTION_TRANSITION_PR32_POLICY",
    "STAGED_MESH_SESSION_COORDINATOR_INTEGRATION_PR32_POLICY",
    "STAGED_MESH_RESULT_INTEGRATION_CONTRACT_PR32_POLICY",
    "STAGED_MESH_GRACEFUL_DEGRADATION_FALLBACK_PR32_POLICY",
    # PR-J: live mesh runtime engine
    "LIVE_MESH_RUNTIME_ENGINE_ORCHESTRATOR_PR_J_SENTINEL",
    "LIVE_MESH_STAGED_TO_ACTIVE_DISPATCH_PR_J_POLICY",
    "LIVE_MESH_RESULT_CONVERGENCE_PR_J_POLICY",
    # PR-33: reconnect and recovery consistency hardening
    "RECONNECT_RECOVERY_CONSISTENCY_PR33_SENTINEL",
    "RECONNECT_MUST_NOT_BREAK_HOST_SIDE_TRUTH_PR33_POLICY",
    "REGISTRY_RECONNECT_EVENT_IS_OBSERVABLE_PR33_POLICY",
    "EXECUTION_TRACKER_SURVIVES_RECONNECT_PR33_POLICY",
    "RESULT_MERGE_CONSISTENT_THROUGH_RECOVERY_PR33_POLICY",
    # PR-34: final product-grade cross-device and runtime acceptance pack
    "CROSS_DEVICE_RUNTIME_ACCEPTANCE_PR34_SENTINEL",
    "DISPATCH_FALLBACK_RESULT_MERGE_STABILITY_PR34_POLICY",
    "ANDROID_ATTACHED_RUNTIME_ORCHESTRATION_STABILITY_PR34_POLICY",
    "MULTI_TARGET_RANKING_MATURITY_PR34_POLICY",
    "STAGED_MESH_CLOSURE_RUNNABLE_PR34_POLICY",
    "DIAGNOSTICS_READINESS_PARTICIPATION_FORMATION_USABILITY_PR34_POLICY",
    # PR-closure: Android terminal signal → canonical ReplayFoundation truth
    "ANDROID_TERMINAL_SIGNAL_RECORDED_TO_CANONICAL_TRUTH_SENTINEL",
    "ANDROID_TERMINAL_SIGNAL_RECORDS_TO_REPLAY_FOUNDATION_POLICY",
    # PR-36: Cross-Runtime Result Merge Contract
    "RuntimeResultRole",
    "RuntimeResultStatus",
    "ResultMergePolicy",
    "RuntimeResultUnit",
    "MergedRuntimeResult",
    "ResultMergeSummary",
    "merge_unit_from_takeover_result",
    "merge_unit_from_dispatch_result",
    "merge_unit_from_execution_output",
    "build_merged_runtime_result",
    "merge_runtime_results",
    "build_result_merge_summary",
    # PR-37: Mesh Session Coordinator
    "MeshSessionCoordinator",
    "coordinate_mesh_session",
    "get_coordinator_summary",
    # PR-J: live mesh runtime execution helpers
    "run_live_mesh_session",
    "register_participant",
    "update_participant_status",
    "drop_participant",
    "MESH_SESSION_COORDINATOR_LIVE_RUNTIME_ENGINE_PR_J_SENTINEL",
    # PR-J: live mesh session coordinator (incremental event-driven)
    "LiveMeshSessionCoordinator",
    "create_live_mesh_session_coordinator",
    "LIVE_MESH_SESSION_COORDINATOR_PR_J_SENTINEL",
    "INCREMENTAL_PARTICIPANT_EVENTS_PR_J_POLICY",
    "BARRIER_TRACKS_ACROSS_EVENTS_PR_J_POLICY",
    "COORDINATOR_FINALIZE_PRODUCES_STABLE_RESULT_PR_J_POLICY",
    "PARTICIPANT_DROPOUT_AFFECTS_OUTCOME_PR_J_POLICY",
    # PR-2: Posture-Aware Source Execution Eligibility
    "SOURCE_DISPATCH_POSTURE_AWARE_AUTHORITY",
    "CONTROL_ONLY_SOURCE_INELIGIBLE_FOR_LOCAL_EXECUTION_POLICY",
    "JOIN_RUNTIME_SOURCE_ELIGIBLE_FOR_LOCAL_EXECUTION_POLICY",
    "POSTURE_GATED_LOCAL_EXECUTION_POLICY",
    "POSTURE_AWARE_DISPATCH_INTEGRATED_SENTINEL",
    # PR-2 coordination-role alignment
    "OBSERVER_ONLY_ROLE_BLOCKS_EXECUTION_POLICY",
    "COORDINATION_ROLE_ALIGNED_DISPATCH_SENTINEL",
    "check_source_eligibility_with_coordination_role",
    "SourceExecutionEligibility",
    "check_source_execution_eligibility",
    "is_source_eligible_for_local_execution",
    "resolve_posture_for_eligibility",
    # PR-4: Canonical Runtime Session Truth and Result Merge
    "CANONICAL_SESSION_TRUTH_AUTHORITY",
    "CONTROL_ONLY_EXCLUDED_FROM_MERGE_POLICY",
    "POSTURE_AWARE_RESULT_FILTER_POLICY",
    "JOIN_RUNTIME_INCLUDED_IN_MERGE_POLICY",
    "OBSERVER_ONLY_ROLE_EXCLUDED_FROM_MERGE_POLICY",
    "CANONICAL_SESSION_TRUTH_PR4_SENTINEL",
    "SessionTruthSource",
    "CanonicalSessionTruthRecord",
    "CanonicalSessionTruthRuntime",
    "CanonicalSessionTruthSnapshot",
    "filter_result_units_by_posture",
    "merge_session_truth",
    "record_session_truth",
    "build_canonical_session_truth_snapshot",
    "get_canonical_session_truth_runtime",
    "reset_canonical_session_truth_runtime",
    # PR package 1: Posture Contract Canonicalization (MAIN repo side)
    "POSTURE_CONTRACT_CANONICALIZATION_AUTHORITY",
    "POSTURE_BOUNDARY_NO_ENTRY_MODE_CONFLATION_POLICY",
    "POSTURE_BOUNDARY_NO_CROSS_DEVICE_FLAG_CONFLATION_POLICY",
    "POSTURE_BOUNDARY_NO_FORMATION_ROLE_CONFLATION_POLICY",
    "POSTURE_CONTRACT_PR_PACKAGE_1_SENTINEL",
    "PostureBoundaryViolation",
    "canonicalize_posture_in_payload",
    "validate_posture_field_consistency",
    "assert_posture_boundary_compliance",
    "get_posture_from_payload",
    # PR-6: Multi-Device Coordination Authority and Role Modelling
    "MULTI_DEVICE_COORDINATION_AUTHORITY",
    "MULTI_DEVICE_COORDINATION_AUTHORITY_PR6_SENTINEL",
    "SOURCE_CONTROLLER_OWNS_RUNTIME_AUTHORITY_POLICY",
    "TARGET_ONLY_EXECUTOR_HAS_NO_CONTROL_AUTHORITY_POLICY",
    "OBSERVER_ONLY_HAS_NO_EXECUTION_AUTHORITY_POLICY",
    "COORDINATION_ROLE_DERIVATION_IS_POSTURE_DRIVEN_POLICY",
    "CoordinationRole",
    "CoordinationRoleRecord",
    "CoordinationRoleSnapshot",
    "CoordinationRoleRuntime",
    "derive_coordination_role",
    "build_coordination_role_record",
    "build_coordination_role_snapshot",
    "record_coordination_role",
    "get_coordination_role_runtime",
    "reset_coordination_role_runtime",
    "get_source_controller_device_id",
    # PR-5: Android First-Class Runtime Host (MAIN repo side)
    "ANDROID_FIRST_CLASS_RUNTIME_HOST_PR5_SENTINEL",
    "ANDROID_RUNTIME_HOST_DISTINCT_FROM_CONNECTED_DEVICE_PR5",
    "ANDROID_RUNTIME_HOST_POSTURE_PRESERVED_PR5",
    "AndroidRuntimeHostRole",
    "AndroidRuntimeHostIdentity",
    "classify_android_runtime_host",
    "build_android_runtime_host_identity",
    # PR package 6: Canonical Capability & Scheduling Basis (MAIN repo side)
    "CANONICAL_CAPABILITY_SCHEDULING_BASIS_AUTHORITY",
    "FULL_RUNTIME_TIER_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY",
    "COMMAND_ONLY_TIER_BLOCKS_EXECUTION_PLACEMENT_POLICY",
    "CAPABILITY_TIER_DRIVES_SURFACE_ELIGIBILITY_POLICY",
    "OBSERVER_ONLY_ROLE_EXCLUDED_FROM_SCHEDULING_POLICY",
    "ANDROID_HOST_CAPABILITY_LIFTED_FROM_PR5_POLICY",
    "SCHEDULING_BASIS_NORMALISATION_IS_ADDITIVE_POLICY",
    "CANONICAL_CAPABILITY_SCHEDULING_BASIS_PR6_SENTINEL",
    "CapabilityTier",
    "ExecutionSurface",
    "RuntimeCapabilityProfile",
    "SchedulingBasisInputs",
    "ExecutionSurfaceEligibility",
    "build_runtime_capability_profile",
    "build_scheduling_basis_inputs",
    "evaluate_execution_surface_eligibility",
    "normalize_scheduling_inputs",
    # PR package 7: Canonical Persistent Attached-Runtime Session Semantics (MAIN repo side)
    "ATTACHED_RUNTIME_SESSION_AUTHORITY",
    "ATTACHED_SESSION_PERSISTS_ACROSS_REQUESTS_POLICY",
    "TRANSIENT_PRESENCE_DISTINCT_FROM_ATTACHED_SESSION_POLICY",
    "DETACH_SIGNAL_REQUIRED_FOR_SESSION_TERMINATION_POLICY",
    "ATTACH_IS_IDEMPOTENT_POLICY",
    "DISCONNECTED_DOES_NOT_INVALIDATE_SESSION_POLICY",
    "INVALIDATED_SESSION_IS_TERMINAL_POLICY",
    "DISABLED_SESSION_NOT_ELIGIBLE_FOR_EXECUTION_POLICY",
    "ATTACHED_SESSION_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY",
    "ATTACHMENT_LIFECYCLE_IS_POSTURE_AWARE_POLICY",
    "ATTACHMENT_LIFECYCLE_ACTION_GOVERNANCE_POLICY",
    "ATTACHED_RUNTIME_SESSION_PR7_SENTINEL",
    "AttachmentState",
    "AttachmentLifecycleSignal",
    "AttachmentLifecycleAction",
    "AttachedRuntimeSessionRecord",
    "AttachedRuntimeSessionSnapshot",
    "AttachedRuntimeSessionRuntime",
    "attach_runtime_session",
    "apply_lifecycle_signal",
    "classify_attach_lifecycle_action",
    "classify_signal_lifecycle_action",
    "get_attached_runtime_session",
    "list_active_attached_sessions",
    "build_attached_runtime_session_snapshot",
    "get_attached_runtime_session_runtime",
    "reset_attached_runtime_session_runtime",
    # PR package 8: Canonical Delegated-Runtime Dispatch Intent and Handoff-Preparation (MAIN repo side)
    "DELEGATED_RUNTIME_DISPATCH_INTENT_AUTHORITY",
    "DELEGATION_REQUIRES_ATTACHED_SESSION_POLICY",
    "DELEGATION_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY",
    "OBSERVER_ONLY_ROLE_BLOCKS_DELEGATION_POLICY",
    "TARGET_ONLY_EXECUTOR_CANNOT_DELEGATE_POLICY",
    "COMMAND_ONLY_TIER_BLOCKS_FULL_DELEGATION_POLICY",
    "HANDOFF_INPUTS_MUST_BE_SESSION_ANCHORED_POLICY",
    "DELEGATION_INTENT_IS_ADDITIVE_TO_SESSION_POLICY",
    "DISPATCH_RECORD_IS_IMMUTABLE_POLICY",
    "PREPARATION_STATE_IS_MONOTONICALLY_ADVANCING_POLICY",
    "DELEGATED_RUNTIME_DISPATCH_INTENT_PR8_SENTINEL",
    "DelegationIntent",
    "HandoffPreparationState",
    "DelegatedRuntimeDispatchRecord",
    "HandoffInputBundle",
    "DispatchEligibilityOutcome",
    "DelegatedRuntimeDispatchSnapshot",
    "DelegatedRuntimeDispatchRuntime",
    "build_delegated_dispatch_record",
    "evaluate_dispatch_eligibility",
    "prepare_handoff_inputs",
    "record_delegated_dispatch_intent",
    "get_delegated_dispatch_record",
    "list_pending_delegated_dispatch_records",
    "build_delegated_dispatch_snapshot",
    "get_delegated_runtime_dispatch_runtime",
    "reset_delegated_runtime_dispatch_runtime",
    # PR package 9: Canonical Delegated-Runtime Handoff Contract Foundations (MAIN repo side)
    "DELEGATED_RUNTIME_HANDOFF_CONTRACT_AUTHORITY",
    "HANDOFF_CONTRACT_REQUIRES_DISPATCH_RECORD_POLICY",
    "HANDOFF_CONTRACT_REQUIRES_ATTACHED_SESSION_POLICY",
    "HANDOFF_CONTRACT_VERSION_MUST_BE_EXPLICIT_POLICY",
    "HANDOFF_CONTRACT_IDENTITY_IS_IMMUTABLE_POLICY",
    "HANDOFF_CONTRACT_STATUS_IS_MONOTONIC_POLICY",
    "HANDOFF_CONTRACT_POSTURE_IS_PRESERVED_POLICY",
    "SEALED_CONTRACT_IS_DISPATCH_READY_POLICY",
    "HANDOFF_CONTRACT_PAYLOAD_MUST_BE_NON_EMPTY_POLICY",
    "HANDOFF_CONTRACT_TRACE_ID_IS_PROPAGATED_POLICY",
    "DELEGATED_RUNTIME_HANDOFF_CONTRACT_PR9_SENTINEL",
    "HandoffContractVersion",
    "HandoffContractStatus",
    "DelegatedHandoffContractIdentity",
    "DelegatedHandoffContractMeta",
    "DelegatedHandoffContractPayload",
    "DelegatedHandoffContractRecord",
    "DelegatedHandoffContractSnapshot",
    "DelegatedHandoffContractRuntime",
    "build_delegated_handoff_contract",
    "seal_handoff_contract",
    "record_handoff_contract",
    "get_handoff_contract",
    "list_pending_handoff_contracts",
    "build_handoff_contract_snapshot",
    "get_handoff_contract_runtime",
    "reset_handoff_contract_runtime",
    # PR package 10: Canonical Delegated-Runtime Execution-Tracking and Acknowledgment Basis (MAIN repo side)
    "DELEGATED_RUNTIME_EXECUTION_TRACKER_AUTHORITY",
    "EXECUTION_TRACKING_REQUIRES_CONTRACT_ID_POLICY",
    "EXECUTION_TRACKING_REQUIRES_SESSION_ID_POLICY",
    "EXECUTION_PHASE_IS_MONOTONIC_POLICY",
    "ACK_SEQUENCE_IS_MONOTONICALLY_INCREASING_POLICY",
    "RESULT_IS_IMMUTABLE_ONCE_RECORDED_POLICY",
    "EXECUTION_TRACKING_POSTURE_IS_PROPAGATED_POLICY",
    "TERMINAL_PHASE_BLOCKS_FURTHER_SIGNALS_POLICY",
    "TRACKING_RECORD_IS_CONTRACT_ANCHORED_POLICY",
    "PARTIAL_RESULT_DOES_NOT_CLOSE_TRACKING_POLICY",
    "DELEGATED_RUNTIME_EXECUTION_TRACKER_PR10_SENTINEL",
    "DelegatedExecutionPhase",
    "AcknowledgmentSignal",
    "DelegatedExecutionIdentity",
    "DelegatedExecutionAcknowledgment",
    "DelegatedExecutionResult",
    "DelegatedExecutionTrackingRecord",
    "DelegatedExecutionTrackingSnapshot",
    "DelegatedExecutionTrackingRuntime",
    "create_execution_tracking_record",
    "apply_acknowledgment_signal",
    "apply_result",
    "record_execution_tracking",
    "get_execution_tracking_record",
    "list_active_execution_tracking_records",
    "build_execution_tracking_snapshot",
    "get_execution_tracking_runtime",
    "reset_execution_tracking_runtime",
    # PR package 11: Canonical MAIN-Side Attached-Android-Runtime Dispatch Binding Basis (MAIN repo side)
    "ANDROID_RUNTIME_DISPATCH_BINDING_AUTHORITY",
    "BINDING_REQUIRES_ATTACHED_SESSION_POLICY",
    "BINDING_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY",
    "BINDING_REQUIRES_TARGET_DEVICE_ID_POLICY",
    "BINDING_SESSION_ID_MUST_MATCH_CONTRACT_POLICY",
    "BINDING_STATE_IS_MONOTONIC_POLICY",
    "RELEASED_BINDING_IS_TERMINAL_POLICY",
    "BINDING_CONTRACT_ID_IS_IMMUTABLE_POLICY",
    "DISPATCH_BINDING_REQUIRES_CONTRACT_ID_POLICY",
    "BINDING_TRACKER_ID_IS_PROPAGATED_POLICY",
    "ANDROID_RUNTIME_DISPATCH_BINDING_PR11_SENTINEL",
    "AndroidRuntimeBindingState",
    "AndroidRuntimeBindingSignal",
    "AndroidRuntimeDispatchBindingIdentity",
    "AndroidRuntimeDispatchBindingRecord",
    "AndroidRuntimeDispatchBindingSnapshot",
    "AndroidRuntimeDispatchBindingRuntime",
    "create_android_dispatch_binding",
    "advance_binding_state",
    "resolve_dispatch_binding",
    "record_dispatch_binding",
    "get_dispatch_binding",
    "get_dispatch_binding_by_contract",
    "list_bound_dispatch_bindings",
    "build_dispatch_binding_snapshot",
    "get_dispatch_binding_runtime",
    "reset_dispatch_binding_runtime",
    # PR package 13: Canonical Host-Side Android Execution Signal Reconciliation Binding (MAIN repo side)
    "ANDROID_EXECUTION_SIGNAL_RECONCILER_AUTHORITY",
    "RECONCILER_REQUIRES_CONTRACT_ID_OR_SESSION_ID_POLICY",
    "RECONCILER_SIGNAL_MAPPING_IS_CANONICAL_POLICY",
    "RECONCILER_TERMINAL_RECORD_BLOCKS_FURTHER_SIGNALS_POLICY",
    "RECONCILER_IDENTITY_IS_PRESERVED_ACROSS_RECONCILE_POLICY",
    "RECONCILER_UNKNOWN_SIGNAL_DEFAULTS_TO_PROGRESS_POLICY",
    "RECONCILER_TASK_STATUS_MAPS_TO_ACK_SIGNAL_CANONICALLY_POLICY",
    "RECONCILER_ERROR_SIGNAL_CLOSES_TRACKING_RECORD_POLICY",
    "RECONCILER_TIMEOUT_SIGNAL_CLOSES_TRACKING_RECORD_POLICY",
    "RECONCILER_CANCELLED_SIGNAL_CLOSES_TRACKING_RECORD_POLICY",
    "RECONCILER_RESULT_PAYLOAD_IS_FORWARDED_TO_TRACKER_POLICY",
    "ANDROID_EXECUTION_SIGNAL_RECONCILER_PR13_SENTINEL",
    # PR-22: reconciler registry consolidation sentinels
    "RECONCILER_PR22_SENTINEL",
    "RECONCILER_REGISTRY_GATE_IS_AUTHORITATIVE_PR22_POLICY",
    "RECONCILER_REGISTRY_BLOCKS_NON_ACTIVE_SESSION_PR22_POLICY",
    "AndroidSignalKind",
    "AndroidExecutionSignalEnvelope",
    "AndroidSignalReconcileOutcome",
    "normalize_android_message_to_signal_kind",
    "extract_signal_envelope",
    "reconcile_android_execution_signal",
    "reconcile_inbound_message",
    # PR package 14: Canonical Persistent Attached-Runtime Reuse Binding (MAIN repo side)
    "ATTACHED_RUNTIME_REUSE_BINDING_AUTHORITY",
    "REUSE_BINDING_REQUIRES_ATTACHED_SESSION_POLICY",
    "REUSE_BINDING_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY",
    "REUSE_BINDING_REQUIRES_TARGET_DEVICE_ID_POLICY",
    "REUSE_ELIGIBILITY_REQUIRES_ACTIVE_SESSION_POLICY",
    "REUSE_BINDING_INVALIDATED_ON_DETACH_POLICY",
    "REUSE_BINDING_INVALIDATED_ON_DISCONNECT_POLICY",
    "REUSE_BINDING_INVALIDATED_ON_DISABLE_POLICY",
    "REUSE_BINDING_DISPATCH_BINDING_ID_IS_LATEST_POLICY",
    "REUSE_BINDING_IS_STABLE_TARGETING_SURFACE_POLICY",
    "ATTACHED_RUNTIME_REUSE_BINDING_PR14_SENTINEL",
    "ReuseEligibilityStatus",
    "ReuseInvalidationReason",
    "AttachedRuntimeReuseBindingIdentity",
    "AttachedRuntimeReuseBindingRecord",
    "AttachedRuntimeReuseBindingSnapshot",
    "AttachedRuntimeReuseBindingRuntime",
    "establish_reuse_binding",
    "evaluate_reuse_eligibility",
    "invalidate_reuse_binding",
    "register_dispatch_binding_id",
    "record_reuse_binding",
    "get_reuse_binding",
    "get_reuse_binding_by_device",
    "list_eligible_reuse_bindings",
    "build_reuse_binding_snapshot",
    "get_reuse_binding_runtime",
    "reset_reuse_binding_runtime",
    # PR package 16: Canonical Ingress Path for Android Delegated Execution Signals (MAIN repo side)
    "ANDROID_DELEGATED_SIGNAL_INGRESS_AUTHORITY",
    "INGRESS_DELEGATED_SIGNAL_TYPE_IS_CANONICAL_POLICY",
    "INGRESS_SIGNAL_KIND_IS_EXPLICIT_FIELD_POLICY",
    "INGRESS_RESULT_KIND_DISAMBIGUATES_RESULT_SIGNALS_POLICY",
    "INGRESS_SIGNAL_ID_IS_PRESERVED_POLICY",
    "INGRESS_EMISSION_SEQ_IS_PRESERVED_POLICY",
    "INGRESS_IDENTITY_FIELDS_ARE_VERBATIM_POLICY",
    "INGRESS_REQUIRES_LOOKUP_KEY_POLICY",
    "INGRESS_DELEGATES_TO_RECONCILER_POLICY",
    "INGRESS_TRACKER_PHASE_CONSISTENT_WITH_SIGNAL_KIND_POLICY",
    "INGRESS_NON_DESTRUCTIVE_ON_MISS_POLICY",
    "INGRESS_RECOVERY_GUARD_IS_MANDATORY_POLICY",
    "INGRESS_GUARD_REJECTED_SIGNAL_IS_DROPPED_POLICY",
    "ANDROID_DELEGATED_SIGNAL_INGRESS_PR16_SENTINEL",
    # PR package 21: Canonical Delegated Execution Path Closure (MAIN repo side)
    "CANONICAL_PATH_IS_INGRESS_GUARD_RECONCILE_TRACKER_POLICY",
    "IDENTITY_CONTINUITY_ACROSS_CANONICAL_PATH_POLICY",
    "TERMINAL_STATE_IS_PROTECTED_AGAINST_REPLAY_POLICY",
    "CANONICAL_DELEGATED_EXECUTION_PATH_CLOSED_PR21_SENTINEL",
    # PR-22: ingress registry consolidation sentinels
    "INGRESS_REGISTRY_CONSOLIDATION_PR22_SENTINEL",
    "INGRESS_REGISTRY_GATE_IS_AUTHORITATIVE_PR22_POLICY",
    "INGRESS_REGISTRY_BLOCKS_NON_ACTIVE_SESSION_PR22_POLICY",
    "DelegatedSignalKind",
    "ResultKind",
    "DelegatedExecutionSignalEnvelope",
    "extract_delegated_signal_envelope",
    "ingest_delegated_execution_signal",
    # PR package 15: Attached-Runtime Recovery Readiness and Inbound Signal Guard (MAIN repo side)
    "ATTACHED_RUNTIME_RECOVERY_READINESS_AUTHORITY",
    "GUARD_MUST_PRECEDE_RECONCILE_POLICY",
    "DUPLICATE_SIGNAL_ID_IS_REJECTED_POLICY",
    "REPLAY_AT_SAME_SEQ_IS_REJECTED_POLICY",
    "STALE_EMISSION_SEQ_IS_REJECTED_POLICY",
    "OUT_OF_ORDER_EMISSION_SEQ_IS_REJECTED_POLICY",
    "ACCEPTED_SIGNAL_IS_RECORDED_POLICY",
    "GUARD_DECISION_IS_OBSERVABLE_POLICY",
    "RING_BUFFER_IS_BOUNDED_POLICY",
    "IDEMPOTENCY_KEY_USES_SIGNAL_ID_AND_CONTEXT_POLICY",
    "SEQ_INDEX_TRACKS_MAX_PER_CONTEXT_POLICY",
    "REJECTED_SIGNAL_MUST_NOT_REACH_TRACKER_POLICY",
    "ATTACHED_RUNTIME_RECOVERY_READINESS_PR15_SENTINEL",
    "RECOVERY_READINESS_RING_BUFFER_SIZE",
    "STALE_EMISSION_SEQ_THRESHOLD",
    "SignalGuardDecision",
    "RecoveryReadinessStatus",
    "IdempotencyKey",
    "SeenSignalRecord",
    "SignalGuardOutcome",
    "RecoveryReadinessSnapshot",
    "RecoveryReadinessRuntime",
    "build_idempotency_key",
    "check_signal_guard",
    "record_seen_signal",
    "guard_inbound_signal",
    "build_recovery_readiness_snapshot",
    "get_recovery_readiness_runtime",
    "reset_recovery_readiness_runtime",
    # PR-17: Canonical Dispatch Consumption of Attached-Runtime Reuse Bindings
    "ATTACHED_RUNTIME_REUSE_DISPATCH_AUTHORITY",
    "REUSE_DISPATCH_LOOKUP_PRECEDES_DISPATCH_POLICY",
    "REUSE_DISPATCH_ELIGIBILITY_GATE_IS_MANDATORY_POLICY",
    "REUSE_DISPATCH_ELIGIBLE_SURFACE_IS_REUSED_POLICY",
    "REUSE_DISPATCH_INELIGIBLE_BINDING_IS_REJECTED_POLICY",
    "REUSE_DISPATCH_NO_BINDING_ALLOWS_NEW_DISPATCH_POLICY",
    "REUSE_DISPATCH_WRITE_BACK_IS_MANDATORY_POLICY",
    "REUSE_DISPATCH_INVALIDATION_HARD_STOP_POLICY",
    "REUSE_DISPATCH_SESSION_LOOKUP_PRECEDES_DEVICE_LOOKUP_POLICY",
    "REUSE_DISPATCH_LIVE_SESSION_CROSS_CHECK_IS_OPTIONAL_POLICY",
    "REUSE_DISPATCH_RESOLUTION_IS_IMMUTABLE_POLICY",
    "REUSE_DISPATCH_DETACH_TRIGGERS_INELIGIBLE_RESOLUTION_POLICY",
    "ATTACHED_RUNTIME_REUSE_DISPATCH_PR17_SENTINEL",
    "ReuseDispatchResolutionKind",
    "ReuseDispatchResolution",
    "resolve_reuse_dispatch_surface",
    "write_back_dispatch_binding_id",
    "dispatch_with_reuse_binding",
    # PR-22: reuse dispatch registry consolidation sentinels
    "REUSE_DISPATCH_PR22_SENTINEL",
    "REUSE_DISPATCH_REGISTRY_GATE_IS_AUTHORITATIVE_PR22_POLICY",
    "REUSE_DISPATCH_REGISTRY_BLOCKS_NON_ACTIVE_SESSION_PR22_POLICY",
    # PR-23: canonical takeover dispatch / delegated fallback
    "REUSE_DISPATCH_PR23_SENTINEL",
    "TAKEOVER_DISPATCH_CONSULTS_REGISTRY_FIRST_PR23_POLICY",
    "DELEGATED_FALLBACK_REQUIRES_INELIGIBLE_CANONICAL_PATH_PR23_POLICY",
    "TAKEOVER_DISPATCH_DECISION_IS_DETERMINISTIC_PR23_POLICY",
    "REPLACED_SESSION_CANNOT_WIN_TAKEOVER_DISPATCH_PR23_POLICY",
    "STALE_EXECUTION_CONTEXT_CANNOT_ALTER_TAKEOVER_DECISION_PR23_POLICY",
    "TakeoverRouteOutcome",
    "TakeoverDispatchDecision",
    "resolve_takeover_or_fallback_route",
    # PR package 19: Authoritative Attached Runtime Session Registry (MAIN repo side)
    "ATTACHED_RUNTIME_SESSION_REGISTRY_AUTHORITY",
    "REGISTRY_IS_SINGLE_TRUTH_SOURCE_POLICY",
    "REGISTRY_DEVICE_HAS_AT_MOST_ONE_ACTIVE_SESSION_POLICY",
    "REGISTRY_REGISTER_REPLACES_OLD_SESSION_POLICY",
    "REGISTRY_RECONNECT_PRESERVES_RUNTIME_SESSION_ID_POLICY",
    "REGISTRY_DETACH_REQUIRES_EXPLICIT_SIGNAL_POLICY",
    "REGISTRY_INVALIDATED_ENTRY_IS_TERMINAL_POLICY",
    "REGISTRY_DISPATCH_MUST_CONSULT_REGISTRY_POLICY",
    "REGISTRY_REUSE_MUST_CONSULT_REGISTRY_POLICY",
    "REGISTRY_RECONCILIATION_MUST_CONSULT_REGISTRY_POLICY",
    "REGISTRY_LOOKUP_RETURNS_ACTIVE_ONLY_BY_DEFAULT_POLICY",
    "ATTACHED_RUNTIME_SESSION_REGISTRY_PR19_SENTINEL",
    "RegistryEntryState",
    "RegistryTransition",
    "InvalidationReason",
    "AttachedSessionRegistryEntry",
    "AttachedSessionRegistrySnapshot",
    "AttachedSessionRegistry",
    "register_session",
    "reconnect_session",
    "reattach_session",
    "detach_session",
    "invalidate_session",
    "lookup_active_session",
    "lookup_session_by_device",
    "list_active_sessions",
    "build_registry_snapshot",
    "get_session_registry",
    "reset_session_registry",
    # PR-22: registry consolidation sentinels
    "ATTACHED_RUNTIME_REGISTRY_CONSOLIDATION_PR22_SENTINEL",
    "REGISTRY_IS_AUTHORITATIVE_DISPATCH_GATE_PR22_POLICY",
    "REGISTRY_IS_AUTHORITATIVE_REUSE_GATE_PR22_POLICY",
    "REGISTRY_IS_AUTHORITATIVE_RECONCILIATION_GATE_PR22_POLICY",
    "REGISTRY_KNOWN_NON_ACTIVE_BLOCKS_EXECUTION_PR22_POLICY",
    "REGISTRY_ABSENT_ENTRY_PASSES_THROUGH_PR22_POLICY",
    # PR-23: canonical takeover dispatch authority sentinels
    "ATTACHED_RUNTIME_REGISTRY_TAKEOVER_DISPATCH_PR23_SENTINEL",
    "REGISTRY_IS_CANONICAL_TAKEOVER_DISPATCH_AUTHORITY_PR23_POLICY",
    "REGISTRY_TAKEOVER_ELIGIBILITY_REQUIRES_ACTIVE_STATE_PR23_POLICY",
    "REGISTRY_REPLACED_SESSION_IS_INELIGIBLE_FOR_TAKEOVER_PR23_POLICY",
    # PR package 20: Canonical Delegated Target Selection Policy (MAIN repo side)
    "DELEGATED_TARGET_SELECTION_POLICY_AUTHORITY",
    "SELECTION_MUST_CONSULT_REGISTRY_POLICY",
    "SELECTION_REQUIRES_ACTIVE_ATTACHMENT_STATE_POLICY",
    "SELECTION_REQUIRES_JOIN_RUNTIME_POSTURE_POLICY",
    "SELECTION_REQUIRES_NO_INVALIDATION_REASON_POLICY",
    "SELECTION_REUSE_VALID_IS_PREFERRED_POLICY",
    "SELECTION_HIGH_FAILURE_COUNT_DEMOTES_CANDIDATE_POLICY",
    "SELECTION_HIGH_DETACH_COUNT_DEMOTES_CANDIDATE_POLICY",
    "SELECTION_NO_VALID_CANDIDATE_TRIGGERS_LOCAL_FALLBACK_POLICY",
    "SELECTION_HIGH_RISK_CANDIDATE_MAY_DEGRADE_POLICY",
    "SELECTION_DECISION_IS_EXPLAINABLE_POLICY",
    "SELECTION_RANKING_IS_DETERMINISTIC_POLICY",
    "DELEGATED_TARGET_SELECTION_POLICY_PR20_SENTINEL",
    "DEGRADATION_SCORE_THRESHOLD",
    "BASE_CANDIDATE_SCORE",
    "REUSE_VALID_BONUS",
    "FAILURE_COUNT_PENALTY_PER_UNIT",
    "FAILURE_COUNT_MAX_PENALTY",
    "DETACH_COUNT_PENALTY_PER_UNIT",
    "DETACH_COUNT_MAX_PENALTY",
    "LOAD_PENALTY_PER_10_EXECUTIONS",
    "LOAD_MAX_PENALTY",
    "SelectionOutcome",
    "CandidateRejectionReason",
    "SelectionCandidateContext",
    "CandidateEvaluation",
    "SelectionDecision",
    "evaluate_candidate",
    "rank_candidates",
    "select_delegated_target",
    "build_selection_explanation",
    # PR-6 (center-side): WebRTC Task-Lifecycle Integration
    "WEBRTC_TASK_LIFECYCLE_AUTHORITY",
    "WEBRTC_SESSION_MUST_BE_TASK_SCOPED_POLICY",
    "TRANSPORT_STATE_DRIVES_LIFECYCLE_ACTION_POLICY",
    "TERMINAL_TASK_TRIGGERS_SESSION_TEARDOWN_POLICY",
    "DEGRADED_TRANSPORT_YIELDS_DEGRADED_TASK_POLICY",
    "FAILED_TRANSPORT_YIELDS_FAILED_TASK_POLICY",
    "RECONNECTED_TRANSPORT_RESUMES_RUNNING_TASK_POLICY",
    "BINDING_IS_TASK_SCOPED_SINGLE_SESSION_POLICY",
    "TEARDOWN_IS_IDEMPOTENT_POLICY",
    "SESSION_BINDING_RECORD_IS_IMMUTABLE_POLICY",
    "WEBRTC_TASK_LIFECYCLE_PR6_SENTINEL",
    "WebRTCTransportState",
    "WebRTCTaskLifecycleAction",
    "WebRTCTaskBinding",
    "WebRTCTaskBindingSnapshot",
    "WebRTCTaskSessionRegistry",
    "bind_webrtc_session_to_task",
    "classify_transport_lifecycle_action",
    "apply_transport_state_to_task_lifecycle",
    "teardown_binding_on_task_terminal",
    "get_webrtc_task_binding",
    "list_active_webrtc_task_bindings",
    "build_webrtc_task_binding_snapshot",
    "get_webrtc_task_session_registry",
    "reset_webrtc_task_session_registry",
    # PR-4V2: Android Participant/Session/Runtime Truth Ingress and Canonical
    # Reconciliation into V2 Orchestration State — closes TRUTH-005.
    "ANDROID_PARTICIPANT_TRUTH_INGRESS_AUTHORITY",
    "V2_IS_CANONICAL_ORCHESTRATION_AUTHORITY_SENTINEL",
    "ANDROID_PARTICIPANT_TRUTH_INGRESS_PR4V2_SENTINEL",
    "V2_IS_CANONICAL_ORCHESTRATION_AUTHORITY_POLICY",
    "ANDROID_TRUTH_IS_ADVISORY_FOR_DEVICE_SCOPE_POLICY",
    "CANCEL_FAILURE_RESULT_AFFECT_CANONICAL_STATE_POLICY",
    "STATUS_SIGNAL_EMITS_PROGRESS_EVENT_POLICY",
    "TASK_PHASE_RECONCILED_WITH_TRACKING_RECORD_POLICY",
    "SESSION_SNAPSHOT_VALIDATES_REGISTRY_CONTINUITY_POLICY",
    "READINESS_ASSESSMENT_IS_ADVISORY_POLICY",
    "RUNTIME_STATE_IS_AUDIT_ONLY_POLICY",
    "TERMINAL_V2_STATE_WINS_CONFLICT_POLICY",
    "RECONCILE_IS_NON_DESTRUCTIVE_ON_MISS_POLICY",
    "RECONCILE_EMITS_AUDIT_EVENT_ALWAYS_POLICY",
    "IDENTITY_FIELDS_ARE_VERBATIM_POLICY",
    "AndroidParticipantTruthKind",
    "AndroidParticipantTruthEnvelope",
    "AndroidParticipantReconcileOutcome",
    "extract_participant_truth_envelope",
    "reconcile_android_participant_truth",
    "ingest_android_participant_truth_message",
]
