#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
tests/test_android_participant_evidence_ingress.py
===================================================
Tests for core/android_participant_evidence_ingress.py — the Android
participant runtime evidence ingestion and normalization layer.

Coverage areas
--------------
A.  Module importable; authority sentinels and policy sentinels present.
B.  AndroidParticipantStatus enum values and properties.
C.  AndroidParticipantEvidenceResult dataclass construction and serialisation.
D.  Missing evidence file → missing_evidence status (fail-conservative).
E.  Invalid JSON → malformed_evidence status.
F.  Valid JSON that is not a dict → malformed_evidence status.
G.  Schema validation: missing required fields → malformed_evidence.
H.  Schema validation: wrong authority sentinel → malformed_evidence.
I.  Schema validation: wrong schema_version → malformed_evidence.
J.  Schema validation: generated_at not numeric → malformed_evidence.
K.  Schema validation: is_operational not bool → malformed_evidence.
L.  Schema validation: audit_event_count negative → malformed_evidence.
M.  Stale evidence → stale_evidence status (not treated as ready).
N.  Valid evidence with participant_status="ready" + is_operational=True + events → accepted.
O.  Valid evidence with participant_status="degraded" → degraded.
P.  Valid evidence with participant_status="unavailable" → unavailable.
Q.  Valid evidence with participant_status="recovered" → recovered.
R.  Inferred ready: is_operational=True + audit_event_count>0, no explicit status → ready.
S.  Inferred unavailable: is_operational=False + audit_event_count=0.
T.  Inferred degraded: is_operational=False + audit_event_count>0.
U.  Unverified: is_operational=True + audit_event_count=0 + no explicit status.
V.  Evidence path configurable via environment variable.
W.  Max age configurable via environment variable.
X.  to_dict() produces JSON-serialisable dict with required keys.
Y.  to_json() produces valid JSON.
Z.  build_android_participant_evidence_summary() returns a dict with required keys.

AA. system_final_acceptance_verdict integration:
    - _evaluate_android_participant uses the evidence ingress layer.
    - Missing evidence → android_participant dimension is unresolved (honest).
    - Valid ready evidence → android_participant dimension is accepted.
    - Degraded evidence → android_participant dimension is pending.
    - Stale evidence → android_participant dimension is unresolved.
    - Malformed evidence → android_participant dimension is unresolved.
    - Unavailable evidence → android_participant dimension is unresolved.
    - Evidence is visible in report summary and evidence_linkage.
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
import time
from typing import Any, Dict

import pytest

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from core.android_participant_evidence_ingress import (
    ANDROID_PARTICIPANT_EVIDENCE_INGRESS_AUTHORITY,
    ANDROID_PARTICIPANT_EVIDENCE_CONTRACT_VERSION,
    EXPECTED_AUTHORITY_SENTINEL,
    EVIDENCE_PATH_IS_CONFIGURABLE_POLICY,
    FAIL_CONSERVATIVE_ON_MISSING_EVIDENCE_POLICY,
    STALE_EVIDENCE_IS_NOT_READY_POLICY,
    MALFORMED_EVIDENCE_IS_NOT_READY_POLICY,
    PARTICIPANT_STATUS_DERIVED_FROM_EVIDENCE_POLICY,
    EVIDENCE_VISIBLE_IN_SUMMARY_POLICY,
    AndroidParticipantStatus,
    AndroidParticipantEvidenceResult,
    ingest_android_participant_evidence,
    build_android_participant_evidence_summary,
)
import core.android_participant_evidence_ingress as _mod


# ===========================================================================
# Helpers
# ===========================================================================

_NOW = 1_700_000_000.0  # fixed reference timestamp for tests


def _make_valid_evidence(
    participant_status: str = "ready",
    is_operational: bool = True,
    audit_event_count: int = 5,
    device_id: str = "test-device-001",
    session_id: str = "test-session-001",
    generated_at: float = _NOW - 60.0,  # 1 minute ago
    **extra: Any,
) -> Dict[str, Any]:
    """Return a minimal valid evidence dict."""
    base: Dict[str, Any] = {
        "schema_version": ANDROID_PARTICIPANT_EVIDENCE_CONTRACT_VERSION,
        "authority": EXPECTED_AUTHORITY_SENTINEL,
        "generated_at": generated_at,
        "device_id": device_id,
        "session_id": session_id,
        "participant_status": participant_status,
        "is_operational": is_operational,
        "audit_event_count": audit_event_count,
        "lifecycle_phase": "running",
        "last_heartbeat_at": generated_at + 30.0,
        "capability_declarations": {"screen": True, "touch": True},
        "evidence_notes": "Generated by test fixture.",
    }
    base.update(extra)
    return base


def _write_evidence(tmp_path: str, data: Dict[str, Any]) -> str:
    """Write *data* as JSON to a temp file and return the path."""
    path = os.path.join(tmp_path, "android_participant_evidence.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh)
    return path


# ===========================================================================
# A. Module sentinels
# ===========================================================================


class TestModuleSentinels:
    def test_module_importable(self):
        import core.android_participant_evidence_ingress  # noqa: F401

    def test_authority_sentinel_non_empty(self):
        assert ANDROID_PARTICIPANT_EVIDENCE_INGRESS_AUTHORITY
        assert isinstance(ANDROID_PARTICIPANT_EVIDENCE_INGRESS_AUTHORITY, str)

    def test_authority_sentinel_contains_v1(self):
        assert "V1" in ANDROID_PARTICIPANT_EVIDENCE_INGRESS_AUTHORITY

    def test_contract_version_non_empty(self):
        assert ANDROID_PARTICIPANT_EVIDENCE_CONTRACT_VERSION
        assert isinstance(ANDROID_PARTICIPANT_EVIDENCE_CONTRACT_VERSION, str)

    def test_contract_version_is_1_0(self):
        assert ANDROID_PARTICIPANT_EVIDENCE_CONTRACT_VERSION == "1.0"

    def test_expected_authority_sentinel_non_empty(self):
        assert EXPECTED_AUTHORITY_SENTINEL
        assert "ANDROID_PARTICIPANT" in EXPECTED_AUTHORITY_SENTINEL

    def test_policy_sentinels_are_strings(self):
        policies = [
            EVIDENCE_PATH_IS_CONFIGURABLE_POLICY,
            FAIL_CONSERVATIVE_ON_MISSING_EVIDENCE_POLICY,
            STALE_EVIDENCE_IS_NOT_READY_POLICY,
            MALFORMED_EVIDENCE_IS_NOT_READY_POLICY,
            PARTICIPANT_STATUS_DERIVED_FROM_EVIDENCE_POLICY,
            EVIDENCE_VISIBLE_IN_SUMMARY_POLICY,
        ]
        for p in policies:
            assert isinstance(p, str), f"Expected str, got {type(p)}"
            assert p, "Policy sentinel must be non-empty"

    def test_policy_sentinels_contain_policy_tag(self):
        for p in [
            EVIDENCE_PATH_IS_CONFIGURABLE_POLICY,
            FAIL_CONSERVATIVE_ON_MISSING_EVIDENCE_POLICY,
            STALE_EVIDENCE_IS_NOT_READY_POLICY,
        ]:
            assert "POLICY::" in p

    def test_all_exports_in_dunder_all(self):
        for name in [
            "ANDROID_PARTICIPANT_EVIDENCE_INGRESS_AUTHORITY",
            "AndroidParticipantStatus",
            "AndroidParticipantEvidenceResult",
            "ingest_android_participant_evidence",
            "build_android_participant_evidence_summary",
        ]:
            assert name in _mod.__all__, f"{name} missing from __all__"


# ===========================================================================
# B. AndroidParticipantStatus enum
# ===========================================================================


class TestAndroidParticipantStatusEnum:
    def test_has_all_values(self):
        values = {s.value for s in AndroidParticipantStatus}
        expected = {
            "ready", "degraded", "unavailable", "recovered",
            "missing_evidence", "malformed_evidence", "stale_evidence",
            "unverified",
        }
        assert expected == values

    def test_ready_is_positive(self):
        assert AndroidParticipantStatus.ready.is_positive

    def test_recovered_is_positive(self):
        assert AndroidParticipantStatus.recovered.is_positive

    def test_degraded_is_negative(self):
        assert AndroidParticipantStatus.degraded.is_negative

    def test_unavailable_is_negative(self):
        assert AndroidParticipantStatus.unavailable.is_negative

    def test_missing_evidence_is_negative(self):
        assert AndroidParticipantStatus.missing_evidence.is_negative

    def test_malformed_evidence_is_negative(self):
        assert AndroidParticipantStatus.malformed_evidence.is_negative

    def test_stale_evidence_is_negative(self):
        assert AndroidParticipantStatus.stale_evidence.is_negative

    def test_unverified_is_negative(self):
        assert AndroidParticipantStatus.unverified.is_negative

    def test_ready_has_evidence(self):
        assert AndroidParticipantStatus.ready.has_evidence

    def test_missing_evidence_has_no_evidence(self):
        assert not AndroidParticipantStatus.missing_evidence.has_evidence

    def test_malformed_evidence_has_no_evidence(self):
        assert not AndroidParticipantStatus.malformed_evidence.has_evidence

    def test_stale_evidence_has_evidence(self):
        assert AndroidParticipantStatus.stale_evidence.has_evidence


# ===========================================================================
# C. AndroidParticipantEvidenceResult dataclass
# ===========================================================================


class TestAndroidParticipantEvidenceResult:
    def test_default_construction(self):
        r = AndroidParticipantEvidenceResult()
        assert r.status == AndroidParticipantStatus.missing_evidence
        assert r.result_id.startswith("aper_")

    def test_to_dict_has_required_keys(self):
        r = AndroidParticipantEvidenceResult(
            status=AndroidParticipantStatus.ready,
            evidence_summary="all good",
        )
        d = r.to_dict()
        for key in [
            "result_id", "status", "evidence_summary", "gap_description",
            "raw_evidence", "evidence_path", "ingested_at", "age_seconds",
            "participant_status_raw", "is_operational", "audit_event_count",
            "reject_reason",
        ]:
            assert key in d, f"Key {key!r} missing from to_dict()"

    def test_to_dict_json_serialisable(self):
        r = AndroidParticipantEvidenceResult(
            status=AndroidParticipantStatus.ready,
            evidence_summary="ok",
            raw_evidence={"foo": 1},
        )
        payload = json.dumps(r.to_dict())
        assert json.loads(payload)["status"] == "ready"

    def test_to_json_valid(self):
        r = AndroidParticipantEvidenceResult()
        parsed = json.loads(r.to_json())
        assert parsed["status"] == "missing_evidence"


# ===========================================================================
# D. Missing evidence file → missing_evidence
# ===========================================================================


class TestMissingEvidence:
    def test_missing_file_returns_missing_evidence(self):
        r = ingest_android_participant_evidence(
            evidence_path="/nonexistent/path/android_participant_evidence.json",
            _now=_NOW,
        )
        assert r.status == AndroidParticipantStatus.missing_evidence

    def test_missing_file_reject_reason(self):
        r = ingest_android_participant_evidence(
            evidence_path="/nonexistent/path/android_participant_evidence.json",
            _now=_NOW,
        )
        assert r.reject_reason == "file_not_found"

    def test_missing_file_evidence_summary_non_empty(self):
        r = ingest_android_participant_evidence(
            evidence_path="/nonexistent/path/evidence.json",
            _now=_NOW,
        )
        assert r.evidence_summary
        assert "not found" in r.evidence_summary.lower()

    def test_missing_file_gap_description_non_empty(self):
        r = ingest_android_participant_evidence(
            evidence_path="/nonexistent/path/evidence.json",
            _now=_NOW,
        )
        assert r.gap_description

    def test_missing_file_evidence_path_recorded(self):
        p = "/nonexistent/path/evidence.json"
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.evidence_path == p


# ===========================================================================
# E. Invalid JSON → malformed_evidence
# ===========================================================================


class TestMalformedJsonEvidence:
    def test_invalid_json_returns_malformed(self, tmp_path):
        p = os.path.join(str(tmp_path), "bad.json")
        with open(p, "w") as fh:
            fh.write("not json {{{")
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence

    def test_invalid_json_reject_reason_contains_parse(self, tmp_path):
        p = os.path.join(str(tmp_path), "bad.json")
        with open(p, "w") as fh:
            fh.write("!!!")
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert "json_parse_error" in r.reject_reason

    def test_empty_file_returns_malformed(self, tmp_path):
        p = os.path.join(str(tmp_path), "empty.json")
        with open(p, "w") as fh:
            fh.write("")
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence


# ===========================================================================
# F. Valid JSON that is not a dict → malformed_evidence
# ===========================================================================


class TestNonDictJson:
    def test_list_at_top_level(self, tmp_path):
        p = os.path.join(str(tmp_path), "list.json")
        with open(p, "w") as fh:
            json.dump([], fh)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence
        assert "not_a_dict" in r.reject_reason

    def test_string_at_top_level(self, tmp_path):
        p = os.path.join(str(tmp_path), "str.json")
        with open(p, "w") as fh:
            json.dump("hello", fh)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence


# ===========================================================================
# G–L. Schema validation
# ===========================================================================


class TestSchemaValidation:
    def _write(self, tmp_path, data: Dict[str, Any]) -> str:
        p = os.path.join(str(tmp_path), "ev.json")
        with open(p, "w") as fh:
            json.dump(data, fh)
        return p

    def test_missing_schema_version(self, tmp_path):
        d = _make_valid_evidence()
        del d["schema_version"]
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence
        assert "missing_required_fields" in r.reject_reason

    def test_missing_authority(self, tmp_path):
        d = _make_valid_evidence()
        del d["authority"]
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence

    def test_missing_generated_at(self, tmp_path):
        d = _make_valid_evidence()
        del d["generated_at"]
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence

    def test_missing_participant_status(self, tmp_path):
        d = _make_valid_evidence()
        del d["participant_status"]
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence

    def test_missing_is_operational(self, tmp_path):
        d = _make_valid_evidence()
        del d["is_operational"]
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence

    def test_missing_audit_event_count(self, tmp_path):
        d = _make_valid_evidence()
        del d["audit_event_count"]
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence

    def test_wrong_authority(self, tmp_path):
        d = _make_valid_evidence()
        d["authority"] = "WRONG_AUTHORITY"
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence
        assert "authority_mismatch" in r.reject_reason

    def test_wrong_schema_version(self, tmp_path):
        d = _make_valid_evidence()
        d["schema_version"] = "99.0"
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence
        assert "schema_version_mismatch" in r.reject_reason

    def test_generated_at_string(self, tmp_path):
        d = _make_valid_evidence()
        d["generated_at"] = "not-a-number"
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence

    def test_is_operational_string(self, tmp_path):
        d = _make_valid_evidence()
        d["is_operational"] = "true"
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence

    def test_audit_event_count_negative(self, tmp_path):
        d = _make_valid_evidence()
        d["audit_event_count"] = -1
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence

    def test_audit_event_count_float(self, tmp_path):
        d = _make_valid_evidence()
        d["audit_event_count"] = 3.5
        p = self._write(tmp_path, d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.malformed_evidence


# ===========================================================================
# M. Stale evidence → stale_evidence (not ready)
# ===========================================================================


class TestStaleEvidence:
    def test_stale_evidence_status(self, tmp_path):
        # generated 2 hours ago, max age 1 hour
        d = _make_valid_evidence(generated_at=_NOW - 7200.0)
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(
            evidence_path=p, max_age_seconds=3600.0, _now=_NOW
        )
        assert r.status == AndroidParticipantStatus.stale_evidence

    def test_stale_reject_reason(self, tmp_path):
        d = _make_valid_evidence(generated_at=_NOW - 7200.0)
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(
            evidence_path=p, max_age_seconds=3600.0, _now=_NOW
        )
        assert r.reject_reason == "stale_evidence"

    def test_stale_evidence_not_treated_as_ready(self, tmp_path):
        # Even participant_status="ready" must not overcome staleness
        d = _make_valid_evidence(
            participant_status="ready",
            is_operational=True,
            audit_event_count=100,
            generated_at=_NOW - 7200.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(
            evidence_path=p, max_age_seconds=3600.0, _now=_NOW
        )
        assert r.status == AndroidParticipantStatus.stale_evidence
        assert r.status != AndroidParticipantStatus.ready

    def test_barely_fresh_evidence_not_stale(self, tmp_path):
        # generated 59 minutes ago, max age 1 hour (3600 s)
        d = _make_valid_evidence(generated_at=_NOW - 3540.0)
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(
            evidence_path=p, max_age_seconds=3600.0, _now=_NOW
        )
        assert r.status != AndroidParticipantStatus.stale_evidence

    def test_stale_evidence_gap_description_mentions_staleness(self, tmp_path):
        d = _make_valid_evidence(generated_at=_NOW - 7200.0)
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(
            evidence_path=p, max_age_seconds=3600.0, _now=_NOW
        )
        assert "stale" in r.gap_description.lower() or "old" in r.gap_description.lower()

    def test_stale_evidence_records_age(self, tmp_path):
        d = _make_valid_evidence(generated_at=_NOW - 7200.0)
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(
            evidence_path=p, max_age_seconds=3600.0, _now=_NOW
        )
        assert r.age_seconds == pytest.approx(7200.0, rel=0.01)


# ===========================================================================
# N–Q. Valid evidence — explicit participant_status values
# ===========================================================================


class TestExplicitParticipantStatus:
    def test_ready_explicit(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="ready", is_operational=True, audit_event_count=5,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.ready

    def test_degraded_explicit(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="degraded", is_operational=False, audit_event_count=3,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.degraded

    def test_unavailable_explicit(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="unavailable", is_operational=False, audit_event_count=0,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.unavailable

    def test_recovered_explicit(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="recovered", is_operational=True, audit_event_count=2,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.recovered

    def test_ready_evidence_summary_contains_device(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="ready", device_id="my-device-001",
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert "my-device-001" in r.evidence_summary

    def test_ready_gap_description_is_empty(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="ready", is_operational=True, audit_event_count=5,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.gap_description == ""

    def test_degraded_gap_description_non_empty(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="degraded", is_operational=False, audit_event_count=3,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.gap_description

    def test_unavailable_gap_description_non_empty(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="unavailable", is_operational=False, audit_event_count=0,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.gap_description


# ===========================================================================
# R–U. Inferred status
# ===========================================================================


class TestInferredStatus:
    def test_inferred_ready_no_explicit_status(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="",
            is_operational=True,
            audit_event_count=10,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.ready

    def test_inferred_unavailable_not_operational_no_events(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="",
            is_operational=False,
            audit_event_count=0,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.unavailable

    def test_inferred_degraded_not_operational_with_events(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="",
            is_operational=False,
            audit_event_count=7,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.degraded

    def test_unverified_operational_no_events_no_explicit_status(self, tmp_path):
        d = _make_valid_evidence(
            participant_status="",
            is_operational=True,
            audit_event_count=0,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.unverified


# ===========================================================================
# V. Evidence path configurable via env var
# ===========================================================================


class TestEvidencePathConfiguration:
    def test_env_var_overrides_default(self, tmp_path, monkeypatch):
        d = _make_valid_evidence(participant_status="ready", generated_at=_NOW - 60.0)
        p = _write_evidence(str(tmp_path), d)
        monkeypatch.setenv("ANDROID_PARTICIPANT_EVIDENCE_PATH", p)
        r = ingest_android_participant_evidence(_now=_NOW)
        assert r.status == AndroidParticipantStatus.ready
        monkeypatch.delenv("ANDROID_PARTICIPANT_EVIDENCE_PATH", raising=False)

    def test_explicit_path_param_takes_priority(self, tmp_path, monkeypatch):
        # env var points to missing file; explicit path param should win
        monkeypatch.setenv(
            "ANDROID_PARTICIPANT_EVIDENCE_PATH", "/nonexistent/env-path.json"
        )
        d = _make_valid_evidence(participant_status="ready", generated_at=_NOW - 60.0)
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.ready
        monkeypatch.delenv("ANDROID_PARTICIPANT_EVIDENCE_PATH", raising=False)


# ===========================================================================
# W. Max age configurable via env var
# ===========================================================================


class TestMaxAgeConfiguration:
    def test_env_var_max_age_enforced(self, tmp_path, monkeypatch):
        # Set max age to 10 seconds; evidence is 30 seconds old → stale
        monkeypatch.setenv("ANDROID_PARTICIPANT_EVIDENCE_MAX_AGE_SECONDS", "10")
        d = _make_valid_evidence(
            participant_status="ready",
            is_operational=True,
            audit_event_count=5,
            generated_at=_NOW - 30.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        assert r.status == AndroidParticipantStatus.stale_evidence
        monkeypatch.delenv("ANDROID_PARTICIPANT_EVIDENCE_MAX_AGE_SECONDS", raising=False)

    def test_explicit_max_age_param_overrides(self, tmp_path):
        # Evidence is 30s old; pass max_age=60 → should not be stale
        d = _make_valid_evidence(
            participant_status="ready",
            is_operational=True,
            audit_event_count=5,
            generated_at=_NOW - 30.0,
        )
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(
            evidence_path=p, max_age_seconds=60.0, _now=_NOW
        )
        assert r.status != AndroidParticipantStatus.stale_evidence


# ===========================================================================
# X–Y. Serialisation
# ===========================================================================


class TestSerialisation:
    def test_to_dict_json_serialisable_for_ready(self, tmp_path):
        d = _make_valid_evidence(participant_status="ready", generated_at=_NOW - 60.0)
        p = _write_evidence(str(tmp_path), d)
        r = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        payload = json.dumps(r.to_dict())
        parsed = json.loads(payload)
        assert parsed["status"] == "ready"

    def test_to_json_round_trip_for_missing(self):
        r = ingest_android_participant_evidence(
            evidence_path="/no/such/file.json", _now=_NOW
        )
        parsed = json.loads(r.to_json())
        assert parsed["status"] == "missing_evidence"

    def test_to_dict_has_all_required_keys(self, tmp_path):
        r = ingest_android_participant_evidence(
            evidence_path="/no/such/file.json", _now=_NOW
        )
        d = r.to_dict()
        required = [
            "result_id", "status", "evidence_summary", "gap_description",
            "raw_evidence", "evidence_path", "ingested_at", "age_seconds",
            "participant_status_raw", "is_operational", "audit_event_count",
            "reject_reason",
        ]
        for k in required:
            assert k in d, f"Missing key: {k}"


# ===========================================================================
# Z. build_android_participant_evidence_summary
# ===========================================================================


class TestBuildSummary:
    def test_summary_has_required_keys(self):
        s = build_android_participant_evidence_summary(
            result=ingest_android_participant_evidence(
                evidence_path="/no/such/file.json", _now=_NOW
            )
        )
        for key in [
            "android_participant_status",
            "evidence_summary",
            "gap_description",
            "evidence_path",
            "age_seconds",
            "is_operational",
            "audit_event_count",
            "participant_status_raw",
            "reject_reason",
            "ingested_at",
            "result_id",
        ]:
            assert key in s, f"Missing key: {key}"

    def test_summary_status_for_missing_evidence(self):
        r = ingest_android_participant_evidence(
            evidence_path="/no/such/file.json", _now=_NOW
        )
        s = build_android_participant_evidence_summary(result=r)
        assert s["android_participant_status"] == "missing_evidence"

    def test_summary_no_arg_triggers_ingestion(self, tmp_path, monkeypatch):
        # Supply a valid evidence file via env var; no explicit result arg
        d = _make_valid_evidence(participant_status="ready", generated_at=_NOW - 60.0)
        p = _write_evidence(str(tmp_path), d)
        monkeypatch.setenv("ANDROID_PARTICIPANT_EVIDENCE_PATH", p)
        # Can't fix _now without passing result; just check it runs and returns dict
        s = build_android_participant_evidence_summary()
        assert isinstance(s, dict)
        assert "android_participant_status" in s
        monkeypatch.delenv("ANDROID_PARTICIPANT_EVIDENCE_PATH", raising=False)

    def test_summary_json_serialisable(self, tmp_path):
        r = ingest_android_participant_evidence(
            evidence_path="/no/such/file.json", _now=_NOW
        )
        s = build_android_participant_evidence_summary(result=r)
        payload = json.dumps(s)
        assert json.loads(payload)["android_participant_status"] == "missing_evidence"


# ===========================================================================
# AA. system_final_acceptance_verdict integration
# ===========================================================================


class TestSystemFinalAcceptanceVerdictIntegration:
    """Integration tests: _evaluate_android_participant uses evidence ingress."""

    @pytest.fixture(autouse=True)
    def fresh_evaluator(self):
        from core.system_final_acceptance_verdict import reset_system_acceptance_evaluator
        reset_system_acceptance_evaluator()
        yield
        reset_system_acceptance_evaluator()

    def test_android_dimension_uses_evidence_ingress_signal_source(self, tmp_path):
        """Signal source should reference core.android_participant_evidence_ingress."""
        from core.system_final_acceptance_verdict import evaluate_system_acceptance
        report = evaluate_system_acceptance()
        item = report.checklist.get("android_participant")
        assert item is not None
        assert "android_participant_evidence_ingress" in item.signal_source

    def test_missing_evidence_yields_unresolved(self, tmp_path, monkeypatch):
        """No evidence file → android_participant is unresolved (honest)."""
        monkeypatch.setenv(
            "ANDROID_PARTICIPANT_EVIDENCE_PATH",
            os.path.join(str(tmp_path), "nonexistent.json"),
        )
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance,
            DimensionStatus,
        )
        reset_system_acceptance_evaluator()
        report = evaluate_system_acceptance()
        item = report.checklist["android_participant"]
        assert item.status == DimensionStatus.unresolved
        monkeypatch.delenv("ANDROID_PARTICIPANT_EVIDENCE_PATH", raising=False)

    def test_missing_evidence_gap_description_mentions_evidence(self, tmp_path, monkeypatch):
        monkeypatch.setenv(
            "ANDROID_PARTICIPANT_EVIDENCE_PATH",
            os.path.join(str(tmp_path), "nonexistent.json"),
        )
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance,
        )
        reset_system_acceptance_evaluator()
        report = evaluate_system_acceptance()
        item = report.checklist["android_participant"]
        assert "evidence" in item.gap_description.lower()
        monkeypatch.delenv("ANDROID_PARTICIPANT_EVIDENCE_PATH", raising=False)

    def test_valid_ready_evidence_yields_accepted(self, tmp_path, monkeypatch):
        """Valid ready evidence → android_participant is accepted."""
        d = _make_valid_evidence(
            participant_status="ready",
            is_operational=True,
            audit_event_count=5,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        expected_result = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        from unittest.mock import patch
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance, DimensionStatus,
        )
        with patch(
            "core.system_final_acceptance_verdict._ingest_android_evidence",
            return_value=expected_result,
        ):
            reset_system_acceptance_evaluator()
            report = evaluate_system_acceptance()
        item = report.checklist["android_participant"]
        assert item.status == DimensionStatus.accepted

    def test_degraded_evidence_yields_pending(self, tmp_path, monkeypatch):
        """Degraded evidence → android_participant is pending."""
        d = _make_valid_evidence(
            participant_status="degraded",
            is_operational=False,
            audit_event_count=3,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        expected_result = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        from unittest.mock import patch
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance, DimensionStatus,
        )
        with patch(
            "core.system_final_acceptance_verdict._ingest_android_evidence",
            return_value=expected_result,
        ):
            reset_system_acceptance_evaluator()
            report = evaluate_system_acceptance()
        item = report.checklist["android_participant"]
        assert item.status == DimensionStatus.pending

    def test_stale_evidence_yields_unresolved(self, tmp_path, monkeypatch):
        """Stale evidence → android_participant is unresolved (not ready)."""
        d = _make_valid_evidence(
            participant_status="ready",
            is_operational=True,
            audit_event_count=10,
            generated_at=_NOW - 7200.0,
        )
        p = _write_evidence(str(tmp_path), d)
        stale_result = ingest_android_participant_evidence(
            evidence_path=p, max_age_seconds=3600.0, _now=_NOW
        )
        from unittest.mock import patch
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance, DimensionStatus,
        )
        with patch(
            "core.system_final_acceptance_verdict._ingest_android_evidence",
            return_value=stale_result,
        ):
            reset_system_acceptance_evaluator()
            report = evaluate_system_acceptance()
        item = report.checklist["android_participant"]
        assert item.status == DimensionStatus.unresolved

    def test_malformed_evidence_yields_unresolved(self, tmp_path, monkeypatch):
        """Malformed evidence → android_participant is unresolved."""
        p = os.path.join(str(tmp_path), "malformed.json")
        with open(p, "w") as fh:
            fh.write("{bad json}")
        malformed_result = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        from unittest.mock import patch
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance, DimensionStatus,
        )
        with patch(
            "core.system_final_acceptance_verdict._ingest_android_evidence",
            return_value=malformed_result,
        ):
            reset_system_acceptance_evaluator()
            report = evaluate_system_acceptance()
        item = report.checklist["android_participant"]
        assert item.status == DimensionStatus.unresolved

    def test_unavailable_evidence_yields_unresolved(self, tmp_path):
        """Unavailable participant → android_participant is unresolved."""
        d = _make_valid_evidence(
            participant_status="unavailable",
            is_operational=False,
            audit_event_count=0,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        unavailable_result = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        from unittest.mock import patch
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance, DimensionStatus,
        )
        with patch(
            "core.system_final_acceptance_verdict._ingest_android_evidence",
            return_value=unavailable_result,
        ):
            reset_system_acceptance_evaluator()
            report = evaluate_system_acceptance()
        item = report.checklist["android_participant"]
        assert item.status == DimensionStatus.unresolved

    def test_evidence_linkage_contains_status(self, tmp_path):
        """Evidence linkage in report must contain android status info."""
        d = _make_valid_evidence(
            participant_status="ready",
            is_operational=True,
            audit_event_count=5,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        ready_result = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        from unittest.mock import patch
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance,
        )
        with patch(
            "core.system_final_acceptance_verdict._ingest_android_evidence",
            return_value=ready_result,
        ):
            reset_system_acceptance_evaluator()
            report = evaluate_system_acceptance()
        item = report.checklist["android_participant"]
        # evidence_linkage must have "status" key from to_dict()
        assert "status" in item.evidence_linkage

    def test_report_summary_contains_android_participant(self, tmp_path, monkeypatch):
        """Report summary must mention android_participant."""
        monkeypatch.setenv(
            "ANDROID_PARTICIPANT_EVIDENCE_PATH",
            os.path.join(str(tmp_path), "nonexistent.json"),
        )
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance,
        )
        reset_system_acceptance_evaluator()
        report = evaluate_system_acceptance()
        assert "android_participant" in report.summary.lower()
        monkeypatch.delenv("ANDROID_PARTICIPANT_EVIDENCE_PATH", raising=False)

    def test_no_optimistic_upgrade_when_evidence_absent(self, tmp_path, monkeypatch):
        """Missing evidence must NEVER produce fully_operational verdict."""
        monkeypatch.setenv(
            "ANDROID_PARTICIPANT_EVIDENCE_PATH",
            os.path.join(str(tmp_path), "nonexistent.json"),
        )
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance,
            SystemAcceptanceVerdict,
        )
        reset_system_acceptance_evaluator()
        report = evaluate_system_acceptance()
        assert report.verdict != SystemAcceptanceVerdict.fully_operational
        monkeypatch.delenv("ANDROID_PARTICIPANT_EVIDENCE_PATH", raising=False)

    def test_recovered_evidence_yields_accepted(self, tmp_path):
        """Recovered participant → android_participant dimension is accepted."""
        d = _make_valid_evidence(
            participant_status="recovered",
            is_operational=True,
            audit_event_count=2,
            generated_at=_NOW - 60.0,
        )
        p = _write_evidence(str(tmp_path), d)
        recovered_result = ingest_android_participant_evidence(evidence_path=p, _now=_NOW)
        from unittest.mock import patch
        from core.system_final_acceptance_verdict import (
            reset_system_acceptance_evaluator, evaluate_system_acceptance, DimensionStatus,
        )
        with patch(
            "core.system_final_acceptance_verdict._ingest_android_evidence",
            return_value=recovered_result,
        ):
            reset_system_acceptance_evaluator()
            report = evaluate_system_acceptance()
        item = report.checklist["android_participant"]
        assert item.status == DimensionStatus.accepted
