"""
core.cognitive.reflection_engine — Dual-Mode Reflection Engine
===============================================================
PR-25 — Execution-Driven Cognitive Reflection & Verbal Reinforcement

Inspired by Reflexion (Shinn et al., NeurIPS 2023) and PreFlect (2025).

Provides **two reflection modes** that form a complete pre/post-execution
learning loop:

    Prospective Reflection  —  Before execution. Uses historical patterns to
                               predict risks and recommend strategy adjustments.
                               Analogous to PreFlect's pre-mortem analysis.

    Retrospective Reflection — After execution. Compares expected vs actual
                               outcomes, extracts verbal reinforcement notes.
                               Analogous to Reflexion's trial-and-error learning.

Both modes produce **natural-language reflection text** (not structured JSON).
This is intentional — verbal reflections are most effective when injected
into LLM context (Shinn et al. showed 91% HumanEval pass@1 using language
feedback alone).

Integration
-----------
- Subscribes to state event bus TASK_STARTED / TASK_DONE / TASK_FAILED
- Stores reflections in TaskSummary.reflection (appended to TaskMemory)
- Emits `cognitive.reflection` events for downstream PatternMiner consumption
- Triggered automatically by desktop_presence_runtime before/after execute()

Design principles
-----------------
- **Local rule-driven**: No external LLM calls. Reflections generated by
  comparing execution metrics against historical statistics.
- **Contrastive learning**: Explicitly compares success vs failure trajectories
  (ExpeL-style experience extraction).
- **Activation decay**: Each reflection has an activation score that decays
  over time (Soar/ACT-R base-level activation). Stale reflections fade.
- **Verbal output**: Reflection text is human-readable natural language,
  designed for injection into planner/executor context.
"""

from __future__ import annotations

import asyncio
import logging
import re
import threading
import time
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("Galaxy.Cognitive.Reflection")

# ── Constants ────────────────────────────────────────────────────────────

_REFLECTION_EVENT = "cognitive.reflection"
_TASK_MEMORY_RECENCY_WINDOW = 3600.0 * 24 * 7  # 7 days
_PROSPECTIVE_MIN_HISTORY = 3  # min historical records for prospective reflection
_STRATEGY_SUCCESS_THRESHOLD = 0.7  # below this = strategy concern
_DURATION_VARIANCE_THRESHOLD = 3.0  # std/mean ratio flagging unstable timing
_ACTIVATION_DECAY_RATE = 0.95  # per day


# ── Data model ────────────────────────────────────────────────────────────


@dataclass
class ReflectionRecord:
    """A single reflection entry associated with a task execution.

    Attributes
    ----------
    reflection_type:  'prospective' or 'retrospective'
    task_id:          Correlated task identifier (TaskSummary.summary_id)
    task_description: Short text of what the task was about
    reflection_text:  Natural-language reflection (human/LLM readable)
    activation_score: Base-level activation [0.0, 1.0]. Decays daily.
                      High activation = this reflection is still relevant.
    confidence:       How certain the reflection is [0.0, 1.0]
    supporting_evidence: list of historical task_ids that support this reflection
    timestamp:        Unix epoch of creation
    """

    reflection_type: str = "retrospective"
    task_id: str = ""
    task_description: str = ""
    reflection_text: str = ""
    activation_score: float = 1.0
    confidence: float = 0.5
    supporting_evidence: List[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "reflection_type": self.reflection_type,
            "task_id": self.task_id,
            "task_description": self.task_description[:200],
            "reflection_text": self.reflection_text[:2000],
            "activation_score": round(self.activation_score, 4),
            "confidence": round(self.confidence, 4),
            "supporting_evidence": self.supporting_evidence[:10],
            "timestamp": self.timestamp,
        }

    def decay(self, days: float = 1.0) -> None:
        """Decay activation score. Call periodically (e.g., daily)."""
        self.activation_score *= _ACTIVATION_DECAY_RATE ** days
        self.activation_score = max(0.0, min(1.0, self.activation_score))


# ── Reflection Engine ─────────────────────────────────────────────────────


class ReflectionEngine:
    """Dual-mode reflection engine for cognitive learning.

    Usage::

        engine = get_reflection_engine()

        # Before execution — prospective risk analysis
        prospective = engine.reflect_prospective(
            task="check weather for Beijing",
            strategy="single",
        )
        print(prospective.reflection_text)  # "Historical data suggests..."

        # After execution — retrospective outcome analysis
        retrospective = engine.reflect_retrospective(
            task="check weather for Beijing",
            strategy="single",
            success=True,
            duration_ms=1200,
            result_summary="Sunny, 25C",
        )
        print(retrospective.reflection_text)  # "Completed successfully..."
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._reflections: List[ReflectionRecord] = []
        self._subscribed = False
        self._max_reflections = 500

    # ── Public API ──────────────────────────────────────────────────

    def subscribe_to_task_lifecycle(self) -> None:
        """Subscribe to state event bus for automatic reflection triggers."""
        if self._subscribed:
            return
        try:
            from core.state_event_bus import get_state_event_bus, StateEventType

            bus = get_state_event_bus()
            bus.subscribe(StateEventType.TASK_STARTED, self._on_task_started)
            bus.subscribe(StateEventType.TASK_DONE, self._on_task_done)
            bus.subscribe(StateEventType.TASK_FAILED, self._on_task_failed)
            self._subscribed = True
            logger.debug("ReflectionEngine subscribed to task lifecycle events")
        except Exception as exc:
            logger.warning("ReflectionEngine subscription failed (non-fatal): %s", exc)

    def reflect_prospective(
        self,
        task: str,
        strategy: str = "",
        trace_id: Optional[str] = None,
    ) -> ReflectionRecord:
        """Generate prospective (pre-execution) reflection.

        Analyzes historical data for similar tasks to predict risks
        and suggest strategy adjustments before execution begins.

        Parameters
        ----------
        task:       Task description text
        strategy:   Planned strategy (single/specialized/swarm/fractal)
        trace_id:   Optional correlation ID

        Returns
        -------
        ReflectionRecord with reflection_type='prospective'
        """
        try:
            return self._reflect_prospective_impl(task, strategy, trace_id)
        except Exception as exc:
            logger.debug("reflect_prospective failed (non-fatal): %s", exc)
            return self._fallback_reflection("prospective", task, trace_id)

    def reflect_retrospective(
        self,
        task: str,
        strategy: str = "",
        success: bool = True,
        duration_ms: float = 0.0,
        result_summary: str = "",
        expected_result: str = "",
        trace_id: Optional[str] = None,
    ) -> ReflectionRecord:
        """Generate retrospective (post-execution) reflection.

        Compares actual execution against historical patterns and
        expected outcomes. Extracts verbal reinforcement for future use.

        Parameters
        ----------
        task:            Task description text
        strategy:        Strategy that was used
        success:         Whether execution succeeded
        duration_ms:     Wall-clock duration in milliseconds
        result_summary:  Actual result text
        expected_result: Expected result text (if available)
        trace_id:        Optional correlation ID

        Returns
        -------
        ReflectionRecord with reflection_type='retrospective'
        """
        try:
            return self._reflect_retrospective_impl(
                task, strategy, success, duration_ms, result_summary,
                expected_result, trace_id,
            )
        except Exception as exc:
            logger.debug("reflect_retrospective failed (non-fatal): %s", exc)
            return self._fallback_reflection("retrospective", task, trace_id)

    def get_active_reflections(
        self,
        task_hint: str = "",
        min_activation: float = 0.1,
        limit: int = 10,
    ) -> List[ReflectionRecord]:
        """Retrieve relevant reflections above activation threshold.

        Filters by activation score and optional task keyword matching.
        Results sorted by activation_score descending.
        """
        with self._lock:
            candidates = [
                r for r in self._reflections
                if r.activation_score >= min_activation
            ]
            if task_hint:
                hint_lower = task_hint.lower()
                candidates = [
                    r for r in candidates
                    if hint_lower in r.task_description.lower()
                    or hint_lower in r.reflection_text.lower()
                ]
            candidates.sort(key=lambda r: r.activation_score, reverse=True)
            return candidates[:limit]

    def decay_all(self, days: float = 1.0) -> None:
        """Decay activation scores of all stored reflections."""
        with self._lock:
            for r in self._reflections:
                r.decay(days)
            # Remove dead reflections
            before = len(self._reflections)
            self._reflections = [
                r for r in self._reflections if r.activation_score > 0.01
            ]
            after = len(self._reflections)
            if before != after:
                logger.debug(
                    "ReflectionEngine decay: %d → %d reflections",
                    before, after,
                )

    def to_dict_list(self) -> List[Dict[str, Any]]:
        """Export all reflections as JSON-safe list."""
        with self._lock:
            return [r.to_dict() for r in self._reflections]

    # ── Internal: Prospective reflection ────────────────────────────

    def _reflect_prospective_impl(
        self,
        task: str,
        strategy: str,
        trace_id: Optional[str],
    ) -> ReflectionRecord:
        """Internal: generate pre-execution risk analysis."""
        history = self._fetch_similar_history(task, n=20)

        if len(history) < _PROSPECTIVE_MIN_HISTORY:
            return ReflectionRecord(
                reflection_type="prospective",
                task_description=task[:200],
                reflection_text=(
                    f"Insufficient historical data for '{task[:60]}...' "
                    f"(only {len(history)} similar records). Proceeding with "
                    f"default strategy '{strategy or 'single'}'."
                ),
                activation_score=0.3,
                confidence=0.2,
                timestamp=time.time(),
            )

        # Compute statistics
        total = len(history)
        successes = [h for h in history if h.get("success", True)]
        failures = [h for h in history if not h.get("success", True)]
        success_rate = len(successes) / total if total > 0 else 1.0

        durations = [
            h.get("duration_ms", 0) for h in history if h.get("duration_ms", 0) > 0
        ]
        avg_duration = sum(durations) / len(durations) if durations else 0
        std_duration = self._std(durations) if len(durations) > 1 else 0
        duration_variance = std_duration / avg_duration if avg_duration > 0 else 0

        # Strategy effectiveness comparison (contrastive learning)
        strategy_stats = defaultdict(lambda: {"success": 0, "fail": 0, "durations": []})
        for h in history:
            s = h.get("strategy", "unknown")
            if h.get("success", True):
                strategy_stats[s]["success"] += 1
            else:
                strategy_stats[s]["fail"] += 1
            if h.get("duration_ms", 0) > 0:
                strategy_stats[s]["durations"].append(h["duration_ms"])

        # Build reflection text
        parts: List[str] = []
        parts.append(
            f"Prospective analysis for '{task[:80]}': "
            f"{total} historical similar tasks, "
            f"{success_rate*100:.0f}% success rate."
        )

        # Risk warning
        if success_rate < _STRATEGY_SUCCESS_THRESHOLD:
            parts.append(
                f"CAUTION: Historical success rate is only {success_rate*100:.0f}%. "
                f"Consider fallback strategy or human review if result is critical."
            )

        # Timing insight
        if avg_duration > 0:
            parts.append(
                f"Typical duration: {avg_duration:.0f}ms "
                f"(variance: {duration_variance:.2f})."
            )
            if duration_variance > _DURATION_VARIANCE_THRESHOLD:
                parts.append(
                    "Timing is highly variable — consider setting a generous timeout."
                )

        # Strategy recommendation (contrastive)
        if strategy and strategy in strategy_stats:
            planned_rate = self._success_rate(strategy_stats[strategy])
            best_strat = max(
                strategy_stats.keys(),
                key=lambda s: self._success_rate(strategy_stats[s]),
            )
            best_rate = self._success_rate(strategy_stats[best_strat])
            if best_rate > planned_rate + 0.15 and best_strat != strategy:
                parts.append(
                    f"STRATEGY TIP: '{best_strat}' has {best_rate*100:.0f}% success vs "
                    f"'{strategy}' at {planned_rate*100:.0f}%. "
                    f"Consider switching if appropriate."
                )

        # Failure pattern analysis
        if failures:
            fail_reasons = Counter(
                h.get("result_summary", "unknown")[:60] for h in failures
            )
            top_fail = fail_reasons.most_common(1)[0]
            parts.append(
                f"Common failure pattern: '{top_fail[0]}' "
                f"({top_fail[1]} of {len(failures)} failures)."
            )

        reflection_text = " ".join(parts)

        record = ReflectionRecord(
            reflection_type="prospective",
            task_description=task[:200],
            reflection_text=reflection_text,
            activation_score=0.8 if success_rate < 1.0 else 0.5,
            confidence=min(0.9, 0.3 + total * 0.05),
            timestamp=time.time(),
        )

        self._store_reflection(record)
        self._emit_reflection_event(record, trace_id)

        logger.debug(
            "Prospective reflection generated | task=%s strategy=%s "
            "history=%d confidence=%.2f",
            task[:60], strategy, total, record.confidence,
        )
        return record

    # ── Internal: Retrospective reflection ──────────────────────────

    def _reflect_retrospective_impl(
        self,
        task: str,
        strategy: str,
        success: bool,
        duration_ms: float,
        result_summary: str,
        expected_result: str,
        trace_id: Optional[str],
    ) -> ReflectionRecord:
        """Internal: generate post-execution outcome analysis."""
        history = self._fetch_similar_history(task, n=10)
        avg_duration = (
            sum(h.get("duration_ms", 0) for h in history) / len(history)
            if history else 0
        )

        parts: List[str] = []
        parts.append(
            f"Retrospective for '{task[:80]}': "
            f"strategy='{strategy}', success={success}."
        )

        if success:
            # Success analysis
            if avg_duration > 0 and duration_ms > avg_duration * 2:
                parts.append(
                    f"SLOW: Took {duration_ms:.0f}ms vs typical {avg_duration:.0f}ms. "
                    f"Consider investigating performance degradation."
                )
            elif avg_duration > 0 and duration_ms < avg_duration * 0.5:
                parts.append(
                    f"FAST: Completed in {duration_ms:.0f}ms vs typical {avg_duration:.0f}ms. "
                    f"Good conditions — note what worked well."
                )
            else:
                parts.append(f"Completed in {duration_ms:.0f}ms within normal range.")

            if result_summary:
                parts.append(f"Result: {result_summary[:100]}.")

            # Compare with historical failures (contrastive)
            failures = [h for h in history if not h.get("success", True)]
            if failures:
                parts.append(
                    f"Success achieved where {len(failures)} previous attempts failed. "
                    f"Key difference likely: strategy='{strategy}', "
                    f"stable execution conditions."
                )
        else:
            # Failure analysis
            parts.append(
                f"FAILED after {duration_ms:.0f}ms. "
                f"Result: {result_summary[:120]}."
            )
            if expected_result:
                parts.append(f"Expected: {expected_result[:120]}.")

            # Historical success contrast
            successes = [h for h in history if h.get("success", True)]
            if successes:
                success_strats = Counter(h.get("strategy", "") for h in successes)
                best_strat = success_strats.most_common(1)[0][0] if success_strats else ""
                if best_strat and best_strat != strategy:
                    parts.append(
                        f"HINT: '{best_strat}' succeeded {success_strats[best_strat]} times "
                        f"for similar tasks. Current '{strategy}' may be suboptimal."
                    )

            # Identify potential root cause
            if duration_ms < 500:
                parts.append("Quick failure suggests input validation or permission issue.")
            elif duration_ms > 30000:
                parts.append("Timeout failure — check external dependencies or network.")

        reflection_text = " ".join(parts)

        # Compute activation based on insight value
        activation = 0.9 if not success else 0.5
        if avg_duration > 0:
            duration_deviation = abs(duration_ms - avg_duration) / avg_duration
            activation = min(1.0, activation + duration_deviation * 0.2)

        record = ReflectionRecord(
            reflection_type="retrospective",
            task_description=task[:200],
            reflection_text=reflection_text,
            activation_score=activation,
            confidence=0.7 if history else 0.4,
            timestamp=time.time(),
        )

        self._store_reflection(record)
        self._emit_reflection_event(record, trace_id)

        logger.debug(
            "Retrospective reflection generated | task=%s success=%s "
            "activation=%.2f",
            task[:60], success, activation,
        )
        return record

    # ── Internal helpers ────────────────────────────────────────────

    def _fetch_similar_history(
        self, task: str, n: int = 10
    ) -> List[Dict[str, Any]]:
        """Fetch similar historical tasks from TaskMemory."""
        try:
            from core.task_memory import get_task_memory

            tm = get_task_memory()
            recent = tm.get_recent_summaries(n=n * 2)
            if not recent:
                return []

            # Simple keyword matching for similarity
            task_words = set(self._tokenize(task))
            scored = []
            for summary in recent:
                candidate_words = set(
                    self._tokenize(summary.task)
                    + self._tokenize(summary.task_type)
                )
                overlap = len(task_words & candidate_words)
                score = overlap / max(len(task_words), 1)
                scored.append((score, summary))

            scored.sort(key=lambda x: x[0], reverse=True)
            top = scored[:n]

            return [
                {
                    "task": s.task,
                    "success": s.success,
                    "strategy": s.strategy,
                    "duration_ms": s.duration_ms,
                    "result_summary": s.result_summary,
                    "task_type": s.task_type,
                    "timestamp": s.timestamp,
                    "summary_id": s.summary_id,
                }
                for _, s in top
            ]
        except Exception as exc:
            logger.debug("_fetch_similar_history failed: %s", exc)
            return []

    @staticmethod
    def _tokenize(text: str) -> List[str]:
        """Simple tokenization for similarity matching."""
        return re.findall(r"[a-zA-Z\u4e00-\u9fff]+", text.lower())

    @staticmethod
    def _std(values: List[float]) -> float:
        """Population standard deviation."""
        if len(values) < 2:
            return 0.0
        mean = sum(values) / len(values)
        variance = sum((x - mean) ** 2 for x in values) / len(values)
        return variance ** 0.5

    @staticmethod
    def _success_rate(stats: Dict[str, Any]) -> float:
        """Compute success rate from strategy stats dict."""
        total = stats["success"] + stats["fail"]
        return stats["success"] / total if total > 0 else 0.0

    def _store_reflection(self, record: ReflectionRecord) -> None:
        """Store reflection with capacity management."""
        with self._lock:
            self._reflections.append(record)
            if len(self._reflections) > self._max_reflections:
                # Remove lowest activation reflections
                self._reflections.sort(key=lambda r: r.activation_score)
                cutoff = self._max_reflections // 10  # remove bottom 10%
                self._reflections = self._reflections[cutoff:]

    def _emit_reflection_event(
        self, record: ReflectionRecord, trace_id: Optional[str]
    ) -> None:
        """Emit reflection event on state event bus."""
        try:
            from core.state_event_bus import get_state_event_bus

            get_state_event_bus().publish(
                _REFLECTION_EVENT,
                source="reflection_engine",
                payload=record.to_dict(),
                trace_id=trace_id or f"refl_{int(time.time()*1000)%10**9}",
            )
        except Exception as exc:
            logger.debug("Reflection event emission failed (non-fatal): %s", exc)

    def _fallback_reflection(
        self,
        reflection_type: str,
        task: str,
        trace_id: Optional[str],
    ) -> ReflectionRecord:
        """Return a safe fallback reflection when main logic fails."""
        return ReflectionRecord(
            reflection_type=reflection_type,
            task_description=task[:200],
            reflection_text=f"{reflection_type.capitalize()} reflection unavailable — "
                           "proceeding with default execution strategy.",
            activation_score=0.1,
            confidence=0.0,
            timestamp=time.time(),
        )

    # ── Event bus callbacks ─────────────────────────────────────────

    def _on_task_started(self, event: Any) -> None:
        """Auto-trigger prospective reflection when task starts."""
        try:
            payload = getattr(event, "payload", {}) or {}
            task = str(payload.get("task", ""))
            strategy = str(payload.get("strategy", ""))
            trace_id = getattr(event, "trace_id", "") or ""
            if task:
                self.reflect_prospective(task, strategy, trace_id)
        except Exception as exc:
            logger.debug("_on_task_started error (non-fatal): %s", exc)

    def _on_task_done(self, event: Any) -> None:
        """Auto-trigger retrospective reflection when task completes."""
        try:
            payload = getattr(event, "payload", {}) or {}
            task = str(payload.get("task", ""))
            strategy = str(payload.get("strategy", ""))
            success = bool(payload.get("success", True))
            duration_ms = float(payload.get("duration_ms", 0))
            result_summary = str(payload.get("result_summary", ""))
            trace_id = getattr(event, "trace_id", "") or ""
            if task:
                self.reflect_retrospective(
                    task, strategy, success, duration_ms,
                    result_summary, trace_id=trace_id,
                )
        except Exception as exc:
            logger.debug("_on_task_done error (non-fatal): %s", exc)

    def _on_task_failed(self, event: Any) -> None:
        """Auto-trigger retrospective reflection on failure."""
        self._on_task_done(event)


# ── Singleton accessors ───────────────────────────────────────────────────

_engine_instance: Optional[ReflectionEngine] = None
_engine_lock = threading.Lock()


def get_reflection_engine() -> ReflectionEngine:
    """Return the process-wide ReflectionEngine singleton."""
    global _engine_instance
    if _engine_instance is None:
        with _engine_lock:
            if _engine_instance is None:
                _engine_instance = ReflectionEngine()
                _engine_instance.subscribe_to_task_lifecycle()
                logger.debug("ReflectionEngine singleton initialised")
    return _engine_instance


def reset_reflection_engine() -> None:
    """Reset singleton (for testing only)."""
    global _engine_instance
    with _engine_lock:
        _engine_instance = None
