#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
scripts/cross_device_task_demo.py
==================================
PR-5 Capability 4 — Cross-Device / Cross-App Orchestration Demo

Demonstrates multi-device, multi-target task orchestration:
  - Device A (local)   : generate a file artifact
  - Device B (remote)  : process / retrieve the artifact
  - Orchestrator       : coordinate both with TaskEnvelope multi-target routing

This demo runs in standalone mode without live device connections by using
mock device executors.  The orchestration logic (TaskEnvelope multi-target
dispatch, result aggregation, memory backflow) is real.

Run::

    python scripts/cross_device_task_demo.py
"""

from __future__ import annotations

import asyncio
import logging
import os
import sys
import tempfile
from typing import Any, Dict, List

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)
logger = logging.getLogger("Demo.CrossDevice")

from core.schemas.task_envelope import TaskEnvelope
from core.task_lifecycle import TaskLifecycleManager

mgr = TaskLifecycleManager()


# ---------------------------------------------------------------------------
# Mock device executors (stand-in for real WebSocket-connected devices)
# ---------------------------------------------------------------------------

class MockDevice:
    """Simulates a remote device that executes tasks."""

    def __init__(self, device_id: str, capabilities: List[str]):
        self.device_id = device_id
        self.capabilities = capabilities
        self._results: Dict[str, Any] = {}

    async def execute(self, envelope: TaskEnvelope) -> Dict[str, Any]:
        """Execute the task described by *envelope*."""
        logger.info(
            "[%s] executing tool=%s task_id=%s",
            self.device_id, envelope.tool_name, envelope.task_id,
        )
        await asyncio.sleep(0.05)  # simulate network latency

        if envelope.tool_name == "generate_artifact":
            artifact_path = os.path.join(
                tempfile.gettempdir(),
                f"galaxy_artifact_{envelope.task_id}.txt",
            )
            with open(artifact_path, "w") as f:
                f.write(f"Artifact from {self.device_id}: {envelope.args}\n")
            self._results["artifact_path"] = artifact_path
            return {"success": True, "artifact_path": artifact_path, "device": self.device_id}

        if envelope.tool_name == "process_artifact":
            path = envelope.args.get("artifact_path", "")
            if path and os.path.isfile(path):
                with open(path) as f:
                    content = f.read().strip()
                os.unlink(path)  # cleanup
                return {"success": True, "processed": content, "device": self.device_id}
            return {"success": False, "error": f"artifact not found: {path}", "device": self.device_id}

        return {"success": True, "echo": envelope.args, "device": self.device_id}


# ---------------------------------------------------------------------------
# Multi-device orchestrator (capability 4)
# ---------------------------------------------------------------------------

class CrossDeviceOrchestrator:
    """Demonstrates PR-5 Capability 4: multi-target task dispatch.

    Each sub-task uses a separate TaskEnvelope with its own lifecycle.
    Results are aggregated and written to TaskMemory by the lifecycle manager.
    """

    def __init__(self, devices: Dict[str, MockDevice]) -> None:
        self._devices = devices

    async def run_pipeline(
        self,
        session_id: str,
        trace_id: str,
    ) -> Dict[str, Any]:
        """Run a two-device pipeline:
          1. device_a: generate artifact
          2. device_b: process artifact generated by device_a
        """
        print("\n── Phase 1: device_a — generate artifact ──")
        env_a = TaskEnvelope(
            tool_name="generate_artifact",
            args={"content": "hello from device_a", "format": "text"},
            source="orchestrator",
            targets=["device_a"],
            session_id=session_id,
            trace_id=trace_id,
            required_capabilities=["filesystem"],
        )
        print(f"  env_a task_id={env_a.task_id}  targets={env_a.targets}")

        result_a = await self._dispatch(env_a, "device_a")
        if not result_a.get("success"):
            return {"success": False, "phase": "generate_artifact", "error": result_a}

        artifact_path = result_a.get("artifact_path", "")
        print(f"  artifact_path={artifact_path}")

        print("\n── Phase 2: device_b — process artifact ──")
        env_b = TaskEnvelope(
            tool_name="process_artifact",
            args={"artifact_path": artifact_path},
            source="orchestrator",
            targets=["device_b"],
            session_id=session_id,
            trace_id=trace_id,
            required_capabilities=["filesystem"],
        )
        print(f"  env_b task_id={env_b.task_id}  targets={env_b.targets}")

        result_b = await self._dispatch(env_b, "device_b")
        return {
            "success": result_b.get("success", False),
            "device_a_result": result_a,
            "device_b_result": result_b,
        }

    async def _dispatch(self, envelope: TaskEnvelope, device_id: str) -> Dict[str, Any]:
        """Dispatch a single envelope to *device_id* with lifecycle tracking."""
        device = self._devices.get(device_id)
        if device is None:
            return {"success": False, "error": f"device not found: {device_id}"}

        envelope = mgr.mark_running(envelope)
        print(f"  lifecycle={envelope.lifecycle_status}")
        try:
            result = await device.execute(envelope)
            summary = str(result)[:120]
            envelope = mgr.mark_done(envelope, result_summary=summary)
            print(f"  lifecycle={envelope.lifecycle_status}")
            return result
        except Exception as exc:
            envelope = mgr.mark_failed(envelope, error=str(exc))
            print(f"  lifecycle={envelope.lifecycle_status}  error={exc}")
            return {"success": False, "error": str(exc)}


# ---------------------------------------------------------------------------
# Main demo
# ---------------------------------------------------------------------------

async def run_demo():
    print("\n" + "=" * 60)
    print("PR-5 Capability 4: Cross-Device Orchestration Demo")
    print("=" * 60)

    devices = {
        "device_a": MockDevice("device_a", ["screen", "filesystem", "keyboard"]),
        "device_b": MockDevice("device_b", ["filesystem", "http_client"]),
    }
    orch = CrossDeviceOrchestrator(devices)

    pipeline_result = await orch.run_pipeline(
        session_id="demo_session_crossdevice_001",
        trace_id="trace_crossdevice_demo",
    )

    print("\n" + "=" * 60)
    print(f"Pipeline success: {pipeline_result['success']}")
    if pipeline_result.get("device_a_result"):
        print(f"  device_a: {pipeline_result['device_a_result']}")
    if pipeline_result.get("device_b_result"):
        print(f"  device_b: {pipeline_result['device_b_result']}")

    if pipeline_result["success"]:
        print("\n✅ Cross-device pipeline completed successfully.")
    else:
        print("\n❌ Cross-device pipeline failed.")

    return pipeline_result["success"]


if __name__ == "__main__":
    ok = asyncio.run(run_demo())
    sys.exit(0 if ok else 1)
