#!/usr/bin/env python3
"""scripts/gen_ts_types.py — Pydantic 模型 → TypeScript 类型(单一真相源,去前后端漂移)

把 core.schemas.ui_element 的结构化 UI 契约(UISource/UIActionKind/UIBounds/
UIElementNode/UIGraph)导出成 TS,供 Electron 面板消费 ui_graph 时类型安全 ——
后端改字段、前端立刻类型报错,不再靠手写 interface 悄悄漂移。

只覆盖 ui_element 这一组(结构清晰、被前端消费);不做通用 Pydantic→TS 转换器
(那会引入一堆边角复杂度)。重跑本脚本即可再生成。
"""
from __future__ import annotations

import enum
import os
import sys
import typing
from typing import get_args, get_origin

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pydantic import BaseModel

import core.schemas.ui_element as ui


_ENUMS = [ui.UISource, ui.UIActionKind]
_MODELS = [ui.UIBounds, ui.UIElementNode, ui.UIGraph]

_SCALAR = {str: "string", int: "number", float: "number", bool: "boolean"}


def _ts_type(ann: typing.Any) -> str:
    """Python 类型注解 → TS 类型字符串。"""
    if ann in _SCALAR:
        return _SCALAR[ann]
    if isinstance(ann, type) and issubclass(ann, enum.Enum):
        return ann.__name__
    if isinstance(ann, type) and issubclass(ann, BaseModel):
        return ann.__name__

    origin = get_origin(ann)
    args = get_args(ann)
    if origin in (list, typing.List):
        return f"{_ts_type(args[0])}[]"
    if origin in (dict, typing.Dict):
        return "Record<string, unknown>"
    # Optional[X] / Union[X, None]
    if origin is typing.Union:
        non_none = [a for a in args if a is not type(None)]
        inner = " | ".join(_ts_type(a) for a in non_none)
        return f"{inner} | null" if len(args) > len(non_none) else inner
    if ann is typing.Any or ann is object:
        return "unknown"
    return "unknown"


def _emit_enum(e: type) -> str:
    members = " | ".join(f'"{m.value}"' for m in e)
    return f"export type {e.__name__} = {members};"


def _emit_model(m: type) -> str:
    lines = [f"export interface {m.__name__} {{"]
    for name, field in m.model_fields.items():
        ts = _ts_type(field.annotation)
        # 有默认值 / Optional → 可选字段
        optional = (not field.is_required()) or ts.endswith("| null")
        q = "?" if optional else ""
        lines.append(f"  {name}{q}: {ts};")
    lines.append("}")
    return "\n".join(lines)


def build() -> str:
    parts = [
        "// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.",
        "// 源:core/schemas/ui_element.py(结构化 UI 契约 SSOT)。改后端字段后重跑该脚本。",
        "",
    ]
    parts += [_emit_enum(e) for e in _ENUMS]
    parts.append("")
    parts += [_emit_model(m) for m in _MODELS]
    parts.append("")
    return "\n".join(parts)


if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "electron", "renderer", "panel", "src", "types", "ui_element.gen.ts")
    with open(out, "w", encoding="utf-8") as f:
        f.write(build())
    print(f"wrote {out}")
