#!/usr/bin/env python3
"""scripts/gen_ts_types.py — 后端契约 → TypeScript 类型(单一真相源,去前后端漂移)

后端改字段、前端立刻类型报错,不再靠手写 interface 悄悄漂移。

覆盖两组契约,各写各的文件:

* ``core.schemas.ui_element``  → ``types/ui_element.gen.ts``
  结构化 UI 契约(UISource/UIActionKind/UIBounds/UIElementNode/UIGraph)。

* ``core.api_routes``          → ``types/api.gen.ts``
  **整个权威 API 层**(388 条路径 / 406 个操作 / 102 个组件 schema),直接从
  FastAPI 的 OpenAPI 出。此前这个脚本只覆盖两组手写 schema 的契约,而前端要用
  哪个端点、参数长什么样、返回什么,全靠人对着后端源码抄 —— 面板只用了其中
  20 条,剩下的对前端来说是**不可发现**的。现在路径本身成为一个 TS 联合类型:
  调一个不存在的端点、或对某路径用了它不支持的方法,``tsc`` 直接报错。

* ``core.phase_contract``      → ``types/phase_contract.gen.ts``
  面板侧相位姿态:离散三态 + 后端一直在算的连续量(在场强度/塌缩与回撤倾向/
  稳定度)。加这一组的起因是:那些连续量在 ContinuumState 里算了很久,却在
  在场桥那一步被三个硬编码常数顶掉,前端从来没见过。既然要送出去,类型就该
  从后端生成,而不是前端再手写一份 —— 那正是这个脚本存在的理由。

不做通用 Pydantic→TS 转换器(那会引入一堆边角复杂度)。重跑本脚本即可再生成。
"""

from __future__ import annotations

import enum
import json
import os
import sys
import typing
from typing import get_args, get_origin

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pydantic import BaseModel

import core.phase_contract as phase_contract
import core.schemas.ui_element as ui

_ENUMS = [ui.UISource, ui.UIActionKind]
_MODELS = [ui.UIBounds, ui.UIElementNode, ui.UIGraph]

_SCALAR = {str: "string", int: "number", float: "number", bool: "boolean"}


def _ts_type(ann: typing.Any) -> str:
    """Python 类型注解 → TS 类型字符串。"""
    if ann in _SCALAR:
        return _SCALAR[ann]
    if isinstance(ann, type) and issubclass(ann, enum.Enum):
        return ann.__name__
    if isinstance(ann, type) and issubclass(ann, BaseModel):
        return ann.__name__

    origin = get_origin(ann)
    args = get_args(ann)
    if origin in (list, typing.List):
        return f"{_ts_type(args[0])}[]"
    if origin in (dict, typing.Dict):
        return "Record<string, unknown>"
    # Optional[X] / Union[X, None]
    if origin is typing.Union:
        non_none = [a for a in args if a is not type(None)]
        inner = " | ".join(_ts_type(a) for a in non_none)
        return f"{inner} | null" if len(args) > len(non_none) else inner
    if ann is typing.Any or ann is object:
        return "unknown"
    return "unknown"


def _emit_enum(e: type) -> str:
    members = " | ".join(f'"{m.value}"' for m in e)
    return f"export type {e.__name__} = {members};"


def _emit_model(m: type) -> str:
    lines = [f"export interface {m.__name__} {{"]
    for name, field in m.model_fields.items():
        ts = _ts_type(field.annotation)
        # 有默认值 / Optional → 可选字段
        optional = (not field.is_required()) or ts.endswith("| null")
        q = "?" if optional else ""
        lines.append(f"  {name}{q}: {ts};")
    lines.append("}")
    return "\n".join(lines)


def build_phase_contract() -> str:
    """相位契约 → TS。

    这一组不是 Pydantic 模型而是 dataclass + 一份显式 schema 描述
    (``phase_contract_schema()``),因为生成器需要的信息比 JSON Schema 更具体:
    哪些字段是 [0,1] 归一量、``source`` 的取值域是什么。手写那份描述比让
    生成器去猜可靠。

    锚点常量也一并导出:前端做过渡编排时要知道三档各在深度轴的哪个位置,
    此前那三个数在 TS 侧是另写一份的,改后端就会漂。
    """
    sch = phase_contract.phase_contract_schema()
    lines = [
        "// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.",
        "// 源:core/phase_contract.py(面板侧相位契约 SSOT)。改后端字段后重跑该脚本。",
        "",
        "/**",
        " * 后端【线上】传输的三态 token。",
        " *",
        " * 刻意不叫 `Phase`：面板自己的 `types/phase.ts` 里已有一个 `Phase`,",
        " * 取值是 'silent' | 'liminal' | 'manifest'（展示词汇），而后端发的是",
        " * 'static'（见 core/desktop_presence_system.py 的 STATIC）。两者同名不同义，",
        " * 一起 import 会撞。转换由 usePhase.ts 的 _mapPhaseToken 负责。",
        " *",
        " * 连续量只描述它在这一档里的位置，不改变是哪一档。",
        " */",
        "export type WirePhase = " + " | ".join(f'"{p}"' for p in sch["phases"]) + ";",
        "",
        "/** depth 是实算的还是锚点兜底。前端可据此区分精确态/估计态。 */",
        "export type PhasePostureSource = " + " | ".join(f'"{s}"' for s in sch["sources"]) + ";",
        "",
        "/** 三态在渲染深度轴上的锚点。前端过渡编排按这几个数调。 */",
        "export const PHASE_ANCHORS: Record<WirePhase, number> = {",
    ]
    for name, val in sch["anchors"].items():
        lines.append(f'  "{name}": {val},')
    lines += [
        "};",
        "",
        "/** 边缘混合上限:倾向为 1 时深度最多向邻档漂移两档间距的这个比例。 */",
        f"export const PHASE_EDGE_BLEND = {sch['edge_blend']};",
        "",
        "export interface PhasePosture {",
    ]
    for f in sch["fields"]:
        lines.append(f"  /** {f['doc']} */")
        lines.append(f"  {f['name']}: {f['ts']};")
    lines += ["}", ""]
    lines += _render_contract_lines()
    return "\n".join(lines)


def _render_contract_lines() -> list:
    """忠实契约 → TS，追加在遗留投影之后（同一个 .gen.ts）。

    刻意与 ``PhasePosture`` 同文件：两者是同一件事的两个版本，放一起才能让读到
    遗留类型的人立刻看见「还有一个更忠实的」，而不是各自散在两个文件里。
    """
    sch = phase_contract.render_contract_schema()
    out = [
        "",
        "// ═══════════════════════════════════════════════════════════════════",
        "// 忠实契约：按 core/continuum 的实际形状生成",
        "//",
        "// 上面的 PhasePosture 是一维遗留投影（三锚点串在一条 depth 轴上），保留",
        "// 只为兼容既有覆盖层 presence_motion.js。**新代码应当消费 RenderPosture。**",
        "//",
        "// 差别是结构性的，不是字段多少：",
        "//   · 四相 vs 三态 —— receding（返回弧）在遗留投影里被折叠成 silent，",
        "//     于是「刚做完正在退场」与「静息」在渲染端不可分辨；",
        "//   · 二维 vs 一维 —— runtime_domain（在哪儿跑）遗留投影里完全没有；",
        "//   · retreat_tendency 的语义 —— 后端原文是「推向 receding」，遗留投影",
        "//     把它当成「退回上一档」，那会表达出转移表明令禁止的 manifest→liminal。",
        "// ═══════════════════════════════════════════════════════════════════",
        "",
        "/**",
        " * 【主轴】主体生命周期（后端 TriState）——渲染端的整体编排跟这一根走。",
        " *",
        " * 它就是用户能直接感知的节奏：休息 / 过渡 / 对外表达。在场桥广播的",
        " * `payload.phase` 一直是这一根。",
        " */",
        "export type Lifecycle = " + " | ".join(f'"{p}"' for p in sch["lifecycle_states"]) + ";",
        "",
        "/**",
        " * 【副轴】内部连续体四相 —— 提供主轴给不出的纹理，不决定整体编排。",
        " *",
        " * 比主轴多一相 `receding`（返回弧）。主轴回到 `silent` 时，靠副轴才能",
        " * 区分「刚做完正在消散」(receding) 与「静息」(formless)。",
        " */",
        "export type RenderPhase = " + " | ".join(f'"{p}"' for p in sch["phases"]) + ";",
        "",
        "/** 阈限态里正在发生什么。主轴说「在过渡」，这一项说「过渡里在干嘛」。 */",
        "export type LiminalActivity = " + " | ".join(f'"{a}"' for a in sch["liminal_activities"]) + ";",
        "",
        "/** 沙盘推演的种类。 */",
        "export type SimulationKind = " + " | ".join(f'"{k}"' for k in sch["simulation_kinds"]) + ";",
        "",
        "/**",
        " * 阈限态沙盘推演摘要 —— **阈限态的可视内容**。",
        " *",
        " * 阈限态在面板上一直「什么都没有」，根因不是动画简陋，是这一层从没送出来过：",
        " * 智能体在真正落手之前会先在影子沙盘里推演若干条候选路径（见后端",
        " * core/liminal_rehearsal.py），`candidate_paths` 就是它正在权衡的那几条，",
        " * `committed_path` 是最终提交的那条。",
        " */",
        "export interface SimulationSummary {",
    ]
    for f in sch["simulation_fields"]:
        out.append(f"  /** {f['doc']} */")
        out.append(f"  {f['name']}: {f['ts']};")
    out += [
        "}",
        "",
        "/** 三态公共投影。仅供必须使用公共词汇的消费者；用它画图会丢掉返回弧。 */",
        "export type WirePhaseTri = " + " | ".join(f'"{p}"' for p in sorted(set(sch["tri_state_map"].values()))) + ";",
        "",
        "/** 第二维：执行发生在哪儿。 */",
        "export type RuntimeDomain = " + " | ".join(f'"{d}"' for d in sch["runtime_domains"]) + ";",
        "",
        "/** 形态提示（后端 ExpressionEngine 算出，非前端推导）。 */",
        "export type FormSignature = " + " | ".join(f'"{s}"' for s in sch["form_signatures"]) + ";",
        "",
        "/** 抽象空间权重／贴近度。 */",
        "export type SpatialPresence = " + " | ".join(f'"{s}"' for s in sch["spatial_presences"]) + ";",
        "",
        "/** 执行链的种类。决定 ExecutionChainView.last_target 指的是任务还是设备。 */",
        "export type ChainKind = " + " | ".join(f'"{k}"' for k in sch["chain_kinds"]) + ";",
        "",
        "/** 表达期用什么手法动手。none = 尚未决策。 */",
        "export type HybridExecutionMode = " + " | ".join(f'"{m}"' for m in sch["hybrid_execution_modes"]) + ";",
        "",
        "/** 「这一维接没接上」。unwired = 这条链路还没建，不是「零个」。 */",
        "export type ViewSource = " + " | ".join(f'"{s}"' for s in sch["world_model_sources"]) + ";",
        "",
        "/** 世界模型视图的来源。与 ViewSource 同一份取值域（后端是别名，不是副本）。 */",
        "export type WorldModelSource = ViewSource;",
        "",
        "/** 感知模态。四条恒定存在，缺席的那条以 unavailable 出现而不是从数组里消失。 */",
        "export type PerceptionModality = " + " | ".join(f'"{m}"' for m in sch["perception_modalities"]) + ";",
        "",
        "/**",
        " * 单个模态的状态。**刻意不是布尔** —— 布尔会把三件不同的事压成一件，",
        " * 而那正是深度轴犯过的错（20 个字段压成一个标量，退场只能把进场倒放）。",
        " *",
        " *   unavailable  这条通路从没来过东西（没硬件／没授权／前端没在推）→ 这一侧不亮",
        " *   paused       用户按了隐私暂停 → 明确地「闭着」，不是「没有」",
        " *   suppressed   在，但这一拍被刻意屏蔽 → 短暂闭合，不是熄灭",
        " *   idle         通路通、有过信号，但这一拍静了 → 柔和呼吸",
        " *   live         这一拍有新鲜信号 → 有反应",
        " *",
        " * `suppressed` 是反自激励：AI 朗读时麦克风采到的是它自己的声音，自发注意力",
        " * 循环刻意忽略那段音频。这一档把「说话时不能显示在听」从**渲染端要记的规矩**",
        " * 变成**后端给的状态** —— 规矩会被忘记，状态不会。",
        " */",
        "export type ModalityState = " + " | ".join(f'"{s}"' for s in sch["modality_states"]) + ";",
        "",
        "/** 自发注意力上一拍的决策。none = 还没决策过。 */",
        "export type AmbientAction = " + " | ".join(f'"{a}"' for a in sch["ambient_actions"]) + ";",
        "",
        "/** 一个感知模态的当前状态。第一态「哪侧亮、亮多少、是闭着还是没有」全靠这一层。 */",
        "export interface ModalityView {",
    ]
    for f in sch["modality_fields"]:
        out.append(f"  /** {f['doc']} */")
        out.append(f"  {f['name']}: {f['ts']};")
    out += [
        "}",
        "",
        "/**",
        " * **第一态的主体** —— 原生多模态摄入此刻的样子。",
        " *",
        " * 第一态的定义本身就是感知：后端 TriStatePhase.SILENT 的原文是「the system is",
        " * always alive in silent; it is receiving inputs (audio, visual, touch, text) from",
        " * its native modalities」。而在这一层之前，RenderPosture 里**一个感知字段都没有** ——",
        " * 感知状态走的是另一条平行的、无类型的分支 `payload.ambient`：面板手写类型读了它，",
        " * 覆盖层一次都没读过。也就是说第一态的视觉主体在渲染端没有数据来源。",
        " *",
        " * 它**不随相位裁剪**，而且恰恰是主轴 silent 时最要紧 —— 第一态是「在场但不表达」，",
        " * 没有这一层它就退化成「睡着」。",
        " */",
        "export interface PerceptionView {",
    ]
    for f in sch["perception_fields"]:
        out.append(f"  /** {f['doc']} */")
        out.append(f"  {f['name']}: {f['ts']};")
    out += [
        "}",
        "",
        "/**",
        " * 主轴上最近一次转移的**性质** —— 退场编排该看这一位。",
        " *",
        " * 覆盖层此前唯一的依据是一个标量深度，深度从 manifest 走回 silent 时，画面上",
        " * 放的就是进场动画倒着播。这个类型把「刚才发生的是哪一种转移」变成显式事实。",
        " *",
        " * `handoff` 与 `dissolving` **都是合法出口**：前者是「这一轮结果已提交、还有",
        " * 后续」（在场层 core/desktop_presence_system.py 的 MANIFEST→LIMINAL 策略），",
        " * 后者是「做完就散」。它们在不同的轴上，不是同一件事的两种说法 —— 所以渲染端",
        " * 按实际收到的这一位编排，不必也不该预先选定一条退场路线。",
        " */",
        "export type TransitionKind = " + " | ".join(f'"{k}"' for k in sch["transition_kinds"]) + ";",
        "",
        "/**",
        " * 阈限空间三类内容里的**执行链**那两类。",
        " *",
        " * core/liminal_space_mapping.py 把阈限空间定义为「运行时的空间执行场」，装三类",
        " * 内容：本机执行链、跨设备执行链、沙盘推演。`is_active === false` 表示**这条链",
        " * 还没跑过**，不是「没有这条链」—— 零态本身是有意义的信号。",
        " */",
        "export interface ExecutionChainView {",
    ]
    for f in sch["chain_fields"]:
        out.append(f"  /** {f['doc']} */")
        out.append(f"  {f['name']}: {f['ts']};")
    out += [
        "}",
        "",
        "/**",
        " * 表达期用什么手法在动手（直接调 API / 操作界面 / 看截图推理 / 混合）。",
        " *",
        " * 后端 core/hybrid_execution_policy.py 早就把它显式化了，但那个决策此前在",
        " * core/ 之外零消费方 —— 系统知道自己正在并行赛跑还是分阶段混合，却从没对外",
        " * 说过一个字。`is_decided === false` 与「决定了但没给理由」可区分。",
        " */",
        "export interface HybridExecutionView {",
    ]
    for f in sch["hybrid_fields"]:
        out.append(f"  /** {f['doc']} */")
        out.append(f"  {f['name']}: {f['ts']};")
    out += [
        "}",
        "",
        "/**",
        " * 世界模型在阈限空间里的位置 —— **目前是留出的位置，`is_wired` 恒为 false**。",
        " *",
        " * enhancements/reasoning/world_model.py 是存在的，但没有通向渲染层的投影通路。",
        " * 这里显式区分 `unwired`（链路还没建）与 `live`（建好了，数就是这个），于是前端",
        " * 一次写对：链路接上时只有后端的构造函数需要改，前端判断不用动。",
        " */",
        "export interface WorldModelView {",
    ]
    for f in sch["world_model_fields"]:
        out.append(f"  /** {f['doc']} */")
        out.append(f"  {f['name']}: {f['ts']};")
    out += [
        "}",
        "",
        "/** (上一档, 当前档) → 转移性质。缺失的组合按 `none` 处理。 */",
        "export const TRANSITION_KIND_OF: " "ReadonlyArray<{from: Lifecycle; to: Lifecycle; kind: TransitionKind}> = [",
    ]
    for item in sch["transition_kind_of"]:
        out.append(f'  {{ from: "{item["from"]}", to: "{item["to"]}", kind: "{item["kind"]}" }},')
    out += [
        "];",
        "",
        "/**",
        " * 相位之间【允许】的转移，源自 docs/PHASE_TRANSITION_TABLE.md。",
        " *",
        " * 渲染端据此可提前编排：处在 manifest 时唯一出口是 receding，所以退场动作",
        " * 该按「消散」准备，绝不是「退回 liminal」。",
        " */",
        "export const PHASE_TRANSITIONS: Record<RenderPhase, RenderPhase[]> = {",
    ]
    for name, nxt in sch["transitions"].items():
        out.append(f'  "{name}": [{", ".join(chr(34) + n + chr(34) for n in nxt)}],')
    out += [
        "};",
        "",
        "/** 明令禁止的转移 + 理由。渲染端不该为它们编排动作。 */",
        "export const FORBIDDEN_TRANSITIONS: ReadonlyArray<{from: RenderPhase; to: RenderPhase; why: string}> = [",
    ]
    for item in sch["forbidden"]:
        out.append(f'  {{ from: "{item["from"]}", to: "{item["to"]}", why: "{item["why"]}" }},')
    out += [
        "];",
        "",
        "/** 四相 → 三态的公共投影表。 */",
        "export const TRI_STATE_OF: Record<RenderPhase, WirePhaseTri> = {",
    ]
    for k, v in sch["tri_state_map"].items():
        out.append(f'  "{k}": "{v}",')
    out += ["};", "", "export interface RenderPosture {"]
    for f in sch["fields"]:
        out.append(f"  /** {f['doc']} */")
        out.append(f"  {f['name']}: {f['ts']};")
    out += ["}", ""]
    return out


def build() -> str:
    parts = [
        "// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.",
        "// 源:core/schemas/ui_element.py(结构化 UI 契约 SSOT)。改后端字段后重跑该脚本。",
        "",
    ]
    parts += [_emit_enum(e) for e in _ENUMS]
    parts.append("")
    parts += [_emit_model(m) for m in _MODELS]
    parts.append("")
    return "\n".join(parts)


def _write(root: str, filename: str, content: str) -> str:
    out = os.path.join(root, "electron", "renderer", "panel", "src", "types", filename)
    with open(out, "w", encoding="utf-8") as f:
        f.write(content)
    return out


# ---------------------------------------------------------------------------
# OpenAPI → TS(整个权威 API 层)
# ---------------------------------------------------------------------------
#
# 刻意不引 openapi-typescript 之类的 npm 工具:那会给面板加一条构建期依赖,
# 而这个仓库正在往"依赖越少越好"走(刚删掉两条从没被 import 的依赖)。
# 这里只处理 schema 里**实际出现**的形状,遇到没见过的形状**抛异常**而不是
# 吐 ``any`` —— 悄悄降级成 any 的类型文件比没有类型更糟:它看着有保护,实际
# 什么都没挡住。

_HTTP_METHODS = ("get", "post", "put", "delete", "patch", "head", "options")


class UnsupportedSchemaShape(RuntimeError):
    """OpenAPI 里出现了生成器没见过的形状。

    刻意抛异常而不是回退到 ``any``:回退会让生成的类型文件看着完整、实际
    在那个字段上完全失去保护,而且没人会注意到。宁可让生成器当场失败。
    """


def _san(name: str) -> str:
    """组件 schema 名 → 合法的 TS 标识符。"""
    out = "".join(c if c.isalnum() else "_" for c in name)
    return ("S_" + out) if out[:1].isdigit() else out


def _openapi_ts(node: dict, *, where: str) -> str:
    """OpenAPI schema 节点 → TS 类型字符串。"""
    if not isinstance(node, dict):
        raise UnsupportedSchemaShape(f"{where}: 期望 dict,得到 {type(node).__name__}")

    ref = node.get("$ref")
    if ref:
        if not ref.startswith("#/components/schemas/"):
            raise UnsupportedSchemaShape(f"{where}: 不支持的 $ref {ref!r}")
        return _san(ref.rsplit("/", 1)[-1])

    for key in ("anyOf", "oneOf"):
        if key in node:
            parts = [_openapi_ts(x, where=f"{where}.{key}[{i}]") for i, x in enumerate(node[key])]
            # 去重且保持顺序,避免 "string | string"
            seen: list = []
            for p in parts:
                if p not in seen:
                    seen.append(p)
            return " | ".join(seen) if len(seen) > 1 else seen[0]

    if "allOf" in node:
        parts = [_openapi_ts(x, where=f"{where}.allOf[{i}]") for i, x in enumerate(node["allOf"])]
        return " & ".join(parts) if len(parts) > 1 else parts[0]

    if "enum" in node:
        vals = node["enum"]
        lits = []
        for v in vals:
            if isinstance(v, str):
                lits.append(json.dumps(v))
            elif isinstance(v, bool):
                lits.append("true" if v else "false")
            elif isinstance(v, (int, float)):
                lits.append(str(v))
            elif v is None:
                lits.append("null")
            else:
                raise UnsupportedSchemaShape(f"{where}: enum 里有不支持的字面量 {v!r}")
        return " | ".join(lits)

    t = node.get("type")
    if t is None:
        # 无 type、无 $ref、无组合关键字 —— OpenAPI 里这表示"任意值"。
        # 这是**规范里明确的**语义,不是生成器放弃,所以给 unknown 而非 any:
        # unknown 强制消费方先收窄再用,any 会静默传染。
        return "unknown"
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        items = node.get("items")
        if items is None:
            return "unknown[]"
        return f"Array<{_openapi_ts(items, where=f'{where}.items')}>"
    if t == "object":
        props = node.get("properties")
        if props:
            required = set(node.get("required") or [])
            fields = []
            for pname in sorted(props):
                opt = "" if pname in required else "?"
                fields.append(f"  {json.dumps(pname)}{opt}: {_openapi_ts(props[pname], where=f'{where}.{pname}')};")
            extra = node.get("additionalProperties")
            if extra not in (None, False):
                vt = "unknown" if extra is True else _openapi_ts(extra, where=f"{where}.additionalProperties")
                fields.append(f"  [key: string]: {vt};")
            return "{\n" + "\n".join(fields) + "\n}"
        extra = node.get("additionalProperties")
        if extra not in (None, False):
            vt = "unknown" if extra is True else _openapi_ts(extra, where=f"{where}.additionalProperties")
            return f"Record<string, {vt}>"
        return "Record<string, unknown>"
    raise UnsupportedSchemaShape(f"{where}: 不支持的 type {t!r}")


def load_openapi() -> dict:
    """组装权威 API 层并取其 OpenAPI 文档。

    刻意用 ``core.api_routes.create_api_routes()`` 而不是去跑 launcher/services.py:
    前者就是"权威 API 层"本身(``tests/test_routes_import.py`` 也这么建),
    后者会把整个系统拉起来。实测这样建一次约 2.2 秒。
    """
    import logging

    from fastapi import FastAPI

    from core.api_routes import create_api_routes

    prev = logging.root.manager.disable
    logging.disable(logging.CRITICAL)  # 组装过程会打一堆 INFO,生成器不需要
    try:
        app = FastAPI(title="Galaxy V2 Authoritative API")
        app.include_router(create_api_routes())
        return app.openapi()
    finally:
        logging.disable(prev)


def build_api_surface(schema: dict | None = None) -> str:
    """生成 ``types/api.gen.ts``。

    产出三样东西:

    1. ``ApiPath`` —— 全部路径的联合类型。调不存在的端点 → tsc 报错。
    2. ``API_METHODS`` —— 路径 → 允许的方法。对某路径用错方法 → tsc 报错。
    3. 组件 schema 的 TS interface —— 返回体/请求体的字段级类型。

    路径里的 ``{param}`` 原样保留:面板侧是用模板串拼的,保留占位符才能让
    ``ApiPath`` 与源码里写的形态对上。
    """
    schema = schema if schema is not None else load_openapi()
    paths = schema.get("paths", {})
    comps = schema.get("components", {}).get("schemas", {})

    out = [
        "// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.",
        "// 源:core/api_routes.py 组装出的权威 API 层的 OpenAPI 文档。",
        "// 后端加/删/改端点后重跑该脚本;CI 会比对生成结果是否与后端一致。",
        "",
        f"// 路径 {len(paths)} 条 · 组件 schema {len(comps)} 个",
        "",
        "/** 权威 API 层的全部路径。写错或调一个不存在的端点 → 编译期报错。 */",
        "export type ApiPath =",
    ]
    for p in sorted(paths):
        out.append(f"  | {json.dumps(p)}")
    out += [
        ";",
        "",
        "/** 每条路径允许的 HTTP 方法。用错方法 → 编译期报错。 */",
        "export const API_METHODS = {",
    ]
    for p in sorted(paths):
        methods = sorted(m for m in paths[p] if m in _HTTP_METHODS)
        out.append(f"  {json.dumps(p)}: [{', '.join(json.dumps(m) for m in methods)}],")
    out += [
        "} as const satisfies Record<ApiPath, readonly string[]>;",
        "",
        "export type ApiMethod<P extends ApiPath> = (typeof API_METHODS)[P][number];",
        "",
    ]

    if comps:
        out.append("// ── 组件 schema ──")
        out.append("")
        for name in sorted(comps):
            ts = _openapi_ts(comps[name], where=f"components.schemas.{name}")
            if ts.startswith("{"):
                out.append(f"export interface {_san(name)} {ts}")
            else:
                out.append(f"export type {_san(name)} = {ts};")
            out.append("")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for _name, _content in (
        ("ui_element.gen.ts", build()),
        ("phase_contract.gen.ts", build_phase_contract()),
        ("api.gen.ts", build_api_surface()),
    ):
        print(f"wrote {_write(root, _name, _content)}")
