#!/usr/bin/env python3
"""
scripts/gen_node_security_report.py — Per-Node Image Security Report Generator
================================================================================

Generates a lightweight JSON security report for Galaxy node images.
The report includes metadata about the image, SBOM availability, cosign
signature status, and basic dependency statistics.

This script is designed to run in CI after node images are built and
optionally signed.  It produces one JSON file per node (plus a combined
summary) as build artifacts.

Usage
-----
# Generate report for all nodes (or a subset)
python scripts/gen_node_security_report.py \\
    --nodes Node_00_StateMachine Node_02_Tasker \\
    --image-prefix ghcr.io/org/galaxy- \\
    --tag latest \\
    --output-dir /tmp/security-reports

# Generate combined summary only
python scripts/gen_node_security_report.py \\
    --summary-only \\
    --output-dir /tmp/security-reports

# Show all discovered nodes without generating reports
python scripts/gen_node_security_report.py --list-nodes

CLI flags
---------
--nodes         Space-separated list of node names (default: all).
--image-prefix  Docker image name prefix (default: galaxy-node-).
--tag           Docker image tag (default: latest).
--output-dir    Directory to write report files (default: security-reports/).
--sbom-dir      Directory containing SBOM files generated by syft/anchore.
--summary-only  Only write the combined summary; skip per-node files.
--list-nodes    Print discovered node names and exit.
--format        Output format: json (default) or text.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Project layout helpers
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
NODES_DIR = REPO_ROOT / "nodes"


def discover_nodes(nodes_dir: Path = NODES_DIR) -> list[str]:
    """Return sorted list of node directory names under *nodes_dir*."""
    return sorted(
        p.name
        for p in nodes_dir.iterdir()
        if p.is_dir() and p.name.startswith("Node_") and (p / "main.py").exists()
    )


# ---------------------------------------------------------------------------
# Dependency stat helpers
# ---------------------------------------------------------------------------


def _count_requirements(node_name: str) -> dict[str, int]:
    """Count lines in node-specific and root requirements files."""
    node_req = NODES_DIR / node_name / "requirements.txt"
    root_req = REPO_ROOT / "requirements.txt"
    counts: dict[str, int] = {}
    for label, path in [("node_direct", node_req), ("root_direct", root_req)]:
        if path.exists():
            lines = [
                ln.strip()
                for ln in path.read_text().splitlines()
                if ln.strip() and not ln.strip().startswith("#")
            ]
            counts[label] = len(lines)
        else:
            counts[label] = 0
    return counts


# ---------------------------------------------------------------------------
# SBOM & cosign helpers
# ---------------------------------------------------------------------------


def _find_sbom(node_name: str, sbom_dir: Path | None) -> dict[str, Any]:
    """Locate an SBOM file for *node_name* and return basic metadata."""
    if sbom_dir is None:
        return {"present": False, "path": None, "format": None}

    # Anchore SBOM action typically names files: <image-name>.sbom.json
    # syft names them: <image-name>.syft.json or similar
    candidates = list(sbom_dir.glob(f"*{node_name.lower()}*.json")) + list(
        sbom_dir.glob(f"*{node_name.lower()}*.spdx*")
    )
    if not candidates:
        return {"present": False, "path": None, "format": None}

    sbom_file = candidates[0]
    fmt = "spdx-json" if "spdx" in sbom_file.name else "cyclonedx-json"
    component_count: int | None = None
    try:
        data = json.loads(sbom_file.read_text())
        # CycloneDX
        components = data.get("components", [])
        if components:
            component_count = len(components)
        # SPDX
        packages = data.get("packages", [])
        if packages:
            component_count = len(packages)
    except Exception:
        pass

    return {
        "present": True,
        "path": str(sbom_file),
        "format": fmt,
        "component_count": component_count,
    }


def _check_cosign_signature(image_ref: str) -> dict[str, Any]:
    """
    Check whether *image_ref* has a valid cosign signature.

    Returns a dict with keys: ``verified``, ``method``, ``error``.
    This is a best-effort check — it does NOT enforce trust policy.
    """
    try:
        result = subprocess.run(
            ["cosign", "verify", image_ref],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            return {"verified": True, "method": "cosign", "error": None}
        return {
            "verified": False,
            "method": "cosign",
            "error": result.stderr.strip() or "non-zero exit code",
        }
    except FileNotFoundError:
        return {
            "verified": False,
            "method": "cosign",
            "error": "cosign binary not found; skipped",
        }
    except subprocess.TimeoutExpired:
        return {
            "verified": False,
            "method": "cosign",
            "error": "timeout",
        }


def _get_image_digest(image_ref: str) -> str | None:
    """Return the image digest (sha256:…) if docker is available."""
    try:
        result = subprocess.run(
            ["docker", "inspect", "--format", "{{index .RepoDigests 0}}", image_ref],
            capture_output=True,
            text=True,
            timeout=15,
        )
        if result.returncode == 0:
            digest = result.stdout.strip()
            return digest if digest else None
    except Exception:
        pass
    return None


# ---------------------------------------------------------------------------
# Report builder
# ---------------------------------------------------------------------------


def build_node_report(
    node_name: str,
    *,
    image_prefix: str = "galaxy-node-",
    tag: str = "latest",
    sbom_dir: Path | None = None,
    check_signatures: bool = True,
) -> dict[str, Any]:
    """Build and return a security report dict for a single node."""
    timestamp = datetime.now(timezone.utc).isoformat()

    # Derive image reference from node name (e.g. Node_02_Tasker → tasker)
    # Convention: image_prefix + node_name.lower() + :tag
    image_name = node_name.lower().replace("_", "-")
    image_ref = f"{image_prefix}{image_name}:{tag}"

    dep_counts = _count_requirements(node_name)
    sbom_info = _find_sbom(node_name, sbom_dir)

    sig_info: dict[str, Any] = {"verified": False, "method": "skipped", "error": None}
    digest: str | None = None
    if check_signatures:
        sig_info = _check_cosign_signature(image_ref)
        digest = _get_image_digest(image_ref)

    has_dockerfile = (NODES_DIR / node_name / "Dockerfile").exists()
    has_node_requirements = (NODES_DIR / node_name / "requirements.txt").exists()

    report: dict[str, Any] = {
        "schema_version": "1.0",
        "generated_at": timestamp,
        "node": node_name,
        "image": {
            "ref": image_ref,
            "digest": digest,
            "has_dockerfile": has_dockerfile,
        },
        "sbom": sbom_info,
        "signature": sig_info,
        "dependencies": {
            "node_requirements_present": has_node_requirements,
            **dep_counts,
        },
        "hash_locked": (REPO_ROOT / "requirements.hash.txt").exists(),
        "supply_chain_checks": {
            "sbom_present": sbom_info["present"],
            "signature_verified": sig_info.get("verified", False),
            "hash_locked_deps": (REPO_ROOT / "requirements.hash.txt").exists(),
        },
    }
    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--nodes",
        nargs="*",
        default=None,
        help="Node names to report on (default: all discovered nodes).",
    )
    parser.add_argument(
        "--image-prefix",
        default="galaxy-node-",
        help="Docker image name prefix (default: galaxy-node-).",
    )
    parser.add_argument(
        "--tag",
        default="latest",
        help="Docker image tag (default: latest).",
    )
    parser.add_argument(
        "--output-dir",
        default="security-reports",
        help="Directory to write report JSON files (default: security-reports/).",
    )
    parser.add_argument(
        "--sbom-dir",
        default=None,
        help="Directory containing SBOM files to cross-reference.",
    )
    parser.add_argument(
        "--summary-only",
        action="store_true",
        help="Only write combined summary; skip per-node files.",
    )
    parser.add_argument(
        "--list-nodes",
        action="store_true",
        help="Print discovered node names and exit.",
    )
    parser.add_argument(
        "--no-sig-check",
        action="store_true",
        help="Skip cosign signature verification (useful when cosign not installed).",
    )
    parser.add_argument(
        "--format",
        choices=["json", "text"],
        default="json",
        help="Output format for per-node files (default: json).",
    )
    return parser.parse_args(argv)


def _report_to_text(report: dict[str, Any]) -> str:
    """Format a report dict as human-readable text."""
    lines = [
        f"Node: {report['node']}",
        f"Generated: {report['generated_at']}",
        f"Image: {report['image']['ref']}",
        f"  Digest: {report['image'].get('digest') or 'N/A'}",
        f"  Has Dockerfile: {report['image']['has_dockerfile']}",
        "",
        "SBOM:",
        f"  Present: {report['sbom']['present']}",
    ]
    if report["sbom"]["present"]:
        lines += [
            f"  Path:    {report['sbom']['path']}",
            f"  Format:  {report['sbom']['format']}",
            f"  Components: {report['sbom'].get('component_count', 'N/A')}",
        ]
    lines += [
        "",
        "Signature:",
        f"  Verified: {report['signature']['verified']}",
        f"  Method:   {report['signature']['method']}",
    ]
    if report["signature"].get("error"):
        lines.append(f"  Error:    {report['signature']['error']}")
    lines += [
        "",
        "Dependencies:",
        f"  Node-specific requirements.txt present: {report['dependencies']['node_requirements_present']}",
        f"  Node direct deps: {report['dependencies'].get('node_direct', 0)}",
        f"  Root direct deps: {report['dependencies'].get('root_direct', 0)}",
        f"  Hash-locked (requirements.hash.txt): {report['hash_locked']}",
        "",
        "Supply Chain Summary:",
        f"  SBOM present:         {report['supply_chain_checks']['sbom_present']}",
        f"  Signature verified:   {report['supply_chain_checks']['signature_verified']}",
        f"  Hash-locked deps:     {report['supply_chain_checks']['hash_locked_deps']}",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    all_nodes = discover_nodes()
    if args.list_nodes:
        for node in all_nodes:
            print(node)
        return 0

    nodes_to_process = args.nodes if args.nodes else all_nodes
    if not nodes_to_process:
        print("No nodes found.", file=sys.stderr)
        return 1

    sbom_dir = Path(args.sbom_dir) if args.sbom_dir else None
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    reports: list[dict[str, Any]] = []
    for node_name in nodes_to_process:
        if not (NODES_DIR / node_name).exists():
            print(f"Warning: node directory not found: {node_name}", file=sys.stderr)
            continue
        print(f"  Generating report for {node_name} ...", end=" ", flush=True)
        report = build_node_report(
            node_name,
            image_prefix=args.image_prefix,
            tag=args.tag,
            sbom_dir=sbom_dir,
            check_signatures=not args.no_sig_check,
        )
        reports.append(report)

        if not args.summary_only:
            if args.format == "json":
                out_file = output_dir / f"{node_name}.security.json"
                out_file.write_text(json.dumps(report, indent=2))
            else:
                out_file = output_dir / f"{node_name}.security.txt"
                out_file.write_text(_report_to_text(report))
        print("done")

    # Combined summary
    summary = {
        "schema_version": "1.0",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_nodes": len(reports),
        "nodes_with_sbom": sum(1 for r in reports if r["sbom"]["present"]),
        "nodes_with_verified_signature": sum(
            1 for r in reports if r["signature"].get("verified", False)
        ),
        "nodes_with_hash_locked_deps": sum(1 for r in reports if r["hash_locked"]),
        "nodes": [
            {
                "node": r["node"],
                "image_ref": r["image"]["ref"],
                "sbom_present": r["sbom"]["present"],
                "signature_verified": r["signature"]["verified"],
                "hash_locked": r["hash_locked"],
            }
            for r in reports
        ],
    }
    summary_file = output_dir / "security-summary.json"
    summary_file.write_text(json.dumps(summary, indent=2))
    print(f"\n✅  Summary written to {summary_file}")
    print(
        f"   {summary['total_nodes']} nodes | "
        f"{summary['nodes_with_sbom']} with SBOM | "
        f"{summary['nodes_with_verified_signature']} signed | "
        f"{summary['nodes_with_hash_locked_deps']} hash-locked"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
