#!/usr/bin/env python3
"""scripts/gen_ts_types.py — 后端契约 → TypeScript 类型(单一真相源,去前后端漂移)

后端改字段、前端立刻类型报错,不再靠手写 interface 悄悄漂移。

覆盖两组契约,各写各的文件:

* ``core.schemas.ui_element``  → ``types/ui_element.gen.ts``
  结构化 UI 契约(UISource/UIActionKind/UIBounds/UIElementNode/UIGraph)。

* ``core.phase_contract``      → ``types/phase_contract.gen.ts``
  面板侧相位姿态:离散三态 + 后端一直在算的连续量(在场强度/塌缩与回撤倾向/
  稳定度)。加这一组的起因是:那些连续量在 ContinuumState 里算了很久,却在
  在场桥那一步被三个硬编码常数顶掉,前端从来没见过。既然要送出去,类型就该
  从后端生成,而不是前端再手写一份 —— 那正是这个脚本存在的理由。

不做通用 Pydantic→TS 转换器(那会引入一堆边角复杂度)。重跑本脚本即可再生成。
"""

from __future__ import annotations

import enum
import os
import sys
import typing
from typing import get_args, get_origin

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pydantic import BaseModel

import core.phase_contract as phase_contract
import core.schemas.ui_element as ui

_ENUMS = [ui.UISource, ui.UIActionKind]
_MODELS = [ui.UIBounds, ui.UIElementNode, ui.UIGraph]

_SCALAR = {str: "string", int: "number", float: "number", bool: "boolean"}


def _ts_type(ann: typing.Any) -> str:
    """Python 类型注解 → TS 类型字符串。"""
    if ann in _SCALAR:
        return _SCALAR[ann]
    if isinstance(ann, type) and issubclass(ann, enum.Enum):
        return ann.__name__
    if isinstance(ann, type) and issubclass(ann, BaseModel):
        return ann.__name__

    origin = get_origin(ann)
    args = get_args(ann)
    if origin in (list, typing.List):
        return f"{_ts_type(args[0])}[]"
    if origin in (dict, typing.Dict):
        return "Record<string, unknown>"
    # Optional[X] / Union[X, None]
    if origin is typing.Union:
        non_none = [a for a in args if a is not type(None)]
        inner = " | ".join(_ts_type(a) for a in non_none)
        return f"{inner} | null" if len(args) > len(non_none) else inner
    if ann is typing.Any or ann is object:
        return "unknown"
    return "unknown"


def _emit_enum(e: type) -> str:
    members = " | ".join(f'"{m.value}"' for m in e)
    return f"export type {e.__name__} = {members};"


def _emit_model(m: type) -> str:
    lines = [f"export interface {m.__name__} {{"]
    for name, field in m.model_fields.items():
        ts = _ts_type(field.annotation)
        # 有默认值 / Optional → 可选字段
        optional = (not field.is_required()) or ts.endswith("| null")
        q = "?" if optional else ""
        lines.append(f"  {name}{q}: {ts};")
    lines.append("}")
    return "\n".join(lines)


def build_phase_contract() -> str:
    """相位契约 → TS。

    这一组不是 Pydantic 模型而是 dataclass + 一份显式 schema 描述
    (``phase_contract_schema()``),因为生成器需要的信息比 JSON Schema 更具体:
    哪些字段是 [0,1] 归一量、``source`` 的取值域是什么。手写那份描述比让
    生成器去猜可靠。

    锚点常量也一并导出:前端做过渡编排时要知道三档各在深度轴的哪个位置,
    此前那三个数在 TS 侧是另写一份的,改后端就会漂。
    """
    sch = phase_contract.phase_contract_schema()
    lines = [
        "// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.",
        "// 源:core/phase_contract.py(面板侧相位契约 SSOT)。改后端字段后重跑该脚本。",
        "",
        "/**",
        " * 后端【线上】传输的三态 token。",
        " *",
        " * 刻意不叫 `Phase`：面板自己的 `types/phase.ts` 里已有一个 `Phase`,",
        " * 取值是 'silent' | 'liminal' | 'manifest'（展示词汇），而后端发的是",
        " * 'static'（见 core/desktop_presence_system.py 的 STATIC）。两者同名不同义，",
        " * 一起 import 会撞。转换由 usePhase.ts 的 _mapPhaseToken 负责。",
        " *",
        " * 连续量只描述它在这一档里的位置，不改变是哪一档。",
        " */",
        "export type WirePhase = " + " | ".join(f'"{p}"' for p in sch["phases"]) + ";",
        "",
        "/** depth 是实算的还是锚点兜底。前端可据此区分精确态/估计态。 */",
        "export type PhasePostureSource = " + " | ".join(f'"{s}"' for s in sch["sources"]) + ";",
        "",
        "/** 三态在渲染深度轴上的锚点。前端过渡编排按这几个数调。 */",
        "export const PHASE_ANCHORS: Record<WirePhase, number> = {",
    ]
    for name, val in sch["anchors"].items():
        lines.append(f'  "{name}": {val},')
    lines += [
        "};",
        "",
        "/** 边缘混合上限:倾向为 1 时深度最多向邻档漂移两档间距的这个比例。 */",
        f"export const PHASE_EDGE_BLEND = {sch['edge_blend']};",
        "",
        "export interface PhasePosture {",
    ]
    for f in sch["fields"]:
        lines.append(f"  /** {f['doc']} */")
        lines.append(f"  {f['name']}: {f['ts']};")
    lines += ["}", ""]
    return "\n".join(lines)


def build() -> str:
    parts = [
        "// AUTO-GENERATED by scripts/gen_ts_types.py — DO NOT EDIT BY HAND.",
        "// 源:core/schemas/ui_element.py(结构化 UI 契约 SSOT)。改后端字段后重跑该脚本。",
        "",
    ]
    parts += [_emit_enum(e) for e in _ENUMS]
    parts.append("")
    parts += [_emit_model(m) for m in _MODELS]
    parts.append("")
    return "\n".join(parts)


def _write(root: str, filename: str, content: str) -> str:
    out = os.path.join(root, "electron", "renderer", "panel", "src", "types", filename)
    with open(out, "w", encoding="utf-8") as f:
        f.write(content)
    return out


if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for _name, _content in (
        ("ui_element.gen.ts", build()),
        ("phase_contract.gen.ts", build_phase_contract()),
    ):
        print(f"wrote {_write(root, _name, _content)}")
