#!/usr/bin/env python3
"""
UFO Galaxy Launcher v2.0
DeepSeek Audited Architecture - Smart Startup Orchestrator

Features:
- Phased startup sequence
- Health check verification
- Environment detection (Docker/Podman/Termux)
- Automatic .env generation
- Graceful shutdown
"""

import os
import sys
import time
import json
import subprocess
import argparse
import platform
from typing import List, Dict, Optional
from dataclasses import dataclass
from enum import Enum

# =============================================================================
# Configuration
# =============================================================================

class Environment(Enum):
    DOCKER = "docker"
    PODMAN = "podman"
    TERMUX = "termux"
    NATIVE = "native"

@dataclass
class NodeConfig:
    node_id: str
    name: str
    layer: str
    critical: bool = False
    depends_on: List[str] = None
    health_endpoint: str = "/health"
    port: int = 8000

# Startup sequence from DeepSeek audit
STARTUP_PHASES = [
    # Phase 0: Core Infrastructure
    {
        "name": "Kernel Core",
        "nodes": ["redis", "node_00_statemachine"],
        "wait_seconds": 5,
        "critical": True
    },
    # Phase 1: Security & Config
    {
        "name": "Security Layer",
        "nodes": ["node_03_secretvault", "node_68_security"],
        "wait_seconds": 3,
        "critical": True
    },
    # Phase 2: Gateways
    {
        "name": "Gateway Layer",
        "nodes": ["node_50_transformer", "node_58_modelrouter"],
        "wait_seconds": 3,
        "critical": True
    },
    # Phase 3: Tools (Parallel)
    {
        "name": "Tools Layer",
        "nodes": ["node_06_filesystem", "node_07_git"],
        "wait_seconds": 2,
        "critical": False,
        "parallel": True
    },
    # Phase 4: Physical (Serial - prevent USB surge)
    {
        "name": "Physical Layer",
        "nodes": ["node_33_adb", "node_34_scrcpy", "node_49_octoprint"],
        "wait_seconds": 2,
        "critical": False,
        "parallel": False
    }
]

# =============================================================================
# Environment Detection
# =============================================================================

def detect_environment() -> Environment:
    """Detect the current runtime environment."""
    
    # Check for Termux
    if os.path.exists("/data/data/com.termux"):
        return Environment.TERMUX
    
    # Check for Podman
    if subprocess.run(["which", "podman"], capture_output=True).returncode == 0:
        return Environment.PODMAN
    
    # Check for Docker
    if subprocess.run(["which", "docker"], capture_output=True).returncode == 0:
        return Environment.DOCKER
    
    return Environment.NATIVE

def get_compose_command(env: Environment) -> List[str]:
    """Get the appropriate compose command for the environment."""
    if env == Environment.PODMAN:
        return ["podman-compose"]
    elif env == Environment.DOCKER:
        return ["docker", "compose"]
    else:
        return ["docker", "compose"]  # Default

# =============================================================================
# .env Generator
# =============================================================================

ENV_TEMPLATE = """# UFO Galaxy Configuration
# Generated by launcher_v2.py

# =============================================================================
# API Keys (Required for cloud models)
# =============================================================================
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=

# =============================================================================
# Local Model Configuration
# =============================================================================
OLLAMA_URL=http://host.containers.internal:11434
OLLAMA_MODEL=llama2

# =============================================================================
# Hardware Configuration
# =============================================================================
# OctoPrint (3D Printer)
OCTOPRINT_URL=http://localhost:5000
OCTOPRINT_API_KEY=

# ADB Configuration
ADB_DEVICE=emulator-5554

# =============================================================================
# System Configuration
# =============================================================================
LOG_LEVEL=INFO
USE_MOCK_DRIVERS=true

# =============================================================================
# Network Configuration
# =============================================================================
STATE_MACHINE_URL=http://node_00_statemachine:8000
SECURITY_URL=http://node_68_security:8068
TRANSFORMER_URL=http://node_50_transformer:8050
"""

def generate_env_file(path: str, force: bool = False):
    """Generate .env file with placeholders."""
    if os.path.exists(path) and not force:
        print(f"⚠️  .env file already exists at {path}")
        print("   Use --force to overwrite")
        return False
    
    with open(path, "w") as f:
        f.write(ENV_TEMPLATE)
    
    print(f"✅ Generated .env file at {path}")
    return True

# =============================================================================
# Whitelist Generator
# =============================================================================

WHITELIST_TEMPLATE = {
    "version": "1.0",
    "description": "UFO Galaxy Security Whitelist",
    "rules": [
        {"source": "50", "target": "33", "action": "*", "allow": True, "comment": "Node 50 -> ADB"},
        {"source": "50", "target": "34", "action": "*", "allow": True, "comment": "Node 50 -> Scrcpy"},
        {"source": "50", "target": "49", "action": "*", "allow": True, "comment": "Node 50 -> OctoPrint"},
        {"source": "58", "target": "50", "action": "*", "allow": True, "comment": "Node 58 -> Transformer"},
        {"source": "*", "target": "00", "action": "*", "allow": True, "comment": "All -> State Machine"},
        {"source": "*", "target": "68", "action": "*", "allow": True, "comment": "All -> Security"},
    ],
    "deny_rules": [
        {"source": "L3_PHYSICAL", "target": "L3_PHYSICAL", "action": "*", "allow": False, "comment": "L3 isolation"},
        {"source": "L3_PHYSICAL", "target": "external", "action": "*", "allow": False, "comment": "L3 no internet"},
    ]
}

def generate_whitelist(path: str, force: bool = False):
    """Generate whitelist.json file."""
    if os.path.exists(path) and not force:
        print(f"⚠️  whitelist.json already exists at {path}")
        return False
    
    with open(path, "w") as f:
        json.dump(WHITELIST_TEMPLATE, f, indent=2)
    
    print(f"✅ Generated whitelist.json at {path}")
    return True

# =============================================================================
# Launcher
# =============================================================================

class GalaxyLauncher:
    """UFO Galaxy System Launcher."""
    
    def __init__(self, project_dir: str, env: Environment):
        self.project_dir = project_dir
        self.env = env
        self.compose_cmd = get_compose_command(env)
        self.compose_file = os.path.join(project_dir, "podman-compose.yml")
    
    def _run_compose(self, args: List[str], check: bool = True) -> subprocess.CompletedProcess:
        """Run a compose command."""
        cmd = self.compose_cmd + ["-f", self.compose_file] + args
        print(f"   Running: {' '.join(cmd)}")
        return subprocess.run(cmd, cwd=self.project_dir, check=check, capture_output=True, text=True)
    
    def check_prerequisites(self) -> bool:
        """Check if all prerequisites are met."""
        print("🔍 Checking prerequisites...")
        
        # Check compose file
        if not os.path.exists(self.compose_file):
            print(f"❌ Compose file not found: {self.compose_file}")
            return False
        
        # Check .env file
        env_file = os.path.join(self.project_dir, "config", ".env")
        if not os.path.exists(env_file):
            print(f"⚠️  .env file not found, generating...")
            os.makedirs(os.path.dirname(env_file), exist_ok=True)
            generate_env_file(env_file)
        
        # Check whitelist
        whitelist_file = os.path.join(self.project_dir, "config", "whitelist.json")
        if not os.path.exists(whitelist_file):
            print(f"⚠️  whitelist.json not found, generating...")
            generate_whitelist(whitelist_file)
        
        # Check container runtime
        try:
            result = subprocess.run(self.compose_cmd[:1] + ["--version"], capture_output=True, text=True)
            print(f"✅ Container runtime: {result.stdout.strip()}")
        except Exception as e:
            print(f"❌ Container runtime not available: {e}")
            return False
        
        print("✅ Prerequisites check passed")
        return True
    
    def build(self) -> bool:
        """Build all container images."""
        print("\n🔨 Building container images...")
        
        try:
            result = self._run_compose(["build"])
            print("✅ Build completed")
            return True
        except subprocess.CalledProcessError as e:
            print(f"❌ Build failed: {e.stderr}")
            return False
    
    def start_phase(self, phase: Dict) -> bool:
        """Start a single phase of the startup sequence."""
        phase_name = phase["name"]
        nodes = phase["nodes"]
        wait_seconds = phase.get("wait_seconds", 3)
        critical = phase.get("critical", False)
        parallel = phase.get("parallel", True)
        
        print(f"\n📦 Phase: {phase_name}")
        print(f"   Nodes: {', '.join(nodes)}")
        
        for node in nodes:
            try:
                print(f"   Starting {node}...")
                result = self._run_compose(["up", "-d", node], check=False)
                
                if result.returncode != 0:
                    print(f"   ⚠️  Warning: {result.stderr}")
                    if critical:
                        print(f"❌ Critical node {node} failed to start")
                        return False
                else:
                    print(f"   ✅ {node} started")
                
                if not parallel:
                    time.sleep(1)  # Serial startup delay
                    
            except Exception as e:
                print(f"   ❌ Error starting {node}: {e}")
                if critical:
                    return False
        
        print(f"   Waiting {wait_seconds}s for health checks...")
        time.sleep(wait_seconds)
        
        return True
    
    def start(self, skip_build: bool = False) -> bool:
        """Start the UFO Galaxy system."""
        print("""
╔═══════════════════════════════════════════════════════════╗
║         UFO Galaxy 64-Core MCP Matrix                     ║
║         Launcher v2.0 - DeepSeek Audited                  ║
╚═══════════════════════════════════════════════════════════╝
        """)
        
        print(f"🌍 Environment: {self.env.value}")
        print(f"📁 Project: {self.project_dir}")
        
        if not self.check_prerequisites():
            return False
        
        if not skip_build:
            if not self.build():
                return False
        
        print("\n🚀 Starting UFO Galaxy...")
        
        for i, phase in enumerate(STARTUP_PHASES):
            print(f"\n{'='*60}")
            print(f"Phase {i}/{len(STARTUP_PHASES)-1}: {phase['name']}")
            print(f"{'='*60}")
            
            if not self.start_phase(phase):
                print(f"\n❌ Startup failed at phase: {phase['name']}")
                return False
        
        print("\n" + "="*60)
        print("🎉 UFO Galaxy started successfully!")
        print("="*60)
        
        self.show_status()
        
        return True
    
    def stop(self) -> bool:
        """Stop the UFO Galaxy system."""
        print("\n🛑 Stopping UFO Galaxy...")
        
        try:
            self._run_compose(["down"])
            print("✅ UFO Galaxy stopped")
            return True
        except subprocess.CalledProcessError as e:
            print(f"❌ Stop failed: {e.stderr}")
            return False
    
    def show_status(self):
        """Show system status."""
        print("\n📊 System Status:")
        
        try:
            result = self._run_compose(["ps"], check=False)
            print(result.stdout)
        except Exception as e:
            print(f"⚠️  Could not get status: {e}")
        
        print("\n🔗 Endpoints:")
        print("   State Machine: http://localhost:8000")
        print("   Transformer:   http://localhost:8050")
        print("   Model Router:  http://localhost:8058")
        print("\n📖 API Docs:")
        print("   http://localhost:8000/docs")
        print("   http://localhost:8050/docs")
        print("   http://localhost:8058/docs")
    
    def logs(self, service: str = None, follow: bool = False):
        """Show logs."""
        args = ["logs"]
        if follow:
            args.append("-f")
        if service:
            args.append(service)
        
        try:
            if follow:
                subprocess.run(self.compose_cmd + ["-f", self.compose_file] + args, cwd=self.project_dir)
            else:
                result = self._run_compose(args, check=False)
                print(result.stdout)
        except KeyboardInterrupt:
            pass

# =============================================================================
# Main
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="UFO Galaxy Launcher v2.0",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s start              # Start the system
  %(prog)s start --skip-build # Start without rebuilding
  %(prog)s stop               # Stop the system
  %(prog)s status             # Show status
  %(prog)s logs               # Show logs
  %(prog)s logs -f node_00    # Follow logs for node_00
  %(prog)s init               # Generate config files
        """
    )
    
    parser.add_argument("command", choices=["start", "stop", "status", "logs", "init", "build"],
                       help="Command to execute")
    parser.add_argument("--project-dir", "-d", default=".",
                       help="Project directory (default: current)")
    parser.add_argument("--skip-build", action="store_true",
                       help="Skip building images")
    parser.add_argument("--follow", "-f", action="store_true",
                       help="Follow logs")
    parser.add_argument("--service", "-s",
                       help="Service name for logs")
    parser.add_argument("--force", action="store_true",
                       help="Force overwrite existing files")
    
    args = parser.parse_args()
    
    # Resolve project directory
    project_dir = os.path.abspath(args.project_dir)
    
    # Detect environment
    env = detect_environment()
    
    # Create launcher
    launcher = GalaxyLauncher(project_dir, env)
    
    # Execute command
    if args.command == "init":
        os.makedirs(os.path.join(project_dir, "config"), exist_ok=True)
        generate_env_file(os.path.join(project_dir, "config", ".env"), args.force)
        generate_whitelist(os.path.join(project_dir, "config", "whitelist.json"), args.force)
        print("\n✅ Initialization complete!")
        print("   Edit config/.env to add your API keys")
        
    elif args.command == "start":
        success = launcher.start(skip_build=args.skip_build)
        sys.exit(0 if success else 1)
        
    elif args.command == "stop":
        success = launcher.stop()
        sys.exit(0 if success else 1)
        
    elif args.command == "status":
        launcher.show_status()
        
    elif args.command == "logs":
        launcher.logs(service=args.service, follow=args.follow)
        
    elif args.command == "build":
        success = launcher.build()
        sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()
